//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Kalendar.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define RT_MANIFEST                     24
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDR_MENU_YEAR                   130
#define IDR_MENU_MONTH                  131
#define IDR_MENU_HOUR                   137
#define IDR_MENU_MINUTE                 138
#define IDR_MENU_NOON                   139
#define IDR_MENU_DIVISION_NO            140
#define IDB_BITMAP_MEMO_BACKIMAGE       141
#define IDB_BITMAP_CHECKMARK            142
#define IDB_BITMAP_LIST_BACKIMAGE       144
#define IDB_BITMAP_SEARCH               147
#define IDB_BITMAP_MONTH_1              150
#define IDB_BITMAP_MONTH_2              151
#define IDB_BITMAP_MONTH_3              152
#define IDB_BITMAP_MONTH_4              153
#define IDB_BITMAP_MONTH_5              154
#define IDB_BITMAP_MONTH_6              155
#define IDB_BITMAP_MONTH_7              156
#define IDB_BITMAP_MONTH_8              157
#define IDB_BITMAP_MONTH_9              158
#define IDB_BITMAP_MONTH_10             159
#define IDD_DIALOG_SEQ                  159
#define IDB_BITMAP_MONTH_11             160
#define IDB_BITMAP_MONTH_12             161
#define IDB_BITMAP_BG_MAIN              163
#define IDB_BITMAP_MONTH_ENG_1          164
#define IDB_BITMAP_MONTH_ENG_2          165
#define IDB_BITMAP_MONTH_ENG_3          166
#define IDB_BITMAP_MONTH_ENG_4          167
#define IDB_BITMAP_MONTH_ENG_5          168
#define IDB_BITMAP_MONTH_ENG_6          169
#define IDB_BITMAP_MONTH_ENG_7          170
#define IDB_BITMAP_MONTH_ENG_8          171
#define IDB_BITMAP_MONTH_ENG_9          172
#define IDB_BITMAP_MONTH_ENG_10         173
#define IDB_BITMAP_MONTH_ENG_11         174
#define IDB_BITMAP_MONTH_ENG_12         175
#define IDB_BITMAP_YEAR_0               176
#define IDB_BITMAP_YEAR_1               177
#define IDB_BITMAP_YEAR_2               178
#define IDB_BITMAP_YEAR_3               179
#define IDB_BITMAP_YEAR_4               180
#define IDB_BITMAP_YEAR_5               181
#define IDB_BITMAP_YEAR_6               182
#define IDB_BITMAP_YEAR_7               183
#define IDB_BITMAP_YEAR_8               184
#define IDB_BITMAP_YEAR_9               185
#define IDB_BITMAP_BUTTON_LISTVIEW      186
#define IDB_BITMAP_BUTTON_NEXTMONTH     187
#define IDB_BITMAP_BUTTON_PREVMONTH     188
#define IDB_BITMAP_BUTTON_SEARCH        189
#define IDB_BITMAP_DAY_NULL             190
#define IDB_BITMAP_DAY_BLACK_0          191
#define IDB_BITMAP_DAY_BLACK_1          192
#define IDB_BITMAP_DAY_BLACK_2          193
#define IDB_BITMAP_DAY_BLACK_3          194
#define IDB_BITMAP_DAY_BLACK_4          195
#define IDB_BITMAP_DAY_BLACK_5          196
#define IDB_BITMAP_DAY_BLACK_6          197
#define IDB_BITMAP_DAY_BLACK_7          198
#define IDB_BITMAP_DAY_BLACK_8          199
#define IDB_BITMAP_DAY_BLACK_9          200
#define IDB_BITMAP_DAY_RED_0            214
#define IDB_BITMAP_DAY_RED_1            215
#define IDB_BITMAP_DAY_RED_2            216
#define IDB_BITMAP_DAY_RED_3            217
#define IDB_BITMAP_DAY_RED_4            218
#define IDB_BITMAP_DAY_RED_5            219
#define IDB_BITMAP_DAY_RED_6            220
#define IDB_BITMAP_DAY_RED_7            221
#define IDB_BITMAP_DAY_RED_8            222
#define IDB_BITMAP_DAY_RED_9            223
#define IDB_BITMAP_DAY_BLUE_0           224
#define IDB_BITMAP_DAY_BLUE_1           225
#define IDB_BITMAP_DAY_BLUE_2           226
#define IDB_BITMAP_DAY_BLUE_3           227
#define IDB_BITMAP_DAY_BLUE_4           228
#define IDB_BITMAP_DAY_BLUE_5           229
#define IDB_BITMAP_DAY_BLUE_6           230
#define IDB_BITMAP_DAY_BLUE_7           231
#define IDB_BITMAP_DAY_BLUE_8           232
#define IDB_BITMAP_DAY_BLUE_9           233
#define IDB_BITMAP_TODAY                234
#define IDB_BITMAP_HOLIDAY              235
#define IDB_BITMAP_TODAY_HOLIDAY        236
#define IDB_BITMAP_BUTTON_MINISEARCH    237
#define IDR_MENU_RICHEDIT               240
#define IDB_BITMAP_BUTTON_CLOSE         243
#define IDB_BITMAP_CLOSE_KALENDAR       251
#define IDB_BITMAP_DIVISION_NO          261
#define IDB_BITMAP_BUTTON_TODAY         262
#define IDB_BITMAP_BUTTON_MEMO          263
#define IDB_BITMAP_BUTTON_CLOSE_RED     266
#define IDB_BITMAP_ALARM_BACKIMAGE      267
#define IDB_BITMAP_BUTTON_XP_STYLE      268
#define IDB_BITMAP_BUTTON_DROPDOWN_T    270
#define IDB_BITMAP_BUTTON_DROPDOWN_B    271
#define IDB_BITMAP_BUTTON_DROPDOWN_R    272
#define IDB_BITMAP_BUTTON_DROPDOWN_L    273
#define IDM_RMOUSE_CLICK                274
#define IDB_DAY                         274
#define IDC_BUTTON_VIEW                 1050
#define IDC_BUTTON_SEARCH               1051
#define IDC_BUTTON_YEAR                 1052
#define IDC_BUTTON_MONTH                1053
#define IDC_BUTTON_PREV_MONTH           1054
#define IDC_BUTTON_NEXT_MONTH           1055
#define IDC_BUTTON_MONTH_ENG            1056
#define IDC_BUTTON_SEQ_MODE             1057
#define IDC_BUTTON_MEMO_MODE            1058
#define IDC_BUTTON_TODAY                1059
#define IDC_EDIT_SEARCH_TEXT            1075
#define IDC_EDIT_YEAR                   1076
#define IDC_LIST_MEMO                   1079
#define IDC_STATIC_DATE                 1080
#define IDC_BUTTON_HOUR                 1081
#define IDC_BUTTON_MIN                  1082
#define IDC_BUTTON_NOON                 1083
#define IDC_BUTTON_ALARM                1084
#define IDC_RICHEDIT_DAY                1152
#define IDC_RICHEDIT_TEXT               1153
#define IDC_RICHEDIT_MEMORIALDAY        1155
#define IDC_STATIC_DAY                  1156
#define IDC_RICHEDIT_MEMO_TEXT          1157
#define IDC_CHECK_ALARM                 1159
#define IDC_STATIC_TITLE                1160
#define IDC_STATIC_HOLIDAY              1166
#define IDC_STATIC_TODAY                1167
#define IDC_STATIC_TODAY_HOLIDAY        1168
#define IDC_STATIC_YEAR                 1171
#define IDC_STATIC_ALARM_TITLE          1173
#define IDC_RICHEDIT_ALARM_TEXT         1174
#define ID_BUTTON_ALARM_OK              1176
#define ID_BUTTON_MEMO_OK               1178
#define IDC_BUTTON_CLOSE                1180
#define IDC_STATIC_BG                   1181
#define IDC_BUTTON_DROPDOWN_T           1182
#define IDC_BUTTON_DROPDOWN_B           1183
#define IDC_BUTTON_DROPDOWN_L           1184
#define IDC_BUTTON_DROPDOWN_R           1185
#define IDD_Kalendar_DIALOG             5234
#define IDD_DIALOG_SEARCH               5235
#define IDD_DIALOG_LISTVIEW             5236
#define IDD_DIALOG_DAY                  5237
#define IDD_DIALOG_MEMO                 5238
#define IDD_DIALOG_ALARM                5239
#define ID_DIVISION_NO1                 31000
#define ID_DIVISION_NO2                 31001
#define ID_DIVISION_NO3                 31002
#define ID_DIVISION_NO100               31099
#define ID_MONTH                        32777
#define ID_MONTH_1                      32778
#define ID_MONTH_2                      32779
#define ID_MONTH_3                      32780
#define ID_MONTH_4                      32781
#define ID_MONTH_5                      32782
#define ID_MONTH_6                      32783
#define ID_MONTH_7                      32784
#define ID_MONTH_8                      32785
#define ID_MONTH_9                      32786
#define ID_MONTH_10                     32787
#define ID_MONTH_11                     32788
#define ID_MONTH_12                     32789
#define ID_YEAR                         32790
#define ID_YEAR_PREV_5                  32791
#define ID_YEAR_PREV_4                  32792
#define ID_YEAR_PREV_3                  32793
#define ID_YEAR_PREV_2                  32794
#define ID_YEAR_PREV_1                  32795
#define ID_YEAR_                        32796
#define ID_YEAR_NEXT_1                  32797
#define ID_YEAR_NEXT_2                  32798
#define ID_YEAR_NEXT_3                  32799
#define ID_YEAR_NEXT_4                  32800
#define ID_YEAR_NEXT_5                  32801
#define ID_HOUR_1                       32802
#define ID_HOUR_2                       32803
#define ID_HOUR_3                       32804
#define ID_HOUR_4                       32805
#define ID_HOUR_5                       32806
#define ID_HOUR_6                       32807
#define ID_HOUR_7                       32808
#define ID_HOUR_8                       32809
#define ID_HOUR_9                       32810
#define ID_HOUR_10                      32811
#define ID_HOUR_11                      32812
#define ID_HOUR_12                      32813
#define ID_MIN_15                       32814
#define ID_MIN_30                       32815
#define ID_MIN_45                       32816
#define ID_MIN_0                        32817
#define ID_NOON_FORE                    32818
#define ID_NOON_AFTER                   32819
#define ID_TIMER_ALARMTIME              32821
#define ID_AFTER_5_MIN                  32829
#define ID_AFTER_10_MIN                 32830
#define ID_AFTER_30_MIN                 32831
#define ID_RICHEDIT_COPY                32832
#define ID_RICHEDIT_PASTE               32833
#define ID_RICHEDIT_CLEAR               32834
#define ID_RICHEDIT_SELECTALL           32835
#define ID_TIMER_WAIT_SET_KALENDAR      32836
#define ID_TIMER_FOR_MOUSE_WITHOUT_DLGSEQ_CLIENT 32837
#define ID_TIMER_WAIT_SEND_DIVISION_NO_TO_KOLASIII 32838
#define ID_MENU_REFRESH                 32840

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        276
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1187
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
