/ Copyright(c) 1997, 1999, 2000 by the Oracle Corporation.  All rights reserved.
/
/ $Header: /K2UP_CVS/Repository/KOLAS III/ORACLE/network/mesg/vpxoafndus.msg,v 1.1 2009/12/09 02:30:38 ╧за╬©Н Exp $
/
/
/ NAME
/   vpxoafndus.msg
/
/
/ FUNCTION
/   Oracle Data Gatherer Oracle Database cartridge message file, American
/   English version.
/
/
/ HISTORY
/       asawant - recreate from scratch
/
/
/ NOTES
/       Message text should be limited to a maximum of 76 characters.
/       Messages containing embedded % directives should not overrun
/       the 76 character limit unless they signal unusual errors
/       which do not occur as part of user applications.  For example,
/       startup errors and system-dependent errors can probably get
/       away with longer message text.
/
/
/       '/' at beginning-of-line for comments.
/       '//' at beginning-of-line for *Cause: And *Action: fields.
/
/
///////////////////////////////////////////////////////////////////////////
01001, 00000, "Abi Dummy Module Name"
// *Comment: mnemonic:
/
01002, 00000, "Oracle Applications Performance Statistics"
// *Comment: mnemonic:
/
01003, 00000, "Module"
// *Comment: mnemonic:
/
01004, 00000, "SQL"
// *Comment: mnemonic:
/
01005, 00000, "Columns returned by the SQL statement will be building blocks for the user-defined chart's resources."
// *Comment: mnemonic:
/
01006, 00000, "Error: failed to allocate memory."
// *Comment: mnemonic:
/
01007, 00000, "Error: failed to free memory."
// *Comment: mnemonic:
/
01008, 00000, "Error: call to vpx_get_class_byid() failed."
// *Comment: mnemonic:
/
01009, 00000, "Error: call to vppgetcltype() failed."
// *Comment: mnemonic:
/
01010, 00000, "Error: call to vpx_get_classes_request() failed."
// *Comment: mnemonic:
/
01011, 00000, "Error: call to vpx_get_chart_byid() failed."
// *Comment: mnemonic:
/
01012, 00000, "Error: call to vpx_get_callback_byid() failed."
// *Comment: mnemonic:
/
01013, 00000, "Error: call to vpx_start_collection() failed."
// *Comment: mnemonic:
/
01014, 00000, "Error: call to vpx_stop_collection() failed."
// *Comment: mnemonic:
/
01015, 00000, "Error: call to vp_send_instance() failed."
// *Comment: mnemonic:
/
01016, 00000, "Error: call to vpx_get_catinfo() failed."
// *Comment: mnemonic:
/
01017, 00000, "Error: call to vpx_get_catmsg() failed."
// *Comment: mnemonic:
/
01018, 00000, "Error: call to vp_send_callback_status() failed."
// *Comment: mnemonic:
/
01019, 00000, "Error: call to vpp_add_parameter() failed."
// *Comment: mnemonic:
/
01020, 00000, "Error: call to vpp_send() failed."
// *Comment: mnemonic:
/
01021, 00000, "Error: call to vpx_end_var_data() failed."
// *Comment: mnemonic:
/
01022, 00000, "Error: call to vp_send_extended_help() failed."
// *Comment: mnemonic:
/
01023, 00000, "Error: undefined data type."
// *Comment: mnemonic:
/
01024, 00000, "Error: failed on data conversion."
// *Comment: mnemonic:
/
01025, 00000, "Error: no nested class."
// *Comment: mnemonic:
/
01026, 00000, "Error: inconsistent static state."
// *Comment: mnemonic:
/
01027, 00000, "Error: inexistent client."
// *Comment: mnemonic:
/
01028, 00000, "Error: failed while searching client data."
// *Comment: mnemonic:
/
01029, 00000, "Error: failed while searching request data."
// *Comment: mnemonic:
/
01030, 00000, "Error: too many columns."
// *Comment: mnemonic:
/
01031, 00000, "Error: instance name size is too big."
// *Comment: mnemonic:
/
01032, 00000, "Error: the call to the callback function failed."
// *Comment: mnemonic:
/
01100, 00000, "Error: Invalid credential list."
// *Comment: mnemonic:
/
01101, 00000, "Error: Unknown Oracle Applications version."
// *Comment: mnemonic:
/
01102, 00000, "Error: Unknown collection parameter string."
// *Comment: mnemonic:
/
01150, 00000, "Error: [OCI] Unknown OCI error."
// *Comment: mnemonic:
/
01151, 00000, "Error: [OCI] Success with info."
// *Comment: mnemonic:
/
01152, 00000, "Error: [OCI] Need data."
// *Comment: mnemonic:
/
01153, 00000, "Error: [OCI] Invalid Handler."
// *Comment: mnemonic:
/
01154, 00000, "Error: [OCI] Still executing."
// *Comment: mnemonic:
/
01155, 00000, "Error: [OCI] Continue."
// *Comment: mnemonic:
/
01156, 00000, "Error: [OCI] Unkown return code."
// *Comment: mnemonic:
/
01157, 00000, "Error: [OCI] Handle not found."
// *Comment: mnemonic:
/
01158, 00000, "Error: [OCI] Unexpected OCI error."
// *Comment: mnemonic:
/
01159, 00000, "ORA-12154: TNS:could not resolve service name"
// *Comment: mnemonic:
/
01160, 00000, "ORA-01017: invalid username/passord; logon denied"
// *Comment: mnemonic:
/
01200, 00000, "System Overview"
// *Comment: mnemonic:
/
01201, 00000, "Applications System Overview"
// *Comment: mnemonic:
/
01202, 00000, "System Overview Instances"
// *Comment: mnemonic:
/
01203, 00000, "Form Sessions and Concurrent Requests"
// *Comment: mnemonic:
/
01204, 00000, "Form Sessions and Concurrent Requests Activity"
// *Comment: mnemonic:
/
01205, 00000, "Oracle Applications Instance"
// *Comment: mnemonic:
/
01206, 00000, "Form Sessions"
// *Comment: mnemonic:
/
01207, 00000, "Form Sessions Instance ID"
// *Comment: mnemonic:
/
01208, 00000, "Instance ID"
// *Comment: mnemonic:
/
01209, 00000, "Current Form Sessions"
// *Comment: mnemonic:
/
01210, 00000, "Current Form Session Instance ID"
// *Comment: mnemonic:
/
01211, 00000, "Aud Sid"
// *Comment: mnemonic:
/
01212, 00000, "Top Form Sessions"
// *Comment: mnemonic:
/
01213, 00000, "Top Form Sessions Aud Sid"
// *Comment: mnemonic:
/
01214, 00000, "Aud Sid"
// *Comment: mnemonic:
/
01215, 00000, "Form Sessions Waiting on Locks"
// *Comment: mnemonic:
/
01216, 00000, "Form Sessions Waiting on Locks"
// *Comment: mnemonic:
/
01217, 00000, "Locked Aud Sid:Locking Aud Sid"
// *Comment: mnemonic:
/
01218, 00000, "Form Sessions per User"
// *Comment: mnemonic:
/
01219, 00000, "Number of Forms Sessions per User"
// *Comment: mnemonic:
/
01220, 00000, "User Name"
// *Comment: mnemonic:
/
01221, 00000, "Forms Sessions Details for User"
// *Comment: mnemonic:
/
01222, 00000, "Forms Sessions Details for User"
// *Comment: mnemonic:
/
01223, 00000, "Aud Sid"
// *Comment: mnemonic:
/
01224, 00000, "Form Sessions per Application"
// *Comment: mnemonic:
/
01225, 00000, "Number of Forms Sessions per Application"
// *Comment: mnemonic:
/
01226, 00000, "Application Name"
// *Comment: mnemonic:
/
01227, 00000, "Forms Sessions Details for Application"
// *Comment: mnemonic:
/
01228, 00000, "Forms Sessions Details for Application"
// *Comment: mnemonic:
/
01229, 00000, "Aud Sid"
// *Comment: mnemonic:
/
01230, 00000, "Form Sessions per Responsibility"
// *Comment: mnemonic:
/
01231, 00000, "Number of Form Sessions per Responsibility"
// *Comment: mnemonic:
/
01232, 00000, "Responsibility"
// *Comment: mnemonic:
/
01233, 00000, "Forms Sessions Details for Responsibility"
// *Comment: mnemonic:
/
01234, 00000, "Forms Sessions Details for Responsibility"
// *Comment: mnemonic:
/
01235, 00000, "Aud Sid"
// *Comment: mnemonic:
/
01236, 00000, "Concurrent Requests"
// *Comment: mnemonic:
/
01237, 00000, "Concurrent Request ID"
// *Comment: mnemonic:
/
01238, 00000, "Request ID"
// *Comment: mnemonic:
/
01239, 00000, "Active Requests by Status"
// *Comment: mnemonic:
/
01240, 00000, "Overview of Active Requests on the System by Status"
// *Comment: mnemonic:
/
01241, 00000, "Oracle Applications Instance"
// *Comment: mnemonic:
/
01242, 00000, "Active Requests by User"
// *Comment: mnemonic:
/
01243, 00000, "Number of Active Requests by User"
// *Comment: mnemonic:
/
01244, 00000, "User Name"
// *Comment: mnemonic:
/
01245, 00000, "Standby Requests for User"
// *Comment: mnemonic:
/
01246, 00000, "Standby Requests for a Specific User"
// *Comment: mnemonic:
/
01247, 00000, "Request ID"
// *Comment: mnemonic:
/
01248, 00000, "Pending Requests for User"
// *Comment: mnemonic:
/
01249, 00000, "Pending Requests for a Specific User"
// *Comment: mnemonic:
/
01250, 00000, "Request ID"
// *Comment: mnemonic:
/
01251, 00000, "Running Requests for User"
// *Comment: mnemonic:
/
01252, 00000, "Running Requests for a Specific User"
// *Comment: mnemonic:
/
01253, 00000, "Request ID"
// *Comment: mnemonic:
/
01254, 00000, "Active Requests by Application"
// *Comment: mnemonic:
/
01255, 00000, "Number of Active Requests by Application"
// *Comment: mnemonic:
/
01256, 00000, "Application Name"
// *Comment: mnemonic:
/
01257, 00000, "Standby Requests for Application"
// *Comment: mnemonic:
/
01258, 00000, "Standby Requests for a Specific Application"
// *Comment: mnemonic:
/
01259, 00000, "Request ID"
// *Comment: mnemonic:
/
01260, 00000, "Pending Requests for Application"
// *Comment: mnemonic:
/
01261, 00000, "Pending Requests for a Specific Application"
// *Comment: mnemonic:
/
01262, 00000, "Request ID"
// *Comment: mnemonic:
/
01263, 00000, "Running Requests for Application"
// *Comment: mnemonic:
/
01264, 00000, "Running Requests for a Specific Application"
// *Comment: mnemonic:
/
01265, 00000, "Request ID"
// *Comment: mnemonic:
/
01266, 00000, "Active Requests by Responsibility"
// *Comment: mnemonic:
/
01267, 00000, "Number of Active Requests by Responsibility"
// *Comment: mnemonic:
/
01268, 00000, "Responsibility Name"
// *Comment: mnemonic:
/
01269, 00000, "Standby Requests for Responsibility"
// *Comment: mnemonic:
/
01270, 00000, "Standby Requests for a Specific Responsibility"
// *Comment: mnemonic:
/
01271, 00000, "Request ID"
// *Comment: mnemonic:
/
01272, 00000, "Pending Requests for Responsibility"
// *Comment: mnemonic:
/
01273, 00000, "Pending Requests for a Specific Responsibility"
// *Comment: mnemonic:
/
01274, 00000, "Request ID"
// *Comment: mnemonic:
/
01275, 00000, "Running Requests for Responsibility"
// *Comment: mnemonic:
/
01276, 00000, "Running Requests for a Specific Responsibility"
// *Comment: mnemonic:
/
01277, 00000, "Request ID"
// *Comment: mnemonic:
/
01278, 00000, "Top Running Requests"
// *Comment: mnemonic:
/
01279, 00000, "Running Requests Sorted by Selection"
// *Comment: mnemonic:
/
01280, 00000, "Request ID"
// *Comment: mnemonic:
/
01281, 00000, "Longest Running Requests"
// *Comment: mnemonic:
/
01282, 00000, "10 Longest Running Requests"
// *Comment: mnemonic:
/
01283, 00000, "Request ID"
// *Comment: mnemonic:
/
01284, 00000, "Requests Waiting on Locks"
// *Comment: mnemonic:
/
01285, 00000, "Locked Session ID and Locking Session ID"
// *Comment: mnemonic:
/
01286, 00000, "Locked Aud Sid:Locking Aud Sid"
// *Comment: mnemonic:
/
01287, 00000, "Longest Pending Requests"
// *Comment: mnemonic:
/
01288, 00000, "10 Longest Pending or Standby Requests"
// *Comment: mnemonic:
/
01289, 00000, "Request ID"
// *Comment: mnemonic:
/
01290, 00000, "Completed Requests by Status"
// *Comment: mnemonic:
/
01291, 00000, "Completed Requests by Status"
// *Comment: mnemonic:
/
01292, 00000, "Oracle Applications Instance"
// *Comment: mnemonic:
/
01293, 00000, "Completed With Warning"
// *Comment: mnemonic:
/
01294, 00000, "Requests Completed With Warning"
// *Comment: mnemonic:
/
01295, 00000, "Request ID"
// *Comment: mnemonic:
/
01296, 00000, "Completed With Error"
// *Comment: mnemonic:
/
01297, 00000, "Requests Completed With Error"
// *Comment: mnemonic:
/
01298, 00000, "Request ID"
// *Comment: mnemonic:
/
01299, 00000, "All Standby Requests"
// *Comment: mnemonic:
/
01300, 00000, "All Standby Requests"
// *Comment: mnemonic:
/
01301, 00000, "Request ID"
// *Comment: mnemonic:
/
01302, 00000, "All Pending Requests"
// *Comment: mnemonic:
/
01303, 00000, "All Pending Requests"
// *Comment: mnemonic:
/
01304, 00000, "Request ID"
// *Comment: mnemonic:
/
01305, 00000, "All Running Requests"
// *Comment: mnemonic:
/
01306, 00000, "All Running Requests"
// *Comment: mnemonic:
/
01307, 00000, "Request ID"
// *Comment: mnemonic:
/
01308, 00000, "Requests Waited on"
// *Comment: mnemonic:
/
01309, 00000, "Requests Waited on"
// *Comment: mnemonic:
/
01310, 00000, "Request ID"
// *Comment: mnemonic:
/
01311, 00000, "Concurrent Managers"
// *Comment: mnemonic:
/
01312, 00000, "Concurrent Managers Data"
// *Comment: mnemonic:
/
01313, 00000, "Concurrent Managers"
// *Comment: mnemonic:
/
01314, 00000, "Pending Requests per Manager"
// *Comment: mnemonic:
/
01315, 00000, "Number of pending requests per manager"
// *Comment: mnemonic:
/
01316, 00000, "Concurrent Managers"
// *Comment: mnemonic:
/
01317, 00000, "Pending Requests Detail"
// *Comment: mnemonic:
/
01318, 00000, "Pending Request Details for Manager"
// *Comment: mnemonic:
/
01319, 00000, "Request ID"
// *Comment: mnemonic:
/
01320, 00000, "Standby Requests per Manager"
// *Comment: mnemonic:
/
01321, 00000, "Number of standby requests per manager"
// *Comment: mnemonic:
/
01322, 00000, "Concurrent Managers"
// *Comment: mnemonic:
/
01323, 00000, "Standby Requests Detail"
// *Comment: mnemonic:
/
01324, 00000, "Standby Request Details for Manager"
// *Comment: mnemonic:
/
01325, 00000, "Request ID"
// *Comment: mnemonic:
/
01326, 00000, "Running Requests per Manager"
// *Comment: mnemonic:
/
01327, 00000, "Number of running requests per manager"
// *Comment: mnemonic:
/
01328, 00000, "Concurrent Managers"
// *Comment: mnemonic:
/
01329, 00000, "Running Requests Detail"
// *Comment: mnemonic:
/
01330, 00000, "Running Requests Details for Manager"
// *Comment: mnemonic:
/
01331, 00000, "Request ID"
// *Comment: mnemonic:
/
01332, 00000, "Processes per Manager"
// *Comment: mnemonic:
/
01333, 00000, "Maximum Number of Allotted Processes per manager"
// *Comment: mnemonic:
/
01334, 00000, "Concurrent Managers"
// *Comment: mnemonic:
/
01335, 00000, "Process Details for Manager"
// *Comment: mnemonic:
/
01336, 00000, "Concurrent processes for a particular manager"
// *Comment: mnemonic:
/
01337, 00000, "Aud Sid"
// *Comment: mnemonic:
/
01338, 00000, "Sessions Blocking CRM/ICM Activity"
// *Comment: mnemonic:
/
01339, 00000, "Sessions Currently Blocking CRM/ICM Activity"
// *Comment: mnemonic:
/
01340, 00000, "Aud Sid"
// *Comment: mnemonic:
/
01341, 00000, "Oracle Database Session"
// *Comment: mnemonic:
/
01342, 00000, "Oracle Database Session"
// *Comment: mnemonic:
/
01343, 00000, "Oracle Database Session"
// *Comment: mnemonic:
/
01344, 00000, "Session Details"
// *Comment: mnemonic:
/
01345, 00000, "Session Details"
// *Comment: mnemonic:
/
01346, 00000, "Aud Sid"
// *Comment: mnemonic:
/
01347, 00000, "Session  Details"
// *Comment: mnemonic:
/
01348, 00000, "Session Details"
// *Comment: mnemonic:
/
01349, 00000, "Request ID"
// *Comment: mnemonic:
/
01350, 00000, "Session Details ( Locked )"
// *Comment: mnemonic:
/
01351, 00000, "Session Details"
// *Comment: mnemonic:
/
01352, 00000, "Aud Sid"
// *Comment: mnemonic:
/
01353, 00000, "Session Details ( Locking )"
// *Comment: mnemonic:
/
01354, 00000, "Session Details"
// *Comment: mnemonic:
/
01355, 00000, "Aud Sid"
// *Comment: mnemonic:
/
01356, 00000, "Session Statistics"
// *Comment: mnemonic:
/
01357, 00000, "Session Statistics"
// *Comment: mnemonic:
/
01358, 00000, "Session ID"
// *Comment: mnemonic:
/
01359, 00000, "Session  Statistics"
// *Comment: mnemonic:
/
01360, 00000, "Session Statistics"
// *Comment: mnemonic:
/
01361, 00000, "Session ID"
// *Comment: mnemonic:
/
01362, 00000, "Session Statistics ( Locked )"
// *Comment: mnemonic:
/
01363, 00000, "Session Statistics"
// *Comment: mnemonic:
/
01364, 00000, "Session ID"
// *Comment: mnemonic:
/
01365, 00000, "Session Statistics ( Locking )"
// *Comment: mnemonic:
/
01366, 00000, "Session Statistics"
// *Comment: mnemonic:
/
01367, 00000, "Session ID"
// *Comment: mnemonic:
/
01368, 00000, "Current SQL for Session"
// *Comment: mnemonic:
/
01369, 00000, "Current SQL for Session"
// *Comment: mnemonic:
/
01370, 00000, "Session ID"
// *Comment: mnemonic:
/
01371, 00000, "Current SQL for  Session"
// *Comment: mnemonic:
/
01372, 00000, "Current SQL for Session"
// *Comment: mnemonic:
/
01373, 00000, "Aud Sid"
// *Comment: mnemonic:
/
01800, 00000, "System Activity Overview Chart Group"
// *Comment: mnemonic:
/
01801, 00000, "View of Logins, Concurrent Requests, and Concurrent Managers"
// *Comment: mnemonic:
/
01802, 00000, "Top Resource Consumers Chart Group"
// *Comment: mnemonic:
/
01803, 00000, "View of Top Form Sessions and Top Running Concurrent Requests"
// *Comment: mnemonic:
/
01804, 00000, "Form Sessions and Concurrent Requests"
// *Comment: mnemonic:
/
01805, 00000, "Overview of Form Sessions and Requests"
// *Comment: mnemonic:
/
01806, 00000, "Form Sessions Summary Group"
// *Comment: mnemonic:
/
01807, 00000, "View of Forms Sessions Activity"
// *Comment: mnemonic:
/
01808, 00000, "Current Form Sessions"
// *Comment: mnemonic:
/
01809, 00000, "Current Form Sessions Chart"
// *Comment: mnemonic:
/
01810, 00000, "Top Form Sessions"
// *Comment: mnemonic:
/
01811, 00000, "Top Form Sessions Chart"
// *Comment: mnemonic:
/
01812, 00000, "Form Sessions Waiting on Locks"
// *Comment: mnemonic:
/
01813, 00000, "Form Sessions Waiting on Locks Chart"
// *Comment: mnemonic:
/
01814, 00000, "Form Sessions per User"
// *Comment: mnemonic:
/
01815, 00000, "Form Sessions per User Chart"
// *Comment: mnemonic:
/
01816, 00000, "Forms Sessions Details for User"
// *Comment: mnemonic:
/
01817, 00000, "Forms Sessions Details for User Chart"
// *Comment: mnemonic:
/
01818, 00000, "Form Sessions per Application"
// *Comment: mnemonic:
/
01819, 00000, "Form Sessions per Application Chart"
// *Comment: mnemonic:
/
01820, 00000, "Forms Sessions Details for Application"
// *Comment: mnemonic:
/
01821, 00000, "Forms Sessions Details for Application Chart"
// *Comment: mnemonic:
/
01822, 00000, "Form Sessions per Responsibility"
// *Comment: mnemonic:
/
01823, 00000, "Form Sessions per Responsibility Chart"
// *Comment: mnemonic:
/
01824, 00000, "Forms Sessions Details for Responsibility"
// *Comment: mnemonic:
/
01825, 00000, "Forms Sessions Details for Responsibility Chart"
// *Comment: mnemonic:
/
01826, 00000, "Active Requests Chart Group"
// *Comment: mnemonic:
/
01827, 00000, "View of Active Requests by Status, User, Responsibility, and Application"
// *Comment: mnemonic:
/
01828, 00000, "Active Requests Detail for User Group"
// *Comment: mnemonic:
/
01829, 00000, "View of Standby, Pending, and Running Requests for a User"
// *Comment: mnemonic:
/
01830, 00000, "Active Requests Detail for Application Group"
// *Comment: mnemonic:
/
01831, 00000, "View of Standby, Pending, and Running Requests for an Application"
// *Comment: mnemonic:
/
01832, 00000, "Active Requests Detail for Responsibility Group"
// *Comment: mnemonic:
/
01833, 00000, "View of Standby, Pending, and Running Requests for a Responsibility"
// *Comment: mnemonic:
/
01834, 00000, "Active Requests by Status"
// *Comment: mnemonic:
/
01835, 00000, "Active Requests by Status Chart"
// *Comment: mnemonic:
/
01836, 00000, "Active Requests per User"
// *Comment: mnemonic:
/
01837, 00000, "Active Requests per User Chart"
// *Comment: mnemonic:
/
01838, 00000, "Standby Requests for User"
// *Comment: mnemonic:
/
01839, 00000, "Standby Requests for a Specific User Chart"
// *Comment: mnemonic:
/
01840, 00000, "Pending Requests for User"
// *Comment: mnemonic:
/
01841, 00000, "Pending Requests for a Specific User Chart"
// *Comment: mnemonic:
/
01842, 00000, "Running Requests for User"
// *Comment: mnemonic:
/
01843, 00000, "Running Requests for a Specific User Chart"
// *Comment: mnemonic:
/
01844, 00000, "Active Requests per Application"
// *Comment: mnemonic:
/
01845, 00000, "Active Requests per Application Chart"
// *Comment: mnemonic:
/
01846, 00000, "Standby Requests for Application"
// *Comment: mnemonic:
/
01847, 00000, "Standby Requests for a Specific Application Chart"
// *Comment: mnemonic:
/
01848, 00000, "Pending Requests for Application"
// *Comment: mnemonic:
/
01849, 00000, "Pending Requests for a Specific Application Chart"
// *Comment: mnemonic:
/
01850, 00000, "Running Requests for Application"
// *Comment: mnemonic:
/
01851, 00000, "Running Requests for a Specific Application Chart"
// *Comment: mnemonic:
/
01852, 00000, "Active Requests per Responsibility"
// *Comment: mnemonic:
/
01853, 00000, "Active Requests per Responsibility Chart"
// *Comment: mnemonic:
/
01854, 00000, "Standby Requests for Responsibility"
// *Comment: mnemonic:
/
01855, 00000, "Standby Requests for a Specific Responsibility Chart"
// *Comment: mnemonic:
/
01856, 00000, "Pending Requests for Responsibility"
// *Comment: mnemonic:
/
01857, 00000, "Pending Requests for a Specific Responsibility Chart"
// *Comment: mnemonic:
/
01858, 00000, "Running Requests for Responsibility"
// *Comment: mnemonic:
/
01859, 00000, "Running Requests for a Specific Responsibility Chart"
// *Comment: mnemonic:
/
01860, 00000, "Top Running Requests"
// *Comment: mnemonic:
/
01861, 00000, "Top Running Requests Chart"
// *Comment: mnemonic:
/
01862, 00000, "Longest Running Requests"
// *Comment: mnemonic:
/
01863, 00000, "Longest Running Requests Chart"
// *Comment: mnemonic:
/
01864, 00000, "Requests Waiting on Locks"
// *Comment: mnemonic:
/
01865, 00000, "Requests Waiting on Locks Chart"
// *Comment: mnemonic:
/
01866, 00000, "Longest Pending Requests"
// *Comment: mnemonic:
/
01867, 00000, "Longest Pending Requests Chart"
// *Comment: mnemonic:
/
01868, 00000, "Completed Requests by Status"
// *Comment: mnemonic:
/
01869, 00000, "Completed Requests by Status Chart"
// *Comment: mnemonic:
/
01870, 00000, "Completed With Warning"
// *Comment: mnemonic:
/
01871, 00000, "Completed With Warning Chart"
// *Comment: mnemonic:
/
01872, 00000, "Completed With Error"
// *Comment: mnemonic:
/
01873, 00000, "Completed With Error Chart"
// *Comment: mnemonic:
/
01874, 00000, "All Standby Requests"
// *Comment: mnemonic:
/
01875, 00000, "All Standby Requests Chart"
// *Comment: mnemonic:
/
01876, 00000, "All Pending Requests"
// *Comment: mnemonic:
/
01877, 00000, "All Pending Requests Chart"
// *Comment: mnemonic:
/
01878, 00000, "All Running Requests"
// *Comment: mnemonic:
/
01879, 00000, "All Running Requests Chart"
// *Comment: mnemonic:
/
01880, 00000, "Requests Waited on"
// *Comment: mnemonic:
/
01881, 00000, "Requests Waited on Chart"
// *Comment: mnemonic:
/
01882, 00000, "Concurrent Managers Status Group"
// *Comment: mnemonic:
/
01883, 00000, "View of Concurrent Managers Activity"
// *Comment: mnemonic:
/
01884, 00000, "Pending Requests per Manager"
// *Comment: mnemonic:
/
01885, 00000, "Pending Requests per Manager Chart"
// *Comment: mnemonic:
/
01886, 00000, "Pending Requests Details for Manager"
// *Comment: mnemonic:
/
01887, 00000, "Pending Request Details for Manager Chart"
// *Comment: mnemonic:
/
01888, 00000, "Standby Requests per Manager"
// *Comment: mnemonic:
/
01889, 00000, "Standby Requests per Manager Chart"
// *Comment: mnemonic:
/
01890, 00000, "Standby Requests Details for Manager"
// *Comment: mnemonic:
/
01891, 00000, "Standby Request Details for Manager Chart"
// *Comment: mnemonic:
/
01892, 00000, "Running Requests per Manager"
// *Comment: mnemonic:
/
01893, 00000, "Running Requests per Manager Chart"
// *Comment: mnemonic:
/
01894, 00000, "Running Requests Details for Manager"
// *Comment: mnemonic:
/
01895, 00000, "Running Requests Details for Manager Chart"
// *Comment: mnemonic:
/
01896, 00000, "Processes per Manager"
// *Comment: mnemonic:
/
01897, 00000, "Processes per Manager Chart"
// *Comment: mnemonic:
/
01898, 00000, "Process Details for Manager"
// *Comment: mnemonic:
/
01899, 00000, "Process Details for Manager Chart"
// *Comment: mnemonic:
/
01900, 00000, "Sessions Blocking CRM/ICM Activity"
// *Comment: mnemonic:
/
01901, 00000, "Sessions Blocking CRM/ICM Activity Chart"
// *Comment: mnemonic:
/
01902, 00000, "Session Details"
// *Comment: mnemonic:
/
01903, 00000, "Session Details Chart"
// *Comment: mnemonic:
/
01904, 00000, "Session  Details"
// *Comment: mnemonic:
/
01905, 00000, "Session Details Chart"
// *Comment: mnemonic:
/
01906, 00000, "Session Details ( Locked )"
// *Comment: mnemonic:
/
01907, 00000, "Session Details ( Locked ) Chart"
// *Comment: mnemonic:
/
01908, 00000, "Session Details ( Locking )"
// *Comment: mnemonic:
/
01909, 00000, "Session Details ( Locking ) Chart"
// *Comment: mnemonic:
/
01910, 00000, "Session Statistics"
// *Comment: mnemonic:
/
01911, 00000, "Session Statistics Chart"
// *Comment: mnemonic:
/
01912, 00000, "Session  Statistics"
// *Comment: mnemonic:
/
01913, 00000, "Session Statistics Chart"
// *Comment: mnemonic:
/
01914, 00000, "Session Statistics ( Locked )"
// *Comment: mnemonic:
/
01915, 00000, "Session Statistics Chart"
// *Comment: mnemonic:
/
01916, 00000, "Session Statistics ( Locking )"
// *Comment: mnemonic:
/
01917, 00000, "Session Statistics Chart"
// *Comment: mnemonic:
/
01918, 00000, "Current SQL for Session"
// *Comment: mnemonic:
/
01919, 00000, "Current SQL for Session Chart"
// *Comment: mnemonic:
/
01920, 00000, "Current SQL for  Session"
// *Comment: mnemonic:
/
01921, 00000, "Current SQL for Session Chart"
// *Comment: mnemonic:
/
02200, 00000, "Cancel Request"
// *Comment: mnemonic:
/
02201, 00000, "Cancel Request"
// *Comment: mnemonic:
/
02202, 00000, "Failed to Cancel Request - Could not lock request row"
// *Comment: mnemonic:
/
02203, 00000, "Failed to Cancel Request - Request has already Completed"
// *Comment: mnemonic:
/
02204, 00000, "Failed to Cancel Request - Manager process exited abnormally. The Internal Concurrent Manager will update this request"
// *Comment: mnemonic:
/
02205, 00000, "Request Canceled"
// *Comment: mnemonic:
/
02206, 00000, "Request Marked for Cancellation"
// *Comment: mnemonic:
/
02207, 00000, "Toggle Request Hold"
// *Comment: mnemonic:
/
02208, 00000, "Toggle Request Hold"
// *Comment: mnemonic:
/
02209, 00000, "Failed to Toggle Request Hold - Could not lock request row"
// *Comment: mnemonic:
/
02210, 00000, "Failed to Hold Request - Request has already Started"
// *Comment: mnemonic:
/
02211, 00000, "Request Placed on Hold"
// *Comment: mnemonic:
/
02212, 00000, "Request Hold Removed"
// *Comment: mnemonic:
/
02214, 00000, "Terminate Request"
// *Comment: mnemonic:
/
02215, 00000, "Terminate Request"
// *Comment: mnemonic:
/
02216, 00000, "Failed to Terminate Request - Could not lock request row"
// *Comment: mnemonic:
/
02217, 00000, "Failed to Terminate Request - Request has already Completed"
// *Comment: mnemonic:
/
02218, 00000, "Failed to Terminate Request - Manager process exited abnormally. The Internal Concurrent Manager will update this request"
// *Comment: mnemonic:
/
02219, 00000, "Request Terminated"
// *Comment: mnemonic:
/
02220, 00000, "Request Marked for Termination"
// *Comment: mnemonic:
/
02221, 00000, "Kill Session"
// *Comment: mnemonic:
/
02222, 00000, "Kill Session"
// *Comment: mnemonic:
/
02223, 00000, "Session Not Found - The session may have already terminated"
// *Comment: mnemonic:
/
02224, 00000, "Session Marked for Termination"
// *Comment: mnemonic:
/
02228, 00000, "Kill  Session"
// *Comment: mnemonic:
/
02229, 00000, "Kill Session"
// *Comment: mnemonic:
/
02230, 00000, "Session Not Found - The session may have already terminated"
// *Comment: mnemonic:
/
02231, 00000, "Session Marked for Termination"
// *Comment: mnemonic:
/
03000, 00000, "Standby Requests"
// *Comment: mnemonic:
/
03001, 00000, "Number of Standby Concurrent Requests"
// *Comment: mnemonic:
/
03002, 00000, "Pending Requests"
// *Comment: mnemonic:
/
03003, 00000, "Number of Pending Concurrent Requests"
// *Comment: mnemonic:
/
03004, 00000, "Running Requests"
// *Comment: mnemonic:
/
03005, 00000, "Number of Running Concurrent Requests"
// *Comment: mnemonic:
/
03006, 00000, "Form Sessions"
// *Comment: mnemonic:
/
03007, 00000, "Number of Current Forms Sessions"
// *Comment: mnemonic:
/
03200, 00000, "User Name"
// *Comment: mnemonic:
/
03201, 00000, "Application User Name"
// *Comment: mnemonic:
/
03202, 00000, "Responsibility"
// *Comment: mnemonic:
/
03203, 00000, "User Responsibility"
// *Comment: mnemonic:
/
03204, 00000, "Form"
// *Comment: mnemonic:
/
03205, 00000, "Form Name"
// *Comment: mnemonic:
/
03206, 00000, "OS User"
// *Comment: mnemonic:
/
03207, 00000, "Operating System User Name"
// *Comment: mnemonic:
/
03208, 00000, "Time"
// *Comment: mnemonic:
/
03209, 00000, "Time"
// *Comment: mnemonic:
/
03210, 00000, "Session ID"
// *Comment: mnemonic:
/
03211, 00000, "Session ID"
// *Comment: mnemonic:
/
03212, 00000, "Serial Number"
// *Comment: mnemonic:
/
03213, 00000, "Session Serial Number"
// *Comment: mnemonic:
/
03214, 00000, "Terminal Name/Client IP"
// *Comment: mnemonic:
/
03215, 00000, "Terminal Name/Client Internet Protocol (IP)"
// *Comment: mnemonic:
/
03300, 00000, "User Name"
// *Comment: mnemonic:
/
03301, 00000, "Application User Name"
// *Comment: mnemonic:
/
03302, 00000, "Responsibility"
// *Comment: mnemonic:
/
03303, 00000, "User Responsibility"
// *Comment: mnemonic:
/
03304, 00000, "Form"
// *Comment: mnemonic:
/
03305, 00000, "Form Name"
// *Comment: mnemonic:
/
03306, 00000, "OS User"
// *Comment: mnemonic:
/
03307, 00000, "Operating System User Name"
// *Comment: mnemonic:
/
03308, 00000, "Time"
// *Comment: mnemonic:
/
03309, 00000, "Time"
// *Comment: mnemonic:
/
03310, 00000, "Terminal Name/Client IP"
// *Comment: mnemonic:
/
03311, 00000, "Terminal Name/Client Internet Protocol (IP)"
// *Comment: mnemonic:
/
03312, 00000, "Session ID"
// *Comment: mnemonic:
/
03313, 00000, "Session Session ID"
// *Comment: mnemonic:
/
03314, 00000, "Serial Number"
// *Comment: mnemonic:
/
03315, 00000, "Session Serial Number"
// *Comment: mnemonic:
/
03316, 00000, "Process ID"
// *Comment: mnemonic:
/
03317, 00000, "Process ID"
// *Comment: mnemonic:
/
03318, 00000, "State"
// *Comment: mnemonic:
/
03319, 00000, "State"
// *Comment: mnemonic:
/
03320, 00000, "Address of Lock Waiting for"
// *Comment: mnemonic:
/
03321, 00000, "Address of Lock Waiting for"
// *Comment: mnemonic:
/
03322, 00000, "Command in Progress"
// *Comment: mnemonic:
/
03323, 00000, "Command in Progress"
// *Comment: mnemonic:
/
03324, 00000, "Sort Criterion"
// *Comment: mnemonic:
/
03325, 00000, "Sort Criterion"
// *Comment: mnemonic:
/
03326, 00000, "Session UGA Memory"
// *Comment: mnemonic:
/
03327, 00000, "Session User Global Area Memory"
// *Comment: mnemonic:
/
03328, 00000, "Session PGA Memory"
// *Comment: mnemonic:
/
03329, 00000, "Session Program Global Area Memory"
// *Comment: mnemonic:
/
03330, 00000, "CPU Used by This Session"
// *Comment: mnemonic:
/
03331, 00000, "CPU Used by This Session"
// *Comment: mnemonic:
/
03332, 00000, "Physical Reads"
// *Comment: mnemonic:
/
03333, 00000, "Physical Reads"
// *Comment: mnemonic:
/
03334, 00000, "Physical Writes"
// *Comment: mnemonic:
/
03335, 00000, "Physical Writes"
// *Comment: mnemonic:
/
03336, 00000, "Open Cursors (Current)"
// *Comment: mnemonic:
/
03337, 00000, "Open Cursors (Current)"
// *Comment: mnemonic:
/
03338, 00000, "User Commits"
// *Comment: mnemonic:
/
03339, 00000, "User Commits"
// *Comment: mnemonic:
/
03340, 00000, "User Rollbacks"
// *Comment: mnemonic:
/
03341, 00000, "User Rollbacks"
// *Comment: mnemonic:
/
03342, 00000, "Session Logical Reads"
// *Comment: mnemonic:
/
03343, 00000, "Session Logical Reads"
// *Comment: mnemonic:
/
03400, 00000, "User Name"
// *Comment: mnemonic:
/
03401, 00000, "Application User Name"
// *Comment: mnemonic:
/
03402, 00000, "Responsibility"
// *Comment: mnemonic:
/
03403, 00000, "User Responsibility"
// *Comment: mnemonic:
/
03404, 00000, "Form"
// *Comment: mnemonic:
/
03405, 00000, "Form Name"
// *Comment: mnemonic:
/
03406, 00000, "Terminal Name/Client IP"
// *Comment: mnemonic:
/
03407, 00000, "Terminal Name/Client Internet Protocol (IP)"
// *Comment: mnemonic:
/
03408, 00000, "Lock Type"
// *Comment: mnemonic:
/
03409, 00000, "Lock Type"
// *Comment: mnemonic:
/
03410, 00000, "Resource ID 1"
// *Comment: mnemonic:
/
03411, 00000, "Resource ID 1"
// *Comment: mnemonic:
/
03412, 00000, "Resource ID 2"
// *Comment: mnemonic:
/
03413, 00000, "Resource ID 2"
// *Comment: mnemonic:
/
03414, 00000, "Mode Requested"
// *Comment: mnemonic:
/
03415, 00000, "Mode Requested"
// *Comment: mnemonic:
/
03500, 00000, "Form Sessions"
// *Comment: mnemonic:
/
03501, 00000, "Number of Forms Sessions per User"
// *Comment: mnemonic:
/
03600, 00000, "User Name"
// *Comment: mnemonic:
/
03601, 00000, "Application User Name"
// *Comment: mnemonic:
/
03602, 00000, "Responsibility"
// *Comment: mnemonic:
/
03603, 00000, "User Responsibility"
// *Comment: mnemonic:
/
03604, 00000, "Form"
// *Comment: mnemonic:
/
03605, 00000, "Form Name"
// *Comment: mnemonic:
/
03606, 00000, "OS User"
// *Comment: mnemonic:
/
03607, 00000, "Operating System User Name"
// *Comment: mnemonic:
/
03608, 00000, "Time"
// *Comment: mnemonic:
/
03609, 00000, "Time"
// *Comment: mnemonic:
/
03610, 00000, "Session ID"
// *Comment: mnemonic:
/
03611, 00000, "Session ID"
// *Comment: mnemonic:
/
03612, 00000, "Serial Number"
// *Comment: mnemonic:
/
03613, 00000, "Session Serial Number"
// *Comment: mnemonic:
/
03614, 00000, "Terminal Name/Client IP"
// *Comment: mnemonic:
/
03615, 00000, "Terminal Name/Client Internet Protocol (IP)"
// *Comment: mnemonic:
/
03700, 00000, "Form Sessions"
// *Comment: mnemonic:
/
03701, 00000, "Number of Forms Sessions per Application"
// *Comment: mnemonic:
/
03800, 00000, "User Name"
// *Comment: mnemonic:
/
03801, 00000, "Application User Name"
// *Comment: mnemonic:
/
03802, 00000, "Application Name"
// *Comment: mnemonic:
/
03803, 00000, "User Application"
// *Comment: mnemonic:
/
03804, 00000, "Form"
// *Comment: mnemonic:
/
03805, 00000, "Form Name"
// *Comment: mnemonic:
/
03806, 00000, "OS User"
// *Comment: mnemonic:
/
03807, 00000, "Operating System User Name"
// *Comment: mnemonic:
/
03808, 00000, "Time"
// *Comment: mnemonic:
/
03809, 00000, "Time"
// *Comment: mnemonic:
/
03810, 00000, "Session ID"
// *Comment: mnemonic:
/
03811, 00000, "Session ID"
// *Comment: mnemonic:
/
03812, 00000, "Serial Number"
// *Comment: mnemonic:
/
03813, 00000, "Session Serial Number"
// *Comment: mnemonic:
/
03814, 00000, "Terminal Name/Client IP"
// *Comment: mnemonic:
/
03815, 00000, "Terminal Name/Client Internet Protocol (IP)"
// *Comment: mnemonic:
/
03900, 00000, "Form Sessions"
// *Comment: mnemonic:
/
03901, 00000, "Number of Form Sessions per Responsibility"
// *Comment: mnemonic:
/
04000, 00000, "User Name"
// *Comment: mnemonic:
/
04001, 00000, "Application User Name"
// *Comment: mnemonic:
/
04002, 00000, "Responsibility"
// *Comment: mnemonic:
/
04003, 00000, "User Responsibility"
// *Comment: mnemonic:
/
04004, 00000, "Form"
// *Comment: mnemonic:
/
04005, 00000, "Form Name"
// *Comment: mnemonic:
/
04006, 00000, "OS User"
// *Comment: mnemonic:
/
04007, 00000, "Operating System User Name"
// *Comment: mnemonic:
/
04008, 00000, "Time"
// *Comment: mnemonic:
/
04009, 00000, "Time"
// *Comment: mnemonic:
/
04010, 00000, "Session ID"
// *Comment: mnemonic:
/
04011, 00000, "Session ID"
// *Comment: mnemonic:
/
04012, 00000, "Serial Number"
// *Comment: mnemonic:
/
04013, 00000, "Session Serial Number"
// *Comment: mnemonic:
/
04014, 00000, "Terminal Name/Client IP"
// *Comment: mnemonic:
/
04015, 00000, "Terminal Name/Client Internet Protocol (IP)"
// *Comment: mnemonic:
/
04200, 00000, "Standby Requests"
// *Comment: mnemonic:
/
04201, 00000, "Number of Standby Requests"
// *Comment: mnemonic:
/
04202, 00000, "Pending Requests"
// *Comment: mnemonic:
/
04203, 00000, "Number of Pending Requests"
// *Comment: mnemonic:
/
04204, 00000, "Running Requests"
// *Comment: mnemonic:
/
04205, 00000, "Number of Running Requests"
// *Comment: mnemonic:
/
04300, 00000, "Active Requests"
// *Comment: mnemonic:
/
04301, 00000, "Number of Active Requests"
// *Comment: mnemonic:
/
04400, 00000, "Program Name"
// *Comment: mnemonic:
/
04401, 00000, "Program Name"
// *Comment: mnemonic:
/
04402, 00000, "Phase"
// *Comment: mnemonic:
/
04403, 00000, "Phase"
// *Comment: mnemonic:
/
04404, 00000, "Status"
// *Comment: mnemonic:
/
04405, 00000, "Status"
// *Comment: mnemonic:
/
04406, 00000, "User Name"
// *Comment: mnemonic:
/
04407, 00000, "User Name"
// *Comment: mnemonic:
/
04408, 00000, "Requested Start"
// *Comment: mnemonic:
/
04409, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
04410, 00000, "Submission Time"
// *Comment: mnemonic:
/
04411, 00000, "Submission Time"
// *Comment: mnemonic:
/
04412, 00000, "Priority"
// *Comment: mnemonic:
/
04413, 00000, "Request Priority"
// *Comment: mnemonic:
/
04414, 00000, "Arguments"
// *Comment: mnemonic:
/
04415, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
04500, 00000, "Program Name"
// *Comment: mnemonic:
/
04501, 00000, "Program Name"
// *Comment: mnemonic:
/
04502, 00000, "Phase"
// *Comment: mnemonic:
/
04503, 00000, "Phase"
// *Comment: mnemonic:
/
04504, 00000, "Status"
// *Comment: mnemonic:
/
04505, 00000, "Status"
// *Comment: mnemonic:
/
04506, 00000, "User Name"
// *Comment: mnemonic:
/
04507, 00000, "User Name"
// *Comment: mnemonic:
/
04508, 00000, "Requested Start"
// *Comment: mnemonic:
/
04509, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
04510, 00000, "Submission Time"
// *Comment: mnemonic:
/
04511, 00000, "Submission Time"
// *Comment: mnemonic:
/
04512, 00000, "Priority"
// *Comment: mnemonic:
/
04513, 00000, "Request Priority"
// *Comment: mnemonic:
/
04514, 00000, "Arguments"
// *Comment: mnemonic:
/
04515, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
04600, 00000, "Program Name"
// *Comment: mnemonic:
/
04601, 00000, "Program Name"
// *Comment: mnemonic:
/
04602, 00000, "Phase"
// *Comment: mnemonic:
/
04603, 00000, "Phase"
// *Comment: mnemonic:
/
04604, 00000, "Status"
// *Comment: mnemonic:
/
04605, 00000, "Status"
// *Comment: mnemonic:
/
04606, 00000, "User Name"
// *Comment: mnemonic:
/
04607, 00000, "User Name"
// *Comment: mnemonic:
/
04608, 00000, "Requested Start"
// *Comment: mnemonic:
/
04609, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
04610, 00000, "Submission Time"
// *Comment: mnemonic:
/
04611, 00000, "Submission Time"
// *Comment: mnemonic:
/
04612, 00000, "Priority"
// *Comment: mnemonic:
/
04613, 00000, "Request Priority"
// *Comment: mnemonic:
/
04614, 00000, "Arguments"
// *Comment: mnemonic:
/
04615, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
04700, 00000, "Active Requests"
// *Comment: mnemonic:
/
04701, 00000, "Number of Active Requests"
// *Comment: mnemonic:
/
04800, 00000, "Program Name"
// *Comment: mnemonic:
/
04801, 00000, "Program Name"
// *Comment: mnemonic:
/
04802, 00000, "Phase"
// *Comment: mnemonic:
/
04803, 00000, "Phase"
// *Comment: mnemonic:
/
04804, 00000, "Status"
// *Comment: mnemonic:
/
04805, 00000, "Status"
// *Comment: mnemonic:
/
04806, 00000, "User Name"
// *Comment: mnemonic:
/
04807, 00000, "User Name"
// *Comment: mnemonic:
/
04808, 00000, "Application Name"
// *Comment: mnemonic:
/
04809, 00000, "Application Name"
// *Comment: mnemonic:
/
04810, 00000, "Requested Start"
// *Comment: mnemonic:
/
04811, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
04812, 00000, "Submission Time"
// *Comment: mnemonic:
/
04813, 00000, "Submission Time"
// *Comment: mnemonic:
/
04814, 00000, "Priority"
// *Comment: mnemonic:
/
04815, 00000, "Request Priority"
// *Comment: mnemonic:
/
04816, 00000, "Arguments"
// *Comment: mnemonic:
/
04817, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
04900, 00000, "Program Name"
// *Comment: mnemonic:
/
04901, 00000, "Program Name"
// *Comment: mnemonic:
/
04902, 00000, "Phase"
// *Comment: mnemonic:
/
04903, 00000, "Phase"
// *Comment: mnemonic:
/
04904, 00000, "Status"
// *Comment: mnemonic:
/
04905, 00000, "Status"
// *Comment: mnemonic:
/
04906, 00000, "User Name"
// *Comment: mnemonic:
/
04907, 00000, "User Name"
// *Comment: mnemonic:
/
04908, 00000, "Application Name"
// *Comment: mnemonic:
/
04909, 00000, "Application Name"
// *Comment: mnemonic:
/
04910, 00000, "Requested Start"
// *Comment: mnemonic:
/
04911, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
04912, 00000, "Submission Time"
// *Comment: mnemonic:
/
04913, 00000, "Submission Time"
// *Comment: mnemonic:
/
04914, 00000, "Priority"
// *Comment: mnemonic:
/
04915, 00000, "Request Priority"
// *Comment: mnemonic:
/
04916, 00000, "Arguments"
// *Comment: mnemonic:
/
04917, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
05000, 00000, "Program Name"
// *Comment: mnemonic:
/
05001, 00000, "Program Name"
// *Comment: mnemonic:
/
05002, 00000, "Phase"
// *Comment: mnemonic:
/
05003, 00000, "Phase"
// *Comment: mnemonic:
/
05004, 00000, "Status"
// *Comment: mnemonic:
/
05005, 00000, "Status"
// *Comment: mnemonic:
/
05006, 00000, "User Name"
// *Comment: mnemonic:
/
05007, 00000, "User Name"
// *Comment: mnemonic:
/
05008, 00000, "Application Name"
// *Comment: mnemonic:
/
05009, 00000, "Application Name"
// *Comment: mnemonic:
/
05010, 00000, "Requested Start"
// *Comment: mnemonic:
/
05011, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
05012, 00000, "Submission Time"
// *Comment: mnemonic:
/
05013, 00000, "Submission Time"
// *Comment: mnemonic:
/
05014, 00000, "Priority"
// *Comment: mnemonic:
/
05015, 00000, "Request Priority"
// *Comment: mnemonic:
/
05016, 00000, "Arguments"
// *Comment: mnemonic:
/
05017, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
05100, 00000, "Active Requests"
// *Comment: mnemonic:
/
05101, 00000, "Number of Active Requests"
// *Comment: mnemonic:
/
05200, 00000, "Program Name"
// *Comment: mnemonic:
/
05201, 00000, "Program Name"
// *Comment: mnemonic:
/
05202, 00000, "Phase"
// *Comment: mnemonic:
/
05203, 00000, "Phase"
// *Comment: mnemonic:
/
05204, 00000, "Status"
// *Comment: mnemonic:
/
05205, 00000, "Status"
// *Comment: mnemonic:
/
05206, 00000, "User Name"
// *Comment: mnemonic:
/
05207, 00000, "User Name"
// *Comment: mnemonic:
/
05208, 00000, "Responsibility Name"
// *Comment: mnemonic:
/
05209, 00000, "Responsibility Name"
// *Comment: mnemonic:
/
05210, 00000, "Requested Start"
// *Comment: mnemonic:
/
05211, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
05212, 00000, "Submission Time"
// *Comment: mnemonic:
/
05213, 00000, "Submission Time"
// *Comment: mnemonic:
/
05214, 00000, "Priority"
// *Comment: mnemonic:
/
05215, 00000, "Request Priority"
// *Comment: mnemonic:
/
05216, 00000, "Arguments"
// *Comment: mnemonic:
/
05217, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
05300, 00000, "Program Name"
// *Comment: mnemonic:
/
05301, 00000, "Program Name"
// *Comment: mnemonic:
/
05302, 00000, "Phase"
// *Comment: mnemonic:
/
05303, 00000, "Phase"
// *Comment: mnemonic:
/
05304, 00000, "Status"
// *Comment: mnemonic:
/
05305, 00000, "Status"
// *Comment: mnemonic:
/
05306, 00000, "User Name"
// *Comment: mnemonic:
/
05307, 00000, "User Name"
// *Comment: mnemonic:
/
05308, 00000, "Responsibility Name"
// *Comment: mnemonic:
/
05309, 00000, "Responsibility Name"
// *Comment: mnemonic:
/
05310, 00000, "Requested Start"
// *Comment: mnemonic:
/
05311, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
05312, 00000, "Submission Time"
// *Comment: mnemonic:
/
05313, 00000, "Submission Time"
// *Comment: mnemonic:
/
05314, 00000, "Priority"
// *Comment: mnemonic:
/
05315, 00000, "Request Priority"
// *Comment: mnemonic:
/
05316, 00000, "Arguments"
// *Comment: mnemonic:
/
05317, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
05400, 00000, "Program Name"
// *Comment: mnemonic:
/
05401, 00000, "Program Name"
// *Comment: mnemonic:
/
05402, 00000, "Phase"
// *Comment: mnemonic:
/
05403, 00000, "Phase"
// *Comment: mnemonic:
/
05404, 00000, "Status"
// *Comment: mnemonic:
/
05405, 00000, "Status"
// *Comment: mnemonic:
/
05406, 00000, "User Name"
// *Comment: mnemonic:
/
05407, 00000, "User Name"
// *Comment: mnemonic:
/
05408, 00000, "Responsibility Name"
// *Comment: mnemonic:
/
05409, 00000, "Responsibility Name"
// *Comment: mnemonic:
/
05410, 00000, "Requested Start"
// *Comment: mnemonic:
/
05411, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
05412, 00000, "Submission Time"
// *Comment: mnemonic:
/
05413, 00000, "Submission Time"
// *Comment: mnemonic:
/
05414, 00000, "Priority"
// *Comment: mnemonic:
/
05415, 00000, "Request Priority"
// *Comment: mnemonic:
/
05416, 00000, "Arguments"
// *Comment: mnemonic:
/
05417, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
05500, 00000, "Program Name"
// *Comment: mnemonic:
/
05501, 00000, "Program Name"
// *Comment: mnemonic:
/
05502, 00000, "Requested By"
// *Comment: mnemonic:
/
05503, 00000, "Requested By"
// *Comment: mnemonic:
/
05504, 00000, "Phase"
// *Comment: mnemonic:
/
05505, 00000, "Phase"
// *Comment: mnemonic:
/
05506, 00000, "Status"
// *Comment: mnemonic:
/
05507, 00000, "Status"
// *Comment: mnemonic:
/
05508, 00000, "Arguments"
// *Comment: mnemonic:
/
05509, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
05510, 00000, "Start Date"
// *Comment: mnemonic:
/
05511, 00000, "Start Date"
// *Comment: mnemonic:
/
05512, 00000, "Session ID"
// *Comment: mnemonic:
/
05513, 00000, "Session ID"
// *Comment: mnemonic:
/
05514, 00000, "Serial Number"
// *Comment: mnemonic:
/
05515, 00000, "Session Serial Number"
// *Comment: mnemonic:
/
05516, 00000, "Process ID"
// *Comment: mnemonic:
/
05517, 00000, "Process ID"
// *Comment: mnemonic:
/
05518, 00000, "State"
// *Comment: mnemonic:
/
05519, 00000, "State"
// *Comment: mnemonic:
/
05520, 00000, "Address of Lock Waiting for"
// *Comment: mnemonic:
/
05521, 00000, "Address of Lock Waiting for"
// *Comment: mnemonic:
/
05522, 00000, "Command in Progress"
// *Comment: mnemonic:
/
05523, 00000, "Command in Progress"
// *Comment: mnemonic:
/
05524, 00000, "Sort Criterion"
// *Comment: mnemonic:
/
05525, 00000, "Sort Criterion"
// *Comment: mnemonic:
/
05526, 00000, "Session UGA Memory"
// *Comment: mnemonic:
/
05527, 00000, "Session User Global Area Memory"
// *Comment: mnemonic:
/
05528, 00000, "Session PGA Memory"
// *Comment: mnemonic:
/
05529, 00000, "Session Program Global Area Memory"
// *Comment: mnemonic:
/
05530, 00000, "CPU Used by This Session"
// *Comment: mnemonic:
/
05531, 00000, "CPU Used by This Session"
// *Comment: mnemonic:
/
05532, 00000, "Physical Reads"
// *Comment: mnemonic:
/
05533, 00000, "Physical Reads"
// *Comment: mnemonic:
/
05534, 00000, "Physical Writes"
// *Comment: mnemonic:
/
05535, 00000, "Physical Writes"
// *Comment: mnemonic:
/
05536, 00000, "Open Cursors (Current)"
// *Comment: mnemonic:
/
05537, 00000, "Open Cursors (Current)"
// *Comment: mnemonic:
/
05538, 00000, "User Commits"
// *Comment: mnemonic:
/
05539, 00000, "User Commits"
// *Comment: mnemonic:
/
05540, 00000, "User Rollbacks"
// *Comment: mnemonic:
/
05541, 00000, "User Rollbacks"
// *Comment: mnemonic:
/
05542, 00000, "Session Logical Reads"
// *Comment: mnemonic:
/
05543, 00000, "Session Logical Reads"
// *Comment: mnemonic:
/
05600, 00000, "Program Name"
// *Comment: mnemonic:
/
05601, 00000, "Program Name"
// *Comment: mnemonic:
/
05602, 00000, "Requested By"
// *Comment: mnemonic:
/
05603, 00000, "Requested By"
// *Comment: mnemonic:
/
05604, 00000, "Phase"
// *Comment: mnemonic:
/
05605, 00000, "Phase"
// *Comment: mnemonic:
/
05606, 00000, "Status"
// *Comment: mnemonic:
/
05607, 00000, "Status"
// *Comment: mnemonic:
/
05608, 00000, "Arguments"
// *Comment: mnemonic:
/
05609, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
05610, 00000, "Start Date"
// *Comment: mnemonic:
/
05611, 00000, "Start Date"
// *Comment: mnemonic:
/
05612, 00000, "Session ID"
// *Comment: mnemonic:
/
05613, 00000, "Session ID"
// *Comment: mnemonic:
/
05614, 00000, "Serial Number"
// *Comment: mnemonic:
/
05615, 00000, "Session Serial Number"
// *Comment: mnemonic:
/
05616, 00000, "Process ID"
// *Comment: mnemonic:
/
05617, 00000, "Process ID"
// *Comment: mnemonic:
/
05618, 00000, "State"
// *Comment: mnemonic:
/
05619, 00000, "State"
// *Comment: mnemonic:
/
05620, 00000, "Address of Lock Waiting for"
// *Comment: mnemonic:
/
05621, 00000, "Address of Lock Waiting for"
// *Comment: mnemonic:
/
05622, 00000, "Command in Progress"
// *Comment: mnemonic:
/
05623, 00000, "Command in Progress"
// *Comment: mnemonic:
/
05700, 00000, "Request ID"
// *Comment: mnemonic:
/
05701, 00000, "Request ID"
// *Comment: mnemonic:
/
05702, 00000, "Program Name"
// *Comment: mnemonic:
/
05703, 00000, "Program Name"
// *Comment: mnemonic:
/
05704, 00000, "Requested By"
// *Comment: mnemonic:
/
05705, 00000, "Requested By"
// *Comment: mnemonic:
/
05706, 00000, "Arguments"
// *Comment: mnemonic:
/
05707, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
05708, 00000, "Lock Type"
// *Comment: mnemonic:
/
05709, 00000, "Lock Type"
// *Comment: mnemonic:
/
05710, 00000, "Resource ID 1"
// *Comment: mnemonic:
/
05711, 00000, "Resource ID 1"
// *Comment: mnemonic:
/
05712, 00000, "Resource ID 2"
// *Comment: mnemonic:
/
05713, 00000, "Resource ID 2"
// *Comment: mnemonic:
/
05714, 00000, "Mode Requested"
// *Comment: mnemonic:
/
05715, 00000, "Mode Requested"
// *Comment: mnemonic:
/
05800, 00000, "Program Name"
// *Comment: mnemonic:
/
05801, 00000, "Program Name"
// *Comment: mnemonic:
/
05802, 00000, "Requested By"
// *Comment: mnemonic:
/
05803, 00000, "Requested By"
// *Comment: mnemonic:
/
05804, 00000, "Phase"
// *Comment: mnemonic:
/
05805, 00000, "Phase"
// *Comment: mnemonic:
/
05806, 00000, "Status"
// *Comment: mnemonic:
/
05807, 00000, "Status"
// *Comment: mnemonic:
/
05808, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
05809, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
05810, 00000, "Request Priority"
// *Comment: mnemonic:
/
05811, 00000, "Request Priority"
// *Comment: mnemonic:
/
05812, 00000, "Arguments"
// *Comment: mnemonic:
/
05813, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
05900, 00000, "Completed Successfully"
// *Comment: mnemonic:
/
05901, 00000, "Number of Requests Completed Successfully"
// *Comment: mnemonic:
/
05902, 00000, "Completed With Warning"
// *Comment: mnemonic:
/
05903, 00000, "Number of Requests Completed With Warning"
// *Comment: mnemonic:
/
05904, 00000, "Completed With Error"
// *Comment: mnemonic:
/
05905, 00000, "Number of Requests Completed With Error"
// *Comment: mnemonic:
/
06000, 00000, "Program Name"
// *Comment: mnemonic:
/
06001, 00000, "Program Name"
// *Comment: mnemonic:
/
06002, 00000, "User Name"
// *Comment: mnemonic:
/
06003, 00000, "User Name"
// *Comment: mnemonic:
/
06004, 00000, "Phase"
// *Comment: mnemonic:
/
06005, 00000, "Phase"
// *Comment: mnemonic:
/
06006, 00000, "Status"
// *Comment: mnemonic:
/
06007, 00000, "Status"
// *Comment: mnemonic:
/
06008, 00000, "Start Date"
// *Comment: mnemonic:
/
06009, 00000, "Start Date"
// *Comment: mnemonic:
/
06010, 00000, "Completion Date"
// *Comment: mnemonic:
/
06011, 00000, "Completion Date"
// *Comment: mnemonic:
/
06012, 00000, "Completion Message"
// *Comment: mnemonic:
/
06013, 00000, "Completion Message"
// *Comment: mnemonic:
/
06014, 00000, "Arguments"
// *Comment: mnemonic:
/
06015, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
06100, 00000, "Program Name"
// *Comment: mnemonic:
/
06101, 00000, "Program Name"
// *Comment: mnemonic:
/
06102, 00000, "User Name"
// *Comment: mnemonic:
/
06103, 00000, "User Name"
// *Comment: mnemonic:
/
06104, 00000, "Phase"
// *Comment: mnemonic:
/
06105, 00000, "Phase"
// *Comment: mnemonic:
/
06106, 00000, "Status"
// *Comment: mnemonic:
/
06107, 00000, "Status"
// *Comment: mnemonic:
/
06108, 00000, "Start Date"
// *Comment: mnemonic:
/
06109, 00000, "Start Date"
// *Comment: mnemonic:
/
06110, 00000, "Completion Date"
// *Comment: mnemonic:
/
06111, 00000, "Completion Date"
// *Comment: mnemonic:
/
06112, 00000, "Completion Message"
// *Comment: mnemonic:
/
06113, 00000, "Completion Message"
// *Comment: mnemonic:
/
06114, 00000, "Arguments"
// *Comment: mnemonic:
/
06115, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
06200, 00000, "Program Name"
// *Comment: mnemonic:
/
06201, 00000, "Program Name"
// *Comment: mnemonic:
/
06202, 00000, "User Name"
// *Comment: mnemonic:
/
06203, 00000, "User Name"
// *Comment: mnemonic:
/
06204, 00000, "Phase"
// *Comment: mnemonic:
/
06205, 00000, "Phase"
// *Comment: mnemonic:
/
06206, 00000, "Status"
// *Comment: mnemonic:
/
06207, 00000, "Status"
// *Comment: mnemonic:
/
06208, 00000, "Requested Start"
// *Comment: mnemonic:
/
06209, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
06210, 00000, "Priority"
// *Comment: mnemonic:
/
06211, 00000, "Request Priority"
// *Comment: mnemonic:
/
06212, 00000, "Arguments"
// *Comment: mnemonic:
/
06213, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
06300, 00000, "Program Name"
// *Comment: mnemonic:
/
06301, 00000, "Program Name"
// *Comment: mnemonic:
/
06302, 00000, "User Name"
// *Comment: mnemonic:
/
06303, 00000, "User Name"
// *Comment: mnemonic:
/
06304, 00000, "Phase"
// *Comment: mnemonic:
/
06305, 00000, "Phase"
// *Comment: mnemonic:
/
06306, 00000, "Status"
// *Comment: mnemonic:
/
06307, 00000, "Status"
// *Comment: mnemonic:
/
06308, 00000, "Requested Start"
// *Comment: mnemonic:
/
06309, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
06310, 00000, "Priority"
// *Comment: mnemonic:
/
06311, 00000, "Request Priority"
// *Comment: mnemonic:
/
06312, 00000, "Arguments"
// *Comment: mnemonic:
/
06313, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
06400, 00000, "Program Name"
// *Comment: mnemonic:
/
06401, 00000, "Program Name"
// *Comment: mnemonic:
/
06402, 00000, "User Name"
// *Comment: mnemonic:
/
06403, 00000, "User Name"
// *Comment: mnemonic:
/
06404, 00000, "Phase"
// *Comment: mnemonic:
/
06405, 00000, "Phase"
// *Comment: mnemonic:
/
06406, 00000, "Status"
// *Comment: mnemonic:
/
06407, 00000, "Status"
// *Comment: mnemonic:
/
06408, 00000, "Requested Start"
// *Comment: mnemonic:
/
06409, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
06410, 00000, "Priority"
// *Comment: mnemonic:
/
06411, 00000, "Request Priority"
// *Comment: mnemonic:
/
06412, 00000, "Arguments"
// *Comment: mnemonic:
/
06413, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
06500, 00000, "Program Name"
// *Comment: mnemonic:
/
06501, 00000, "Program Name"
// *Comment: mnemonic:
/
06502, 00000, "Requested By"
// *Comment: mnemonic:
/
06503, 00000, "Requested By"
// *Comment: mnemonic:
/
06504, 00000, "Phase"
// *Comment: mnemonic:
/
06505, 00000, "Phase"
// *Comment: mnemonic:
/
06506, 00000, "Status"
// *Comment: mnemonic:
/
06507, 00000, "Status"
// *Comment: mnemonic:
/
06508, 00000, "Arguments"
// *Comment: mnemonic:
/
06509, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
06510, 00000, "Priority"
// *Comment: mnemonic:
/
06511, 00000, "Request Priority"
// *Comment: mnemonic:
/
06512, 00000, "Reason"
// *Comment: mnemonic:
/
06513, 00000, "Reason"
// *Comment: mnemonic:
/
06700, 00000, "Pending Requests"
// *Comment: mnemonic:
/
06701, 00000, "Number of Pending Requests"
// *Comment: mnemonic:
/
06800, 00000, "Program Name"
// *Comment: mnemonic:
/
06801, 00000, "Program Name"
// *Comment: mnemonic:
/
06802, 00000, "Phase"
// *Comment: mnemonic:
/
06803, 00000, "Phase"
// *Comment: mnemonic:
/
06804, 00000, "Status"
// *Comment: mnemonic:
/
06805, 00000, "Status"
// *Comment: mnemonic:
/
06806, 00000, "User Name"
// *Comment: mnemonic:
/
06807, 00000, "User Name"
// *Comment: mnemonic:
/
06808, 00000, "Requested Start"
// *Comment: mnemonic:
/
06809, 00000, "Requested Start"
// *Comment: mnemonic:
/
06810, 00000, "Submission Time"
// *Comment: mnemonic:
/
06811, 00000, "Submission Time"
// *Comment: mnemonic:
/
06812, 00000, "Priority"
// *Comment: mnemonic:
/
06813, 00000, "Request Priority"
// *Comment: mnemonic:
/
06814, 00000, "Arguments"
// *Comment: mnemonic:
/
06815, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
06816, 00000, "Concurrent Manager"
// *Comment: mnemonic:
/
06817, 00000, "Concurrent Manager"
// *Comment: mnemonic:
/
06900, 00000, "Standby Requests"
// *Comment: mnemonic:
/
06901, 00000, "Number of Standby Requests"
// *Comment: mnemonic:
/
07000, 00000, "Program Name"
// *Comment: mnemonic:
/
07001, 00000, "Program Name"
// *Comment: mnemonic:
/
07002, 00000, "Phase"
// *Comment: mnemonic:
/
07003, 00000, "Phase"
// *Comment: mnemonic:
/
07004, 00000, "Status"
// *Comment: mnemonic:
/
07005, 00000, "Status"
// *Comment: mnemonic:
/
07006, 00000, "User Name"
// *Comment: mnemonic:
/
07007, 00000, "User Name"
// *Comment: mnemonic:
/
07008, 00000, "Requested Start"
// *Comment: mnemonic:
/
07009, 00000, "Requested Start"
// *Comment: mnemonic:
/
07010, 00000, "Submission Time"
// *Comment: mnemonic:
/
07011, 00000, "Submission Time"
// *Comment: mnemonic:
/
07012, 00000, "Priority"
// *Comment: mnemonic:
/
07013, 00000, "Request Priority"
// *Comment: mnemonic:
/
07014, 00000, "Arguments"
// *Comment: mnemonic:
/
07015, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
07016, 00000, "Concurrent Manager"
// *Comment: mnemonic:
/
07017, 00000, "Concurrent Manager"
// *Comment: mnemonic:
/
07100, 00000, "Running Requests"
// *Comment: mnemonic:
/
07101, 00000, "Number of Running Requests"
// *Comment: mnemonic:
/
07200, 00000, "Program Name"
// *Comment: mnemonic:
/
07201, 00000, "Program Name"
// *Comment: mnemonic:
/
07202, 00000, "Phase"
// *Comment: mnemonic:
/
07203, 00000, "Phase"
// *Comment: mnemonic:
/
07204, 00000, "Status"
// *Comment: mnemonic:
/
07205, 00000, "Status"
// *Comment: mnemonic:
/
07206, 00000, "User Name"
// *Comment: mnemonic:
/
07207, 00000, "User Name"
// *Comment: mnemonic:
/
07208, 00000, "Actual Start Time"
// *Comment: mnemonic:
/
07209, 00000, "Actual Start Time"
// *Comment: mnemonic:
/
07210, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
07211, 00000, "Requested Start Time"
// *Comment: mnemonic:
/
07212, 00000, "Submission Time"
// *Comment: mnemonic:
/
07213, 00000, "Submission Time"
// *Comment: mnemonic:
/
07214, 00000, "Priority"
// *Comment: mnemonic:
/
07215, 00000, "Request Priority"
// *Comment: mnemonic:
/
07216, 00000, "Arguments"
// *Comment: mnemonic:
/
07217, 00000, "Concatenated Program Arguments"
// *Comment: mnemonic:
/
07218, 00000, "Concurrent Manager"
// *Comment: mnemonic:
/
07219, 00000, "Concurrent Manager"
// *Comment: mnemonic:
/
07300, 00000, "Processes"
// *Comment: mnemonic:
/
07301, 00000, "Number of Processes"
// *Comment: mnemonic:
/
07400, 00000, "Concurrent Process ID"
// *Comment: mnemonic:
/
07401, 00000, "Concurrent Process ID"
// *Comment: mnemonic:
/
07402, 00000, "Status"
// *Comment: mnemonic:
/
07403, 00000, "Status"
// *Comment: mnemonic:
/
07404, 00000, "Concurrent Manager"
// *Comment: mnemonic:
/
07405, 00000, "Concurrent Manager"
// *Comment: mnemonic:
/
07406, 00000, "OS Process ID"
// *Comment: mnemonic:
/
07407, 00000, "OS Process ID"
// *Comment: mnemonic:
/
07408, 00000, "Oracle Process ID"
// *Comment: mnemonic:
/
07409, 00000, "Oracle Process ID"
// *Comment: mnemonic:
/
07410, 00000, "Session ID"
// *Comment: mnemonic:
/
07411, 00000, "Session ID"
// *Comment: mnemonic:
/
07412, 00000, "Serial Number"
// *Comment: mnemonic:
/
07413, 00000, "Session Serial Number"
// *Comment: mnemonic:
/
07414, 00000, "Running Request ID"
// *Comment: mnemonic:
/
07415, 00000, "Running Request ID"
// *Comment: mnemonic:
/
07500, 00000, "Program Name"
// *Comment: mnemonic:
/
07501, 00000, "Program Name"
// *Comment: mnemonic:
/
07502, 00000, "OS User"
// *Comment: mnemonic:
/
07503, 00000, "Operating System User Name"
// *Comment: mnemonic:
/
07504, 00000, "Process ID"
// *Comment: mnemonic:
/
07505, 00000, "Process ID"
// *Comment: mnemonic:
/
07506, 00000, "Node"
// *Comment: mnemonic:
/
07507, 00000, "Node(machine)"
// *Comment: mnemonic:
/
07508, 00000, "Terminal Name/Client IP"
// *Comment: mnemonic:
/
07509, 00000, "Terminal Name/Client Internet Protocol (IP)"
// *Comment: mnemonic:
/
07510, 00000, "Lock Type"
// *Comment: mnemonic:
/
07511, 00000, "Lock Type"
// *Comment: mnemonic:
/
07512, 00000, "Resource ID 1"
// *Comment: mnemonic:
/
07513, 00000, "Resource ID 1"
// *Comment: mnemonic:
/
07514, 00000, "Resource ID 2"
// *Comment: mnemonic:
/
07515, 00000, "Resource ID 2"
// *Comment: mnemonic:
/
07516, 00000, "Mode Requested"
// *Comment: mnemonic:
/
07517, 00000, "Mode Requested"
// *Comment: mnemonic:
/
07700, 00000, "Session ID"
// *Comment: mnemonic:
/
07701, 00000, "Session ID"
// *Comment: mnemonic:
/
07702, 00000, "Session Address"
// *Comment: mnemonic:
/
07703, 00000, "Session Address"
// *Comment: mnemonic:
/
07704, 00000, "Serial Number"
// *Comment: mnemonic:
/
07705, 00000, "Session Serial Number"
// *Comment: mnemonic:
/
07706, 00000, "Aud Sid"
// *Comment: mnemonic:
/
07707, 00000, "Auditing Session ID"
// *Comment: mnemonic:
/
07708, 00000, "Paddr"
// *Comment: mnemonic:
/
07709, 00000, "Paddr"
// *Comment: mnemonic:
/
07710, 00000, "Shadow Process ID"
// *Comment: mnemonic:
/
07711, 00000, "Shadow Process ID"
// *Comment: mnemonic:
/
07712, 00000, "User Number"
// *Comment: mnemonic:
/
07713, 00000, "User Number"
// *Comment: mnemonic:
/
07714, 00000, "User Name"
// *Comment: mnemonic:
/
07715, 00000, "User Name"
// *Comment: mnemonic:
/
07716, 00000, "Command"
// *Comment: mnemonic:
/
07717, 00000, "Command"
// *Comment: mnemonic:
/
07718, 00000, "Taddr"
// *Comment: mnemonic:
/
07719, 00000, "Taddr"
// *Comment: mnemonic:
/
07720, 00000, "Lockwait"
// *Comment: mnemonic:
/
07721, 00000, "Lockwait"
// *Comment: mnemonic:
/
07722, 00000, "Status"
// *Comment: mnemonic:
/
07723, 00000, "Status"
// *Comment: mnemonic:
/
07724, 00000, "Server"
// *Comment: mnemonic:
/
07725, 00000, "Server"
// *Comment: mnemonic:
/
07726, 00000, "Schema Number"
// *Comment: mnemonic:
/
07727, 00000, "Schema Number"
// *Comment: mnemonic:
/
07728, 00000, "Schema Name"
// *Comment: mnemonic:
/
07729, 00000, "Schema Name"
// *Comment: mnemonic:
/
07730, 00000, "OS User"
// *Comment: mnemonic:
/
07731, 00000, "OS User"
// *Comment: mnemonic:
/
07732, 00000, "Process"
// *Comment: mnemonic:
/
07733, 00000, "Process"
// *Comment: mnemonic:
/
07734, 00000, "Machine"
// *Comment: mnemonic:
/
07735, 00000, "Machine"
// *Comment: mnemonic:
/
07736, 00000, "Terminal"
// *Comment: mnemonic:
/
07737, 00000, "Terminal"
// *Comment: mnemonic:
/
07738, 00000, "Program"
// *Comment: mnemonic:
/
07739, 00000, "Program"
// *Comment: mnemonic:
/
07740, 00000, "Type"
// *Comment: mnemonic:
/
07741, 00000, "Type"
// *Comment: mnemonic:
/
07742, 00000, "SQL Address"
// *Comment: mnemonic:
/
07743, 00000, "SQL Address"
// *Comment: mnemonic:
/
07744, 00000, "SQL Hash Value"
// *Comment: mnemonic:
/
07745, 00000, "SQL Hash Value"
// *Comment: mnemonic:
/
07746, 00000, "Previous SQL Address"
// *Comment: mnemonic:
/
07747, 00000, "Previous SQL Address"
// *Comment: mnemonic:
/
07748, 00000, "Previous SQL Hash Value"
// *Comment: mnemonic:
/
07749, 00000, "Previous SQL Hash Value"
// *Comment: mnemonic:
/
07750, 00000, "Module"
// *Comment: mnemonic:
/
07751, 00000, "Module"
// *Comment: mnemonic:
/
07752, 00000, "Module Hash"
// *Comment: mnemonic:
/
07753, 00000, "Module Hash"
// *Comment: mnemonic:
/
07754, 00000, "Action"
// *Comment: mnemonic:
/
07755, 00000, "Action"
// *Comment: mnemonic:
/
07756, 00000, "Action Hash"
// *Comment: mnemonic:
/
07757, 00000, "Action Hash"
// *Comment: mnemonic:
/
07758, 00000, "Client Information"
// *Comment: mnemonic:
/
07759, 00000, "Client Information"
// *Comment: mnemonic:
/
07760, 00000, "Fixed Table Sequence"
// *Comment: mnemonic:
/
07761, 00000, "Fixed Table Sequence"
// *Comment: mnemonic:
/
07762, 00000, "Row Wait Object"
// *Comment: mnemonic:
/
07763, 00000, "Row Wait Object"
// *Comment: mnemonic:
/
07764, 00000, "Row Wait File"
// *Comment: mnemonic:
/
07765, 00000, "Row Wait File"
// *Comment: mnemonic:
/
07766, 00000, "Row Wait Block"
// *Comment: mnemonic:
/
07767, 00000, "Row Wait Block"
// *Comment: mnemonic:
/
07768, 00000, "Row Wait Row"
// *Comment: mnemonic:
/
07769, 00000, "Row Wait Row"
// *Comment: mnemonic:
/
07770, 00000, "Logon Time"
// *Comment: mnemonic:
/
07771, 00000, "Logon Time"
// *Comment: mnemonic:
/
07772, 00000, "Last Call ET"
// *Comment: mnemonic:
/
07773, 00000, "Last Call ET"
// *Comment: mnemonic:
/
07800, 00000, "Session ID"
// *Comment: mnemonic:
/
07801, 00000, "Session ID"
// *Comment: mnemonic:
/
07802, 00000, "Session Address"
// *Comment: mnemonic:
/
07803, 00000, "Session Address"
// *Comment: mnemonic:
/
07804, 00000, "Serial Number"
// *Comment: mnemonic:
/
07805, 00000, "Session Serial Number"
// *Comment: mnemonic:
/
07806, 00000, "Aud Sid"
// *Comment: mnemonic:
/
07807, 00000, "Auditing Session ID"
// *Comment: mnemonic:
/
07808, 00000, "Paddr"
// *Comment: mnemonic:
/
07809, 00000, "Paddr"
// *Comment: mnemonic:
/
07810, 00000, "Shadow Process ID"
// *Comment: mnemonic:
/
07811, 00000, "Shadow Process ID"
// *Comment: mnemonic:
/
07812, 00000, "User Number"
// *Comment: mnemonic:
/
07813, 00000, "User Number"
// *Comment: mnemonic:
/
07814, 00000, "User Name"
// *Comment: mnemonic:
/
07815, 00000, "User Name"
// *Comment: mnemonic:
/
07816, 00000, "Command"
// *Comment: mnemonic:
/
07817, 00000, "Command"
// *Comment: mnemonic:
/
07818, 00000, "Taddr"
// *Comment: mnemonic:
/
07819, 00000, "Taddr"
// *Comment: mnemonic:
/
07820, 00000, "Lockwait"
// *Comment: mnemonic:
/
07821, 00000, "Lockwait"
// *Comment: mnemonic:
/
07822, 00000, "Status"
// *Comment: mnemonic:
/
07823, 00000, "Status"
// *Comment: mnemonic:
/
07824, 00000, "Server"
// *Comment: mnemonic:
/
07825, 00000, "Server"
// *Comment: mnemonic:
/
07826, 00000, "Schema Number"
// *Comment: mnemonic:
/
07827, 00000, "Schema Number"
// *Comment: mnemonic:
/
07828, 00000, "Schema Name"
// *Comment: mnemonic:
/
07829, 00000, "Schema Name"
// *Comment: mnemonic:
/
07830, 00000, "OS User"
// *Comment: mnemonic:
/
07831, 00000, "OS User"
// *Comment: mnemonic:
/
07832, 00000, "Process"
// *Comment: mnemonic:
/
07833, 00000, "Process"
// *Comment: mnemonic:
/
07834, 00000, "Machine"
// *Comment: mnemonic:
/
07835, 00000, "Machine"
// *Comment: mnemonic:
/
07836, 00000, "Terminal"
// *Comment: mnemonic:
/
07837, 00000, "Terminal"
// *Comment: mnemonic:
/
07838, 00000, "Program"
// *Comment: mnemonic:
/
07839, 00000, "Program"
// *Comment: mnemonic:
/
07840, 00000, "Type"
// *Comment: mnemonic:
/
07841, 00000, "Type"
// *Comment: mnemonic:
/
07842, 00000, "SQL Address"
// *Comment: mnemonic:
/
07843, 00000, "SQL Address"
// *Comment: mnemonic:
/
07844, 00000, "SQL Hash Value"
// *Comment: mnemonic:
/
07845, 00000, "SQL Hash Value"
// *Comment: mnemonic:
/
07846, 00000, "Previous SQL Address"
// *Comment: mnemonic:
/
07847, 00000, "Previous SQL Address"
// *Comment: mnemonic:
/
07848, 00000, "Previous SQL Hash Value"
// *Comment: mnemonic:
/
07849, 00000, "Previous SQL Hash Value"
// *Comment: mnemonic:
/
07850, 00000, "Module"
// *Comment: mnemonic:
/
07851, 00000, "Module"
// *Comment: mnemonic:
/
07852, 00000, "Module Hash"
// *Comment: mnemonic:
/
07853, 00000, "Module Hash"
// *Comment: mnemonic:
/
07854, 00000, "Action"
// *Comment: mnemonic:
/
07855, 00000, "Action"
// *Comment: mnemonic:
/
07856, 00000, "Action Hash"
// *Comment: mnemonic:
/
07857, 00000, "Action Hash"
// *Comment: mnemonic:
/
07858, 00000, "Client Information"
// *Comment: mnemonic:
/
07859, 00000, "Client Information"
// *Comment: mnemonic:
/
07860, 00000, "Fixed Table Sequence"
// *Comment: mnemonic:
/
07861, 00000, "Fixed Table Sequence"
// *Comment: mnemonic:
/
07862, 00000, "Row Wait Object"
// *Comment: mnemonic:
/
07863, 00000, "Row Wait Object"
// *Comment: mnemonic:
/
07864, 00000, "Row Wait File"
// *Comment: mnemonic:
/
07865, 00000, "Row Wait File"
// *Comment: mnemonic:
/
07866, 00000, "Row Wait Block"
// *Comment: mnemonic:
/
07867, 00000, "Row Wait Block"
// *Comment: mnemonic:
/
07868, 00000, "Row Wait Row"
// *Comment: mnemonic:
/
07869, 00000, "Row Wait Row"
// *Comment: mnemonic:
/
07870, 00000, "Logon Time"
// *Comment: mnemonic:
/
07871, 00000, "Logon Time"
// *Comment: mnemonic:
/
07872, 00000, "Last Call ET"
// *Comment: mnemonic:
/
07873, 00000, "Last Call ET"
// *Comment: mnemonic:
/
07900, 00000, "Session ID"
// *Comment: mnemonic:
/
07901, 00000, "Session ID"
// *Comment: mnemonic:
/
07902, 00000, "Session Address"
// *Comment: mnemonic:
/
07903, 00000, "Session Address"
// *Comment: mnemonic:
/
07904, 00000, "Serial Number"
// *Comment: mnemonic:
/
07905, 00000, "Session Serial Number"
// *Comment: mnemonic:
/
07906, 00000, "Aud Sid"
// *Comment: mnemonic:
/
07907, 00000, "Auditing Session ID"
// *Comment: mnemonic:
/
07908, 00000, "Paddr"
// *Comment: mnemonic:
/
07909, 00000, "Paddr"
// *Comment: mnemonic:
/
07910, 00000, "Shadow Process ID"
// *Comment: mnemonic:
/
07911, 00000, "Shadow Process ID"
// *Comment: mnemonic:
/
07912, 00000, "User Number"
// *Comment: mnemonic:
/
07913, 00000, "User Number"
// *Comment: mnemonic:
/
07914, 00000, "User Name"
// *Comment: mnemonic:
/
07915, 00000, "User Name"
// *Comment: mnemonic:
/
07916, 00000, "Command"
// *Comment: mnemonic:
/
07917, 00000, "Command"
// *Comment: mnemonic:
/
07918, 00000, "Taddr"
// *Comment: mnemonic:
/
07919, 00000, "Taddr"
// *Comment: mnemonic:
/
07920, 00000, "Lockwait"
// *Comment: mnemonic:
/
07921, 00000, "Lockwait"
// *Comment: mnemonic:
/
07922, 00000, "Status"
// *Comment: mnemonic:
/
07923, 00000, "Status"
// *Comment: mnemonic:
/
07924, 00000, "Server"
// *Comment: mnemonic:
/
07925, 00000, "Server"
// *Comment: mnemonic:
/
07926, 00000, "Schema Number"
// *Comment: mnemonic:
/
07927, 00000, "Schema Number"
// *Comment: mnemonic:
/
07928, 00000, "Schema Name"
// *Comment: mnemonic:
/
07929, 00000, "Schema Name"
// *Comment: mnemonic:
/
07930, 00000, "OS User"
// *Comment: mnemonic:
/
07931, 00000, "OS User"
// *Comment: mnemonic:
/
07932, 00000, "Process"
// *Comment: mnemonic:
/
07933, 00000, "Process"
// *Comment: mnemonic:
/
07934, 00000, "Machine"
// *Comment: mnemonic:
/
07935, 00000, "Machine"
// *Comment: mnemonic:
/
07936, 00000, "Terminal"
// *Comment: mnemonic:
/
07937, 00000, "Terminal"
// *Comment: mnemonic:
/
07938, 00000, "Program"
// *Comment: mnemonic:
/
07939, 00000, "Program"
// *Comment: mnemonic:
/
07940, 00000, "Type"
// *Comment: mnemonic:
/
07941, 00000, "Type"
// *Comment: mnemonic:
/
07942, 00000, "SQL Address"
// *Comment: mnemonic:
/
07943, 00000, "SQL Address"
// *Comment: mnemonic:
/
07944, 00000, "SQL Hash Value"
// *Comment: mnemonic:
/
07945, 00000, "SQL Hash Value"
// *Comment: mnemonic:
/
07946, 00000, "Previous SQL Address"
// *Comment: mnemonic:
/
07947, 00000, "Previous SQL Address"
// *Comment: mnemonic:
/
07948, 00000, "Previous SQL Hash Value"
// *Comment: mnemonic:
/
07949, 00000, "Previous SQL Hash Value"
// *Comment: mnemonic:
/
07950, 00000, "Module"
// *Comment: mnemonic:
/
07951, 00000, "Module"
// *Comment: mnemonic:
/
07952, 00000, "Module Hash"
// *Comment: mnemonic:
/
07953, 00000, "Module Hash"
// *Comment: mnemonic:
/
07954, 00000, "Action"
// *Comment: mnemonic:
/
07955, 00000, "Action"
// *Comment: mnemonic:
/
07956, 00000, "Action Hash"
// *Comment: mnemonic:
/
07957, 00000, "Action Hash"
// *Comment: mnemonic:
/
07958, 00000, "Client Information"
// *Comment: mnemonic:
/
07959, 00000, "Client Information"
// *Comment: mnemonic:
/
07960, 00000, "Fixed Table Sequence"
// *Comment: mnemonic:
/
07961, 00000, "Fixed Table Sequence"
// *Comment: mnemonic:
/
07962, 00000, "Row Wait Object"
// *Comment: mnemonic:
/
07963, 00000, "Row Wait Object"
// *Comment: mnemonic:
/
07964, 00000, "Row Wait File"
// *Comment: mnemonic:
/
07965, 00000, "Row Wait File"
// *Comment: mnemonic:
/
07966, 00000, "Row Wait Block"
// *Comment: mnemonic:
/
07967, 00000, "Row Wait Block"
// *Comment: mnemonic:
/
07968, 00000, "Row Wait Row"
// *Comment: mnemonic:
/
07969, 00000, "Row Wait Row"
// *Comment: mnemonic:
/
07970, 00000, "Logon Time"
// *Comment: mnemonic:
/
07971, 00000, "Logon Time"
// *Comment: mnemonic:
/
07972, 00000, "Last Call ET"
// *Comment: mnemonic:
/
07973, 00000, "Last Call ET"
// *Comment: mnemonic:
/
08000, 00000, "Session ID"
// *Comment: mnemonic:
/
08001, 00000, "Session ID"
// *Comment: mnemonic:
/
08002, 00000, "Session Address"
// *Comment: mnemonic:
/
08003, 00000, "Session Address"
// *Comment: mnemonic:
/
08004, 00000, "Serial Number"
// *Comment: mnemonic:
/
08005, 00000, "Session Serial Number"
// *Comment: mnemonic:
/
08006, 00000, "Paddr"
// *Comment: mnemonic:
/
08007, 00000, "Paddr"
// *Comment: mnemonic:
/
08008, 00000, "Shadow Process ID"
// *Comment: mnemonic:
/
08009, 00000, "Shadow Process ID"
// *Comment: mnemonic:
/
08010, 00000, "User Number"
// *Comment: mnemonic:
/
08011, 00000, "User Number"
// *Comment: mnemonic:
/
08012, 00000, "User Name"
// *Comment: mnemonic:
/
08013, 00000, "User Name"
// *Comment: mnemonic:
/
08014, 00000, "Command"
// *Comment: mnemonic:
/
08015, 00000, "Command"
// *Comment: mnemonic:
/
08016, 00000, "Taddr"
// *Comment: mnemonic:
/
08017, 00000, "Taddr"
// *Comment: mnemonic:
/
08018, 00000, "Lockwait"
// *Comment: mnemonic:
/
08019, 00000, "Lockwait"
// *Comment: mnemonic:
/
08020, 00000, "Status"
// *Comment: mnemonic:
/
08021, 00000, "Status"
// *Comment: mnemonic:
/
08022, 00000, "Server"
// *Comment: mnemonic:
/
08023, 00000, "Server"
// *Comment: mnemonic:
/
08024, 00000, "Schema Number"
// *Comment: mnemonic:
/
08025, 00000, "Schema Number"
// *Comment: mnemonic:
/
08026, 00000, "Schema Name"
// *Comment: mnemonic:
/
08027, 00000, "Schema Name"
// *Comment: mnemonic:
/
08028, 00000, "OS User"
// *Comment: mnemonic:
/
08029, 00000, "OS User"
// *Comment: mnemonic:
/
08030, 00000, "Process"
// *Comment: mnemonic:
/
08031, 00000, "Process"
// *Comment: mnemonic:
/
08032, 00000, "Machine"
// *Comment: mnemonic:
/
08033, 00000, "Machine"
// *Comment: mnemonic:
/
08034, 00000, "Terminal"
// *Comment: mnemonic:
/
08035, 00000, "Terminal"
// *Comment: mnemonic:
/
08036, 00000, "Program"
// *Comment: mnemonic:
/
08037, 00000, "Program"
// *Comment: mnemonic:
/
08038, 00000, "Type"
// *Comment: mnemonic:
/
08039, 00000, "Type"
// *Comment: mnemonic:
/
08040, 00000, "SQL Address"
// *Comment: mnemonic:
/
08041, 00000, "SQL Address"
// *Comment: mnemonic:
/
08042, 00000, "SQL Hash Value"
// *Comment: mnemonic:
/
08043, 00000, "SQL Hash Value"
// *Comment: mnemonic:
/
08044, 00000, "Previous SQL Address"
// *Comment: mnemonic:
/
08045, 00000, "Previous SQL Address"
// *Comment: mnemonic:
/
08046, 00000, "Previous SQL Hash Value"
// *Comment: mnemonic:
/
08047, 00000, "Previous SQL Hash Value"
// *Comment: mnemonic:
/
08048, 00000, "Module"
// *Comment: mnemonic:
/
08049, 00000, "Module"
// *Comment: mnemonic:
/
08050, 00000, "Module Hash"
// *Comment: mnemonic:
/
08051, 00000, "Module Hash"
// *Comment: mnemonic:
/
08052, 00000, "Action"
// *Comment: mnemonic:
/
08053, 00000, "Action"
// *Comment: mnemonic:
/
08054, 00000, "Action Hash"
// *Comment: mnemonic:
/
08055, 00000, "Action Hash"
// *Comment: mnemonic:
/
08056, 00000, "Client Information"
// *Comment: mnemonic:
/
08057, 00000, "Client Information"
// *Comment: mnemonic:
/
08058, 00000, "Fixed Table Sequence"
// *Comment: mnemonic:
/
08059, 00000, "Fixed Table Sequence"
// *Comment: mnemonic:
/
08060, 00000, "Row Wait Object"
// *Comment: mnemonic:
/
08061, 00000, "Row Wait Object"
// *Comment: mnemonic:
/
08062, 00000, "Row Wait File"
// *Comment: mnemonic:
/
08063, 00000, "Row Wait File"
// *Comment: mnemonic:
/
08064, 00000, "Row Wait Block"
// *Comment: mnemonic:
/
08065, 00000, "Row Wait Block"
// *Comment: mnemonic:
/
08066, 00000, "Row Wait Row"
// *Comment: mnemonic:
/
08067, 00000, "Row Wait Row"
// *Comment: mnemonic:
/
08068, 00000, "Logon Time"
// *Comment: mnemonic:
/
08069, 00000, "Logon Time"
// *Comment: mnemonic:
/
08070, 00000, "Last Call ET"
// *Comment: mnemonic:
/
08071, 00000, "Last Call ET"
// *Comment: mnemonic:
/
08100, 00000, "Statistic Name"
// *Comment: mnemonic:
/
08101, 00000, "Statistic Name"
// *Comment: mnemonic:
/
08102, 00000, "Statistic Value"
// *Comment: mnemonic:
/
08103, 00000, "Statistic Value"
// *Comment: mnemonic:
/
08200, 00000, "Statistic Name"
// *Comment: mnemonic:
/
08201, 00000, "Statistic Name"
// *Comment: mnemonic:
/
08202, 00000, "Statistic Value"
// *Comment: mnemonic:
/
08203, 00000, "Statistic Value"
// *Comment: mnemonic:
/
08300, 00000, "Statistic Name"
// *Comment: mnemonic:
/
08301, 00000, "Statistic Name"
// *Comment: mnemonic:
/
08302, 00000, "Statistic Value"
// *Comment: mnemonic:
/
08303, 00000, "Statistic Value"
// *Comment: mnemonic:
/
08400, 00000, "Statistic Name"
// *Comment: mnemonic:
/
08401, 00000, "Statistic Name"
// *Comment: mnemonic:
/
08402, 00000, "Statistic Value"
// *Comment: mnemonic:
/
08403, 00000, "Statistic Value"
// *Comment: mnemonic:
/
08500, 00000, "Line"
// *Comment: mnemonic:
/
08501, 00000, "Line"
// *Comment: mnemonic:
/
08502, 00000, "Text"
// *Comment: mnemonic:
/
08503, 00000, "Text"
// *Comment: mnemonic:
/
08600, 00000, "Line"
// *Comment: mnemonic:
/
08601, 00000, "Line"
// *Comment: mnemonic:
/
08602, 00000, "Text"
// *Comment: mnemonic:
/
08603, 00000, "Text"
// *Comment: mnemonic:
/
