//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SE_CAT_REG.rc
//
#define IDC_DeleteGroup                 3
#define IDOK2                           3
#define IDC_BINDBOOK_LIST               3
#define IDC_ModifyGroup                 4
#define IDC_rB4                         1005
#define IDC_rA4                         1006
#define IDC_rA4_RANDSCAPE               1007
#define IDC_eLESSONNAME                 1018
#define IDC_rPRINT_TYPE                 1021
#define IDC_rSHELF_PRINT                1022
#define IDC_rACCESSIONNO_PRINT          1023
#define IDC_rACCESSION_NO               1119
#define IDC_preGROUP_NO2                1120
#define IDC_eACCESSION_NO_END           1120
#define IDC_eACCESSION_NO_START         1121
#define IDC_preGROUP_NO4                1121
#define IDC_preGROUP_NO1                1123
#define IDC_REG_NO2                     1124
#define IDC_GROUP_NO                    1125
#define IDC_REG_DATE1                   1126
#define IDC_REG_DATE2                   1127
#define IDC_rACCESSION_DATE             1128
#define IDC_preGROUP_NO3                1128
#define IDC_rACCESSION_DATE2            1129
#define IDC_eREGISTRAR                  1133
#define IDC_cMED_CLASS                  1137
#define IDC_cACQUISIT_CLASS             1282
#define IDC_eACQUISIT_YEAR              1284
#define IDC_eACCESSION_REC_NO           1325
#define IDC_REG_NO1                     1325
#define IDC_WORK_NO                     1326
#define IDC_rACCESSION_REC_NO           1326
#define IDC_preGROUP                    1327
#define IDC_cMAT_CLASS                  1363
#define IDC_eMAT_CLASS                  1364
#define IDC_GROUP_YEAR                  1408
#define IDC_eRECEIPT_YEAR               1408
#define IDC_GROUPNO_YEAR                1409
#define IDC_ePROVIDER                   1435
#define IDC_eOFFICIALRANK               1454
#define IDC_REG_TITLE                   1460
#define IDC_REG_AUTHOR                  1461
#define IDC_REG_OTHER_TITLE             1462
#define IDC_REG_PUBLISH_DATE            1463
#define IDC_REG_PRICE                   1464
#define IDC_eTRANSFER_DATE              1969
#define IDC_cREG_CLASS                  2065
#define IDC_cFORM_CLASS                 2065
#define IDC_cREG_CLASS2                 2066
#define IDC_cREG_CLASS3                 2067
#define IDC_eACCESSION_DATE             2223
#define IDC_eACCESSION_DATE_END         2353
#define IDC_eACCESSION_DATE_START       2354
#define IDC_cUSE_OBJECT_CLASS           2774
#define IDC_cMANAGE_CLASS               2776
#define IDC_eRECEIPTOR                  2882
#define IDC_eCLASSIFIER                 2884
#define IDC_eCLASSIFY_DATE              2885
#define IDC_eCATALOGER                  2886
#define IDC_eCATALOG_DATE               2887
#define IDC_eMECH_PREPTOR               2888
#define IDC_eMECH_PREP_DATE             2889
#define IDC_ePROCESSION_COMPLETE_WORKER 2890
#define IDC_ePROCESSING_COMPLETE_DATE   2891
#define IDC_eSHELF_WORKER               2892
#define IDC_eSHELF_DATE                 2893
#define IDC_bACCESSIONNO_GIVE           3003
#define IDC_bREG0100CLEAR               3035
#define IDC_bDetailNo                   3036
#define IDC_bNEXT                       3106
#define IDC_bPREV                       3123
#define IDC_bCat0500PRINT               3130
#define IDC_bAccessionUpdate            3131
#define IDC_bAccessionDelete            3132
#define IDC_bAccessionInput             3133
#define IDC_bSEARCH                     3147
#define IDC_dash_STATUS                 4321
#define IDC_bCHANGE_CODE                12000
#define IDD_SE_CAT_GROUP_INSERT         9676
#define IDC_NEW_GROUP                   12001
#define IDC_GROUPGRID                   12002
#define IDC_GROUP_SEARCH                12003
#define IDC_bSaveNo                     12004
#define IDC_GIVEREGNO                   12005
#define IDD_MULTISORT                   9677
#define IDC_pregroup_STATUS             12006
#define IDC_dash_top_STATUS             12007
#define IDC_dash_down_STATUS            12008
#define IDC_dash_line_STATUS            12009
#define IDC_CREAT_preGROUPNO            12010
#define IDC_NewGroup                    12011
#define IDC_input_type_STATUS           12012
#define IDC_cSORT_COLUMN_1              12016
#define IDC_cSORT_COLUMN_2              12017
#define IDC_cSORT_COLUMN_3              12018
#define IDC_cSORT_COLUMN_4              12019
#define IDC_cSORT_COLUMN_5              12020
#define IDC_cSORT_COLUMN_6              12021
#define IDC_cSORT_DIR_1                 12022
#define IDC_cSORT_DIR_2                 12023
#define IDC_cSORT_DIR_3                 12024
#define IDC_cSORT_DIR_4                 12025
#define IDC_cSORT_DIR_5                 12026
#define IDC_cSORT_DIR_6                 12027
#define IDC_bSORT_MULTI                 12028
#define IDC_bDEFAULT_VALUE              12029
#define IDC_guide_line2                 14000
#define IDC_REG_NO_DESC                 14001
#define IDC_cobWorkingStatus            14002
#define IDC_REGDATA_STATUS              14003
#define IDC_BIND_TYPE                   14006
#define IDC_VIEWGRID                    15000
#define IDC_REG_VOL_TITLE               15001
#define IDC_BINDGRID                    15002
#define IDC_strGROUP_YEAR1              15003
#define IDC_strGROUP_NO1                15004
#define IDC_preYEAR                     15005
#define IDC_strORDER_NO                 15006
#define IDC_cobAcqCode                  15012
#define IDC_bLastNumber                 15022
#define IDC_REG_7                       15026
#define IDC_REG_8                       15027
#define IDC_guide_line                  15028
#define IDC_REG_9                       15028
#define IDC_REG_10                      15029
#define IDC_REG_11                      15030
#define IDC_MSHFLEXGRID                 19000
#define IDD_BO_CAT_REG_0800             9678
#define IDD_BO_CAT_REG_0520             9679
#define IDD_BO_CAT_REG_0510             9680
#define IDD_SE_CAT_REG_0400             9681
#define IDD_SE_CAT_REG_CODE             9682
#define IDD_SE_CAT_SEARCH               9683
#define IDD_SE_CAT_REG_MAIN             9684
#define IDD_SE_CAT_PREGROUP_MAIN        9685
#define IDD_SE_CAT_GROUP_MAIN           9686
#define IDD_SE_CAT_REG_GIVENO           9687
#define IDD_SE_CAT_MAKE_preGROUP        9688
#define IDD_SE_CAT_preGROUP_MNG         9689
#define IDD_SE_CAT_VIEW_MODIFY          9690
#define IDD_SE_CAT_BIND_VIEW            9691
#define IDD_SE_CAT_SEARCH_PRE           9692
#define IDD_SE_CAT_SEARCH_GROUP         9693
#define IDC_rCanRegNo                   29005
#define IDC_rAcqBack                    29007
#define IDC_REG_STATUS                  65535
#define IDC_input_data_STATUS           65535
#define IDC_strGROUP_YEAR               65535
#define IDC_strGROUP_NO                 65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        15000
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         15007
#define _APS_NEXT_SYMED_VALUE           15000
#endif
#endif
