//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BO_ACQ_GROUP_MANAGER.rc
//
#define IDC_btnGROUP_SEARCH             9007
#define IDC_btnGROUP_INSERT             9008
#define IDC_btnGROUP_UPDATE             9009
#define IDC_btnGROUP_DELETE             9010
#define IDC_btnDIVNO_DELETE             9018
#define IDC_edtDIVNO                    9019
#define IDC_chkDIVNO_WORK_DUP_SEARCH    9021
#define IDC_chkDIVNO_HOLD_DUP_SEARCH    9022
#define IDC_chkDIVNO_PURCHASE_CHECK     9023
#define IDC_edtDIVNO_ACQYEAR            9024
#define IDC_edtDIVNO_CREATE_DATE        9026
#define IDC_edtDIVNO_CREATOR            9027
#define IDC_edtDIVNO_STATUS             9028
#define IDC_radDIVNO_MYDATA             9029
#define IDC_radDIVNO_ALLDATA            9030
#define IDC_btnDIVNO_SEARCH             9031
#define IDC_gridDIVNO_LIST              9032
#define IDC_btnDIVNO_INFO               9033
#define IDC_btnDIVNO_INSERT             9034
#define IDC_btnDIVNO_UPDATE             9035
#define IDC_btnDIVNO_MERGE              9037
#define IDC_btnDIVNO_DIVIDE             9038
#define IDC_edtGROUP_CREATE_YEAR        9039
#define IDC_edtGROUP_CREATOR            9040
#define IDC_edtGROUP_NAME               9041
#define IDC_radGROUP_MYDATA             9042
#define IDC_radGROUP_ALLDATA            9043
#define IDC_gridGROUP_LIST              9044
#define IDC_gridDIVNO_INFO              9045
#define IDC_btnDIVNO_INFO_PRINT         9046
#define IDC_btnGROUP_PRINT              9047
#define IDC_btnDIVNO_COPY               9048
#define IDC_chkDIVNO_WORKDUP            9051
#define IDC_chkDIVNO_HOLDDUP            9052
#define IDC_chkDIVNO_PURCHECK           9053
#define IDC_btnDIVNO_NEXT               9054
#define IDC_btnDIVNO_PREV               9055
#define IDC_btnDIVNO_INFO_NEXT          9056
#define IDC_btnDIVNO_INFO_PREV          9057
#define IDC_edtDIVNO_WORK_NO            9058
#define IDC_chkDIVNO_UNUSE_WORK_NO      9059
#define IDC_cmbDIVNO_WORKNO             9060
#define IDC_btnGROUP_NEXT               9061
#define IDC_btnGROUP_PREV               9062
#define IDC_btnGROUP_APPLY              9065
#define IDC_edtGROUP_LAST_NO            9067
#define IDC_edtGROUP_SEQ                9068
#define IDC_btnGROUP_MERGE              9069
#define IDC_btnGROUP_DIVIDE             9070
#define IDC_btnGROUP_COPY               9071
#define IDC_radGROUP_ONLY               9072
#define IDC_radGROUP_INDATA             9073
#define IDC_radGROUP_NEW                9074
#define IDC_radGROUP_EXIST              9075
#define IDC_cmbGROUP_NAME_LIST          9076
#define IDC_edtDIVNO_ORDER_DATE         9080
#define IDC_edtDIVNO_CHECKIN_DATE       9081
#define IDC_edtDIVNO_BOOK_CNT           9082
#define IDC_edtDIV_NO_TOTAL_PRICE       9083
#define IDC_edtDIVNO_WORK_STATUS        9084
#define IDC_edtREQNO_ACQYEAR            9086
#define IDC_edtREQNO                    9087
#define IDC_edtREQNO_CREATE_DATE        9088
#define IDC_edtREQNO_CREATOR            9089
#define IDC_btnREQNO_NEXT               9090
#define IDC_btnREQNO_PREV               9091
#define IDC_edtREQNO_ACQ_YEAR           9092
#define IDC_radREQNO_ALLDATA            9093
#define IDC_radREQNO_MYDATA             9094
#define IDC_btnREQNO_SEARCH             9095
#define IDC_btnREQNO_INSERT             9096
#define IDC_btnREQNO_DELETE             9097
#define IDC_btnREQNO_UPDATE             9099
#define IDC_btnREQNO_MERGE              9100
#define IDC_btnREQNO_DIVIDE             9101
#define IDC_btnREQNO_COPY               9102
#define IDC_gridREQNO_LIST              9103
#define IDC_edtREQNO_BOOK_CNT           9104
#define IDC_edtREQNO_TOTAL_PRICE        9105
#define IDC_edtACQ_YEAR                 9107
#define IDC_btnVIEW_DIVNO               9110
#define IDC_btnDIVNO_CREATE             9117
#define IDC_btnREQNO_CREATE             9118
#define IDC_edtDIVNO_DIVIDE_ACQ_YEAR    9119
#define IDC_edtDIVNO_DIVIDE             9120
#define IDC_edtDIVNO_DIVIDE_WORKSTATUS  9123
#define IDC_gridDIVNO_DIVIDE            9124
#define IDC_btnDIVNO_DIVIDE_NEXT        9125
#define IDC_btnDIVNO_DIVIDE_PREV        9126
#define IDC_btnGROUP_DIVIDE_PREV        9128
#define IDC_btnGROUP_DIVIDE_NEXT        9129
#define IDC_gridGROUP_DIVIDE            9130
#define IDC_edtREQNO_DIVIDE_ACQ_YEAR    9131
#define IDC_edtREQNO_DIVIDE             9132
#define IDC_edtREQNO_DIVIDE_CREATOR     9133
#define IDC_gridREQNO_DIVIDE            9134
#define IDC_btnREQNO_DIVIDE_PREV        9135
#define IDC_btnOTHER_GROUP_NO_DIVIDE_NEXT 9136
#define IDC_edtGROUP_DIVIDE_ACQ_YEAR    9137
#define IDC_edtGROUP_DIVIDE_NAME        9138
#define IDC_edtGROUP_DIVIDE             9139
#define IDC_btnGROUP_CREATE             9140
#define IDC_cmbMSEL_GROUP_INFO          9141
#define IDC_btnMSEL_GROUP_CREATE        9142
#define IDC_stcMSEL_GROUP_INFO          9143
#define IDC_edtGROUPVIEW_CREATE_YEAR    9144
#define IDC_radGROUPVIEW_ALLDATA        9145
#define IDC_radGROUPVIEW_MYDATA         9146
#define IDC_btnREQNO_DIVIDE_NEXT        9147
#define IDC_gridGROUPVIEW_LIST          9148
#define IDC_btnGROUPVIEW_APPLY          9149
#define IDC_btnGROUPVIEW_SEARCH         9150
#define IDC_edtREQNOVIEW_ACQ_YEAR       9151
#define IDC_radREQNOVIEW_ALLDATA        9152
#define IDC_radREQNOVIEW_MYDATA         9153
#define IDC_btnREQNOVIEW_SEARCH         9154
#define IDC_gridREQNOVIEW_LIST          9155
#define IDC_btnREQNOVIEW_APPLY          9156
#define IDC_cmbREQNOVIEW_DATA_STATUS    9157
#define IDC_cmbDIVNO_WORK_STATUS        9158
#define IDC_cmbGROUPVIEW_DATA_STATUS    9159
#define IDC_edtREQNO_LAST_SEARIAL_NO    9160
#define IDC_cmbDIVNO_WORK_CODE          9161
#define IDC_chkDIVNO_WORK_NO_USE_YN     9166
#define IDC_btnDROP_GROUPNO_APPLY       9167
#define IDC_btnDIVNO_STATUS_CHANGE      9168
#define IDC_btnREQNO_INFO               9169
#define IDC_edtDROP_TYPE                9170
#define IDC_edtDROP_ACQ_YEAR            9171
#define IDC_edtDROP_WORK_CODE           9173
#define IDC_strDROP_WORK_CODE           9174
#define IDC_gridDROP_GROUPNO_LIST       9175
#define IDC_edtSTATUS_ACQ_YEAR          9176
#define IDC_edtSTATUS_WORK_CODE         9177
#define IDC_edtSTATUS_PREV_STATUS       9178
#define IDC_edtSTATUS_DIVNO             9179
#define IDC_cmbSTATUS_CHANGE_STATUS     9180
#define IDC_stcCHECK_INFO               9182
#define IDC_gridCHECK_HOLD_DATA         9183
#define IDC_btnOTHER_GROUP_NO_VIEW_DIVNO 9184
#define IDC_btnOTHER_GROUP_NO_CREATE    9185
#define IDC_edtACQ_GROUP_ACQYEAR        9186
#define IDC_radACQ_GROUP_MYDATA         9187
#define IDC_radACQ_GROUP_ALLDATA        9188
#define IDC_cmbACQ_GROUP_WORK_STATUS    9189
#define IDC_cmbACQ_GROUP_WORK_CODE      9190
#define IDC_gridPURCHASE_GROUP          9191
#define IDC_gridOTHER_GROUP             9192
#define IDC_gridACQOBJ_GROUP            9193
#define IDC_stcGROUP_SEARCH_GROUP1      9194
#define IDC_stcGROUP_SEARCH_GROUP2      9195
#define IDC_stcGROUP_SEARCH_WORK_STATUS 9196
#define IDC_stcGROUP_SEARCH_WORK_CODE   9197
#define IDC_stcGROUP_SEARCH_ACQ_CODE    9198
#define IDC_cmbGROUP_SEARCH_ACQ_CODE    9199
#define IDC_stcDONATE_GROUP             9200
#define IDC_edtGROUP_ACQ_YEAR           9201
#define IDC_stcGROUP_ACQ_YEAR           9202
#define IDC_stcACQOBJ_GROUP             9203
#define IDC_stcGROUP_ACQ_CODE           9204
#define IDC_stcGROUP_WORK_CODE          9206
#define IDC_edtGROUP_WORK_STATUS        9208
#define IDC_stcGROUP_WORK_STATUS        9209
#define IDC_edtGROUP_WORK_CODE          9210
#define IDC_edtGROUP_ACQ_CODE           9211
#define IDC_stcACQ_GROUP                9212
#define IDC_stcPURCHASE_GROUP           9213
#define IDC_btnDATA_SORT                9215
#define IDC_btnGROUP_NO_INFO_PREV       9216
#define IDC_btnGROUP_NO_INFO_NEXT       9217
#define IDC_btnBUDGET_CANCEL            9219
#define IDC_btnBUDGET_EXECUTION         9220
#define IDC_btnDIVNO_INSERT_SUB         9221
#define IDC_btnDIVNO_UPDATE_SUB         9222
#define IDC_btnDIVNO_DELETE_SUB         9223
#define IDC_cmbEXECUTION                9224
#define IDC_btnBUDGET_EXECUTION2        9225
#define IDC_edtREMARK                   12402
#define IDC_gridDONATE_GROUP            14001
#define IDC_cmbOTHER_GROUP_NO_ACQ_CODE  15000
#define IDC_btnOTHER_GROUP_NO_INFO      15001
#define IDC_gridGROUP_INFO              19000
#define IDC_gridOTHER_GROUP_NO_INFO     19045
#define IDC_btnOTHER_GROUP_NO_INFO_PRINT 19046
#define IDC_btnOTHER_GROUP_NO_INFO_NEXT 19056
#define IDC_btnOTHER_GROUP_NO_INFO_PREV 19057
#define IDC_edtOTHER_GROUP_NO_ACQYEAR   19086
#define IDC_edtOTHER_GROUP_NO           19087
#define IDC_edtOTHER_GROUP_NO_CREATE_DATE 19088
#define IDC_edtOTHER_GROUP_NO_CREATOR   19089
#define IDC_btnOTHER_GROUP_NO_NEXT      19090
#define IDC_btnOTHER_GROUP_NO_PREV      19091
#define IDC_edtOTHER_GROUP_NO_ACQ_YEAR  19092
#define IDC_radOTHER_GROUP_NO_ALLDATA   19093
#define IDC_radOTHER_GROUP_NO_MYDATA    19094
#define IDC_btnOTHER_GROUP_NO_SEARCH    19095
#define IDC_btnOTHER_GROUP_NO_INSERT    19096
#define IDC_btnOTHER_GROUP_NO_DELETE    19097
#define IDC_btnOTHER_GROUP_NO_UPDATE    19099
#define IDC_btnOTHER_GROUP_NO_MERGE     19100
#define IDC_btnOTHER_GROUP_NO_DIVIDE    19101
#define IDC_btnOTHER_GROUP_NO_COPY      19102
#define IDC_gridOTHER_GROUP_NO_LIST     19103
#define IDC_edtOTHER_GROUP_NO_BOOK_CNT  19104
#define IDC_edtOTHER_GROUP_NO_TOTAL_PRICE 19105
#define IDC_btnVIEW_GROUP               19110
#define IDC_edtOTHER_GROUP_NO_DIVIDE_ACQ_YEAR 19131
#define IDC_edtOTHER_GROUP_NO_DIVIDE    19132
#define IDC_edtOTHER_GROUP_NO_DIVIDE_CREATOR 19133
#define IDC_gridOTHER_GROUP_NO_DIVIDE   19134
#define IDC_btnOTHER_GROUP_NO_DIVIDE_PREV 19135
#define IDC_edtOTHER_GROUP_NOVIEW_ACQ_YEAR 19151
#define IDC_radOTHER_GROUP_NOVIEW_ALLDATA 19152
#define IDC_radOTHER_GROUP_NOVIEW_MYDATA 19153
#define IDC_btnOTHER_GROUP_NOVIEW_SEARCH 19154
#define IDC_gridOTHER_GROUP_NOVIEW_LIST 19155
#define IDC_btnOTHER_GROUP_NOVIEW_APPLY 19156
#define IDC_edtOTHER_GROUP_NO_LAST_SEARIAL_NO 19160
#define IDD_GROUP_SEARCH                5564
#define IDD_GROUP_MANAGER               5565
#define IDD_GROUP_INSERT                5566
#define IDD_VIEW_GROUP_DATA             5567
#define IDD_DIVISIONNO_LIST_DLG         5568
#define IDD_DIVISIONNO_MGR              5569
#define IDD_DIVISIONNO_INSERT           5570
#define IDD_DIVISIONNO_UPDATE           5571
#define IDD_DIVISIONNO_SELECT           5572
#define IDD_GROUP_DELETE                5573
#define IDD_GROUP_MERGE                 5574
#define IDD_REQUSITIONNO_INSERT         5575
#define IDD_REQUISITIONNO_MGR           5576
#define IDD_VIEW_REQUISITIONNO_DATA     5577
#define IDD_REQUISITIONNO_SELECT        5578
#define IDD_GROUP_SELECT                5579
#define IDD_VIEW_DIVISIONNO_DATA        5580
#define IDD_DIVISIONNO_STATUS_CHANGE_DLG 5581
#define IDD_DROP_GROUP_DLG              5582
#define IDD_DIVISIONNO_DIVIDE           5583
#define IDD_GROUP_DIVIDE                5584
#define IDD_REQUISITIONNO_DIVIDE        5585
#define IDD_MERGE_SELECT                5586
#define IDD_GROUP_LIST_DLG              5587
#define IDD_REQUISITIONNO_LIST_DLG      5588
#define IDD_CHANGE_SELECT               5589
#define IDD_CHECK_HOLD_DATA             5590
#define IDD_OTHER_GROUP_NO_SELECT       5591
#define IDD_OTHER_GROUP_NO_MGR          5592
#define IDD_OTHER_GROUP_NO_INSERT       5593
#define IDD_OTHER_GROUP_NO_DIVIDE       5594
#define IDD_OTHER_GROUP_LIST_DLG        5595
#define IDD_VIEW_OTHER_GROUP_NO_DATA    5596
#define IDD_ACQ_GROUP_SEARCH            5597
#define IDD_ACQ_PURCHASE_GROUP          5598
#define IDD_ACQ_DONATE_GROUP            5599
#define IDD_ACQ_OBJ_GROUP               5600
#define IDD_ACQ_OTHER_GROUP             5601
#define IDD_ACQ_GROUP_FORMVIEW          5602

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        20160
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         9227
#define _APS_NEXT_SYMED_VALUE           9000
#endif
#endif
