//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BO_SPECIES_FORM.rc
//
#define IDC_bSAVEAS                     3
#define IDC_ePRICE_OTHER_INFO           1011
#define IDC_eVOL                        1031
#define IDC_eEA_ISBN                    1080
#define IDC_eEA_ISBN_ADD                1083
#define IDC_cMEDIA_CLASS                1137
#define IDC_eREG_CLASS_CODE             1138
#define IDC_cREG_CLASS                  1138
#define IDC_cWORKING_STATUS             1139
#define IDC_ePUBLISH_PLACE              1203
#define IDC_ePUBLISHER                  1204
#define IDC_eTITLE                      1266
#define IDC_cMAT_CLASS                  1363
#define IDC_cPROVIDER                   1435
#define IDC_eSERIES_TITLE               1476
#define IDC_eTOTAL_VOLUMEP              1479
#define IDC_eTOTAL_BOOKP                1481
#define IDC_eEDITION_STMT               1516
#define IDC_cCURRENCY_CLASS             1527
#define IDC_eSET_ISBN                   1549
#define IDC_eSET_ISBN_ADD               1550
#define IDC_cSUBJECT                    1805
#define IDC_cCLASIFY_CLASS              1806
#define IDC_cSHELF_CODE                 1807
#define IDC_bDEFAULT_CONFIG             2001
#define IDC_eDISCRIPTION                2002
#define IDC_bSHOW_HIDE_CODE             2003
#define IDC_STATIC_CODE                 2004
#define IDC_STATIC_HEAD                 2005
#define IDC_STATIC_MARC                 2006
#define IDD_BO_ISBN_ADDITION            5631
#define IDC_STATIC_PURCHASE_GROUP       2007
#define IDC_tWORKING_STATUS             2008
#define IDD_BO_PURCHASE                 5632
#define IDC_tFORM_CLASS                 2010
#define IDC_tMAT_CLASS                  2011
#define IDD_BO_DONATE                   5633
#define IDC_tSUBJECT                    2012
#define IDD_BO_BASIC                    5634
#define IDC_tSUB_REG_CLASS              2013
#define IDC_tMEDIA_CLASS                2014
#define IDC_tUSE_OBJECT_CLASS           2015
#define IDC_tUSE_LIMIT_CLASS            2016
#define IDC_tSHELF_CODE                 2017
#define IDC_tCONTROL_MAT_CLASS          2018
#define IDC_tMANAGE_CLASS               2019
#define IDC_tCLASIFY_CLASS              2020
#define IDC_tWORK_CODE                  2021
#define IDC_tDISCRIPTION                2022
#define IDC_tTITLE                      2023
#define IDC_tREG_CLASS_CODE             2024
#define IDC_tAUTHOR1                    2025
#define IDC_tEDITION_STMT               2026
#define IDC_tVOL                        2028
#define IDC_tSERIES_TITLE               2030
#define IDC_tPUBLISH_PLACE              2031
#define IDC_tPUBLISHER                  2032
#define IDC_tPUBLISH_YEAR               2033
#define IDC_eAPPLICANT                  2036
#define IDC_bAPPENDIX_INFO              2037
#define IDC_bCLEARSCREEN                2038
#define IDC_bISBN_CHECK                 2039
#define IDC_STATIC_ISBN                 2040
#define IDC_bAPPLY_SERIES               2041
#define IDC_bINSERT_APPENDIX            2042
#define IDC_STATIC_BOOK_REGCODE         2042
#define IDC_bSAVE_APPENDIX              2043
#define IDC_STATIC_ISBN2                2043
#define IDC_bDELETE_APPENDIX            2044
#define IDC_TAB_VOLUME_BOOK             2045
#define IDC_STATIC_GRID                 2046
#define IDC_cSHELF_LOC_CODE             2048
#define IDC_bVIEW_HOLD_INFO             2049
#define IDC_bAPPLY_MARC                 2050
#define IDC_bSELECT_REP_BOOK            2050
#define IDC_RICHEDIT_MARC               2052
#define IDC_STATIC_GROUP1               2054
#define IDC_STATIC_GROUP2               2055
#define IDC_tREG_NO                     2056
#define IDC_tVOLTITLE                   2057
#define IDC_tCOPY_CODE                  2058
#define IDC_tSHLEF_LOC_CODE             2059
#define IDC_tBOOK_COUNT                 2060
#define IDC_tPAGE_CNT                   2062
#define IDC_tPHYSICAL_PROPERTIES        2063
#define IDC_tSIZE                       2064
#define IDC_tAPPENDIX                   2065
#define IDC_cFORM_CLASS                 2066
#define IDC_tBOOK_PRICE                 2066
#define IDC_tPRICE_OTHRE_INFO           2067
#define IDC_tAPPLICANT                  2068
#define IDC_bINPUT_ISBN                 2072
#define IDC_bMODIFY_ISBN                2073
#define IDC_bDELETE_ISBN                2074
#define IDC_gISBN                       2076
#define IDC_bCLOSE_ISBN                 2077
#define IDC_eREG_NO_SHOW                2078
#define IDC_stcDONATOR                  2083
#define IDC_edtDONATOR                  2084
#define IDC_btnSEARCH_DONATOR           2085
#define IDC_stcNONDONATE_REASON         2086
#define IDC_edtNONDONATE_REASON         2087
#define IDC_cmbGROUP_NAME               2088
#define IDC_btnGROUP_INSERT             2089
#define IDC_edtACQ_YEAR                 2090
#define IDC_EDIT1                       2091
#define IDC_EDIT2                       2092
#define IDC_EDIT3                       2093
#define IDC_EDIT4                       2094
#define IDC_cUSE_OBJECT_CLASS           2774
#define IDC_cSUB_REG_CLASS              2775
#define IDC_cMANAGE_CLASS               2776
#define IDC_cUSE_LIMIT_CLASS            2777
#define IDC_cCONTROL_MAT_CLASS          2778
#define IDC_eEA_ISBN_MISTAKE            2877
#define IDC_eSET_ISBN_MISTAKE           2878
#define IDC_bMARC_EDIT                  3103
#define IDC_bVOL_INFO                   3169
#define IDC_bEXTRA_ISBN                 3303
#define IDC_bDUP_SEARCH                 3305
#define IDC_bMARC_IMPORT                3331
#define IDC_bKOLIS_NET                  3332
#define IDC_tEA_ISBN                    6001
#define IDC_tSET_ISBN                   6002
#define IDC_b505TAG                     6003
#define IDC_gBO_APPENDIX                6004
#define IDC_eREG_NO                     6005
#define IDC_eVOL_CODE                   6006
#define IDC_eAUTHOR                     12002
#define IDC_eAUTHOR1                    12005
#define IDC_eBOOK_CNT                   12006
#define IDC_ePAGE_CNT                   12007
#define IDC_eBOOK_PRICE                 12008
#define IDC_eVOLTITLE                   12009
#define IDC_ePUBLISH_YEAR               12010
#define IDC_ePRICE                      12013
#define IDC_eISBN2                      12013
#define IDC_eOrderPRICE                 12014
#define IDC_eISBN3                      12014
#define IDC_ePHYSICAL_PROPERTIES        12015
#define IDC_eSIZE                       12016
#define IDC_ePRICE_DC                   12017
#define IDC_eAPPENDIX                   12017
#define IDC_ePRICE_OTHRE_INFO           12018
#define IDC_eCOPY_CODE                  12019
#define IDC_GRID_VOLUME                 12029
#define IDC_bISBN_INSERT                12030
#define IDC_GRID_BOOK                   12031
#define IDC_GRID_VOLUME_HOLD            12032
#define IDC_bPREV_SPECIES               12032
#define IDC_GRID_BOOK_HOLD              12033
#define IDC_cPRICE_TYPE                 13001
#define IDC_bNEXT_SPECIES               15008
#define IDC_bINSERT                     15009
#define IDC_bDELETE                     15011
#define IDC_tPURCHASE                   18000
#define IDC_tCURRENCY_CLASS             18001
#define IDC_tPRICE                      18002
#define IDC_tPRICE_REAL                 18003
#define IDC_tPRICE_JOB                  18004
#define IDC_tPRICE_TYPE                 18005
#define IDC_tPRICE_DC                   18010
#define IDC_tTOTAL_VOLUMEP              18013
#define IDC_tTOTAL_BOOKP                18014
#define IDC_bSAVE                       18015
#define IDC_bCLOSE                      18016
#define IDC_cWORK_CODE                  18027
#define IDD_BO_SPECIES                  5635
#define IDD_BO_APPENDIX                 5636
#define IDD_BO_VOLUME                   5637
#define IDD_BO_MARC_EDIT                5638
#define IDD_BO_GROUP_INFO               5639
#define IDD_BO_DIVISONNO_INFO           5640

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2013
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2095
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
