//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AccessControl.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ACCESSCONTROL_FORM          101
#define IDR_MAINFRAME                   128
#define IDR_ACCESSTYPE                  129
#define IDD_ACCESSCONTROL_WORK_FORM     130
#define IDD_WORK_TOOLBAR                132
#define IDD_USER                        133
#define IDD_NEW_MENU_GROUP              134
#define IDD_MENU_INSERT                 135
#define IDD_TOOLBAR_INSERT              136
#define IDD_NEW_METHOD                  137
#define IDD_DELETE_METHOD               138
#define IDB_CANCEL_F                    138
#define IDD_DELETE_USER                 139
#define IDB_CANCEL_D                    139
#define IDD_CHANGE_METHOD               140
#define IDB_CANCEL_U                    140
#define IDB_OK_U                        141
#define IDD_NEW_TOOL_GROUP              141
#define IDB_OK_F                        142
#define IDD_SELECTION_LIST              142
#define IDB_OK_D                        143
#define IDD_SELECTION_MENU_LIST         143
#define IDB_INSERT_U                    144
#define IDD_SELECTION_MENU_MODIFY       144
#define IDB_INSERT_F                    145
#define IDD_SMARTID_MENU_LIST           145
#define IDB_INSERT_D                    146
#define IDD_SMARTID_MENU_LIST_INSERT    146
#define IDB_UPDATE_D                    147
#define IDD_SMARTID_MENU_LIST_MODIFY    147
#define IDB_UPDATE_F                    148
#define IDB_UPDATE_U                    149
#define IDB_DELETE_U                    150
#define IDB_DELETE_F                    151
#define IDB_DELETE_D                    152
#define IDB_CLOSE_D                     153
#define IDB_CLOSE_F                     154
#define IDB_CLOSE_U                     155
#define IDI_ICON01                      157
#define IDI_ICON02                      158
#define IDI_ICON03                      159
#define IDI_ICON04                      160
#define IDI_ICON05                      161
#define IDI_ICON06                      162
#define IDI_ICON07                      163
#define IDI_ICON08                      164
#define IDI_ICON09                      165
#define IDI_ICON10                      166
#define IDC_tMENU                       1000
#define IDC_STATIC1                     1001
#define IDC_STATIC3                     1003
#define IDC_STATIC4                     1004
#define IDC_bOK                         1005
#define IDC_STATIC5                     1005
#define IDC_bCANCEL                     1006
#define IDC_STATIC6                     1006
#define IDC_lUSER                       1007
#define IDC_STATIC7                     1007
#define IDC_eNAME                       1008
#define IDC_STATIC8                     1008
#define IDC_STATIC9                     1009
#define IDC_ckGROUPTYPE                 1009
#define IDC_STATIC10                    1010
#define IDC_STATIC2                     1011
#define IDC_gMENU                       1012
#define IDC_STATIC11                    1012
#define IDC_MSHFLEXGRID1                1013
#define IDC_bINSERT                     1014
#define IDC_bMODIFY                     1015
#define IDC_bDELETE                     1016
#define IDC_bTOOLBAR                    1017
#define IDC_MSHFLEXGRID2                1018
#define IDC_bGropuINSERT                1019
#define IDC_eALIAS                      1020
#define IDC_bGroupMODIFY                1020
#define IDC_eIDX                        1021
#define IDC_bGroupDELETE                1021
#define IDC_eCAPTION                    1022
#define IDC_STATIC_BACK                 1024
#define IDC_bPREVIEW                    1025
#define IDC_eTARGET                     1026
#define IDC_bCLOSE                      1026
#define IDC_eTITLE                      1027
#define IDC_COM_STATIC9                 1030
#define IDC_eNORMAL                     1031
#define IDC_eHOT                        1032
#define IDC_COM_STATIC10                1033
#define IDC_eDISABLED                   1034
#define IDC_COM_STATIC11                1034
#define IDC_TOOLTIP                     1035
#define IDC_eSM                         1042
#define IDC_bTYPECLEAR                  1043
#define IDC_cMETHOD                     1044
#define IDC_lMETHOD                     1045
#define IDC_GroupDesc                   1047
#define IDC_GroupAlias                  1048
#define IDC_GroupAlign                  1055
#define IDC_STATIC_CAPTION              1055
#define IDC_gLIST                       1060
#define IDC_bREARRANGE                  1063
#define IDC_cACC_SYSKEY                 1065
#define IDC_cACC_KEY                    1066
#define IDC_bSMARTIDINSERT              1066
#define IDC_bSMARTIDDELETE              1067
#define IDC_bSMARTIDMODIFY              1067
#define IDC_bSMARTIDDELETE2             1068
#define IDC_COMBO1                      1070
#define IDC_cTOP_MENU_GROUP             1070
#define IDC_ACC_RADIO1                  1071
#define IDC_cWORKING_STATUS             1071
#define IDC_ACC_RADIO2                  1072
#define IDC_eTITLE_DESC                 1072
#define IDC_ACC_RADIO3                  1073
#define IDC_STATIC_WORKING_STATUS_DESC  1073
#define IDC_ACC_RADIO4                  1074
#define IDC_PROGRESS1                   1074
#define IDC_ACC_RADIO5                  1075
#define IDC_bREFRESH                    1075
#define IDC_ACC_RADIO6                  1076
#define IDC_STATIC_MSG01                1076
#define IDC_ACC_RADIO7                  1077
#define IDD_USER_DUPLICATE              4009
#define IDC_eSOURCENAME                 20005
#define IDC_STATIC_1                    20008
#define IDC_STATIC_2                    20009
#define IDC_STATIC_3                    20010
#define IDC_eTARGETNAME                 20011
#define IDC_STATIC_4                    20012
#define IDC_STATIC_101                  20015
#define IDC_STATIC_102                  20016
#define IDC_bCOPY                       20017
#define IDC_eDELETENAME                 20018
#define IDC_rSOURCE1                    32001
#define IDC_rSOURCE2                    32002
#define IDC_rSOURCE3                    32003
#define IDC_rTARGET1                    32004
#define IDC_rTARGET2                    32005
#define IDC_rTARGET3                    32006
#define IDC_rDELETE1                    32007
#define IDC_rDELETE2                    32008
#define IDC_rDELETE3                    32009
#define ID_MENU_GROUP_NEW               32771
#define ID_USER_NEW                     32772
#define ID_METHOD_NEW                   32773
#define ID_USER_METHOD                  32774
#define ID_USER_DELETE                  32775
#define ID_METHOD_DELETE                32776
#define ID_MENU_GROUP_DELETE            32777
#define ID_LOGIN_NEW                    32778
#define ID_MENU_GROUP_MODIFY            32779
#define ID_SMARTID_MENU_LIST            32780
#define ID_USER_DUPLICATE               32781
#define IDC_STATIC30                    65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
