//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BO_ACQ_SPECIES_FORM.rc
//
#define IDC_bSAVEAS                     3
#define IDC_eVOL                        1031
#define IDC_eEA_ISBN                    1080
#define IDC_eEA_ISBN_ADD                1083
#define IDC_cMEDIA_CLASS                1137
#define IDC_eREG_CLASS_CODE             1138
#define IDC_cREG_CLASS                  1138
#define IDC_ePUBLISH_PLACE              1203
#define IDC_ePUBLISHER                  1204
#define IDC_eTITLE                      1266
#define IDC_cMAT_CLASS                  1363
#define IDC_cmbBSFORM_PROVIDER          1435
#define IDC_eSERIES_TITLE               1476
#define IDC_eTOTAL_VOLUMEP              1479
#define IDC_eTOTAL_BOOKP                1481
#define IDC_eEDITION_STMT               1516
#define IDC_eSET_ISBN                   1549
#define IDC_eSET_ISBN_ADD               1550
#define IDC_cSUBJECT                    1805
#define IDC_cCLASIFY_CLASS              1806
#define IDC_cSHELF_CODE                 1807
#define IDC_bDEFAULT_CONFIG             2001
#define IDC_eDISCRIPTION                2002
#define IDC_btnBSFORM_SHOW_HIDE_CODE    2003
#define IDC_STATIC_CODE                 2004
#define IDC_STATIC_HEAD                 2005
#define IDC_STATIC_MARC                 2006
#define IDC_STATIC_PURCHASE_GROUP       2007
#define IDC_tWORKING_STATUS             2008
#define IDC_tFORM_CLASS                 2010
#define IDC_tMAT_CLASS                  2011
#define IDC_tSUBJECT                    2012
#define IDC_tSUB_REG_CLASS              2013
#define IDC_tMEDIA_CLASS                2014
#define IDC_tUSE_OBJECT_CLASS           2015
#define IDC_tUSE_LIMIT_CLASS            2016
#define IDC_tSHELF_CODE                 2017
#define IDC_tCONTROL_MAT_CLASS          2018
#define IDC_tMANAGE_CLASS               2019
#define IDC_tCLASIFY_CLASS              2020
#define IDC_tWORK_CODE                  2021
#define IDC_tDISCRIPTION                2022
#define IDC_tTITLE                      2023
#define IDC_tREG_CLASS_CODE             2024
#define IDC_tAUTHOR1                    2025
#define IDC_tEDITION_STMT               2026
#define IDC_tClass_Kind                 2027
#define IDC_tVOL                        2028
#define IDC_tSERIES_TITLE               2030
#define IDC_tPUBLISH_PLACE              2031
#define IDC_tPUBLISHER                  2032
#define IDC_tPUBLISH_YEAR               2033
#define IDC_STATIC_EBOOK_GROUP          2034
#define IDC_bCLEARSCREEN                2038
#define IDC_bISBN_CHECK                 2039
#define IDC_bSPECIES_COPY               2039
#define IDC_STATIC_ISBN                 2040
#define IDC_bAPPLY_SERIES               2041
#define IDC_STATIC_BOOK_REGCODE         2042
#define IDC_bINSERT_APPENDIX            2042
#define IDC_bSAVE_APPENDIX              2043
#define IDC_STATIC_FORM_ELEMENT         2043
#define IDC_bDELETE_APPENDIX            2044
#define IDC_bAPPLY_MARC                 2050
#define IDC_RICHEDIT_MARC               2052
#define IDC_cFORM_CLASS                 2066
#define IDC_cAPPLICAND_KIND_DEPT        2067
#define IDC_cAPPLICAND_KIND_COURCE      2068
#define IDC_cAPPLICAND_KIND_CLASS       2069
#define IDC_btnEBOOK_VIEW               2080
#define IDC_btnFIND_FILE1               2081
#define IDC_btnFIND_FILE2               2082
#define IDC_stcDONATOR                  2083
#define IDC_edtBSFORM_DONATOR           2084
#define IDC_btnBSFORM_SEARCH_DONATOR    2085
#define IDC_stcBSFORM_NONDONATE_REASON  2086
#define IDC_edtBSFORM_NONDONATE_REASON  2087
#define IDC_btnFIND_FILE3               2088
#define IDC_stcBSFORM_DONATE_DATE       2088
#define IDC_stcEBOOK_COVER_FILE         2089
#define IDC_edtBSFORM_DONATE_DATE       2089
#define IDC_edtEBOOK_COVER_FILE         2090
#define IDC_btnBSFORM_BEFORE_DONATOR    2090
#define IDC_edtPAGE                     2091
#define IDC_edtPHYSICAL_CHARACTER       2092
#define IDC_edtSIZE                     2093
#define IDC_edtAPPENDIX                 2094
#define IDC_stcEBOOK_FILE               2095
#define IDC_stcEBOOK_EXECUTE_FILE       2096
#define IDC_edtEBOOK_FILE               2097
#define IDC_edtEBOOK_EXECUTE_FILE       2098
#define IDC_cUSE_OBJECT_CLASS           2774
#define IDC_cSUB_REG_CLASS              2775
#define IDC_cMANAGE_CLASS               2776
#define IDC_cUSE_LIMIT_CLASS            2777
#define IDC_cCONTROL_MAT_CLASS          2778
#define IDC_eEA_ISBN_MISTAKE            2877
#define IDC_eSET_ISBN_MISTAKE           2878
#define IDC_bMARC_EDIT                  3103
#define IDC_bVOL_INFO                   3169
#define IDC_bEXTRA_ISBN                 3303
#define IDC_bDUP_SEARCH                 3305
#define IDC_bMARC_IMPORT                3331
#define IDC_bKOLIS_NET                  3332
#define IDC_HOUR                        5001
#define IDC_MIN                         5002
#define IDC_SEC                         5003
#define IDC_tEA_ISBN                    6001
#define IDC_tSET_ISBN                   6002
#define IDC_gBO_APPENDIX                6004
#define IDC_eVOL_CODE                   6006
#define IDC_chkPRIORITY_CATALOG         10970
#define IDC_tPRIORITY_CATALOG           10971
#define IDC_stcUSERCODE1                10974
#define IDC_cmbUSERCODE1                10975
#define IDC_stcUSERCODE2                10976
#define IDC_cmbUSERCODE2                10977
#define IDC_stcUSERCODE3                10978
#define IDC_cmbUSERCODE3                10979
#define IDC_eDISCRIPTION_SMALL          10999
#define IDC_btnSearchUser               11206
#define IDC_eAUTHOR1                    12005
#define IDC_eAPPENDIX_TITLE             12009
#define IDC_ePUBLISH_YEAR               12010
#define IDC_edtBSFORM_ORDER_PRICE       12014
#define IDC_edtBSFORM_PRICE_DC          12017
#define IDC_eCOPY_CODE                  12019
#define IDC_bPREV_SPECIES               12032
#define IDC_btnEXCHANGE_RATE            12406
#define IDC_edtEXCHANGE_RATE            12407
#define IDC_cmbBSFORM_PRICE_TYPE        13001
#define IDC_edtACCNO_YEAR               14008
#define IDC_edtACCNO_MAKER              14009
#define IDC_btnACCNO_SEARCH             14010
#define IDC_gridACCNO_INFO              14011
#define IDC_bNEXT_SPECIES               15008
#define IDC_cmbBSDIVNO_WORK_NO          17000
#define IDC_cmbBSDIVNO_ACQ_CODE         17001
#define IDC_edtBSDIVNO_ACQ_YEAR         17002
#define IDC_cmbBSDIVNO_GROUP_NO         17003
#define IDC_btnBSDIVNO_CREATE           17004
#define IDC_strBSFORM_GROUP_NO          17005
#define IDC_strBSFORM_WORK_NO           17006
#define IDC_edtBSFORM_CREATE_YEAR       17007
#define IDC_cmbBSFORM_GROUP_NAME        17008
#define IDC_btnBSFORM_GROUP_INSERT      17009
#define IDC_edtBSFORM_PRICE             17010
#define IDC_cmbBSFORM_CURRENCY_CLASS    17011
#define IDC_edtBSFORM_PRICE_OTHER_INFO  17012
#define IDC_tPAGE                       17013
#define IDC_tPHYSICAL_CHARACTER         17014
#define IDC_stcSIZE                     17015
#define IDC_stcAPPENDIX                 17016
#define IDC_bAPPENDIX                   17017
#define IDC_edtWORKING_STATUS           17018
#define IDC_radREG_YES                  17020
#define IDC_radREG_NO                   17021
#define IDC_stcGROUP_NAME               17022
#define IDC_stcGROUP_CREATE_YEAR        17023
#define IDC_cmbBSGROUP_ACQ_CODE         17024
#define IDC_edtBSFORM_PRICE_CHARACTER   17030
#define IDC_edtBSFORM_REQUESTOR         17032
#define IDC_edtBSFORM_REQUEST_DATE      17033
#define IDC_stcBSFORM_REQUESTOR         17034
#define IDC_stcBSFORM_REQUEST_DATE      17035
#define IDC_edtAPPENDIX_REG_NO          17036
#define IDC_stcAPPENDIX_REG_NO          17037
#define IDC_btnPREV_CONTENT             17038
#define IDC_cmbMANAGE_CODE              17039
#define IDC_btnSET_ACCESSION_REC_NO     17040
#define IDC_cmbACQ_CODE                 17041
#define IDC_edtREG_NO1                  17044
#define IDC_edtREG_NO2                  17045
#define IDC_edtBOOK_CODE                17046
#define IDC_edtAUTHOR                   17047
#define IDC_edtVOL                      17048
#define IDC_edtPUB_YEAR                 17049
#define IDC_edtVOL_SORT_NO              17050
#define IDC_tPURCHASE                   18000
#define IDC_tCURRENCY_CLASS             18001
#define IDC_tPRICE                      18002
#define IDC_tPRICE_REAL                 18003
#define IDC_tPRICE_JOB                  18004
#define IDC_tPRICE_TYPE                 18005
#define IDC_tPRICE_DC                   18010
#define IDC_tTOTAL_VOLUMEP              18013
#define IDC_tTOTAL_BOOKP                18014
#define IDC_tClass_Code                 18015
#define IDC_cWORK_CODE                  18027
#define IDC_edtSERIES_VOL               18028
#define IDC_tSERIES_VOL                 18029
#define IDC_bSAVE                       18050
#define IDC_bCLOSE                      18051
#define IDD_BO_PURCHASE                 5605
#define IDD_BO_DONATE                   5606
#define IDD_BO_BASIC                    5607
#define IDD_BO_SPECIES                  5608
#define IDD_BO_APPENDIX                 5609
#define IDD_BO_MARC_EDIT                5610
#define IDD_BO_GROUP_INFO               5611
#define IDD_BO_DIVISONNO_INFO           5612
#define IDD_BO_REQUSITINNO_INFO         5613
#define IDD_ACCESSION_REC_NO_SEARCH     5614
#define IDD_BO_LIGHT_DIVISONNO_INFO     5615
#define IDD_USER_DEFINE_CODE_INFO       5616
#define IDC_btnCover                    27059
#define IDC_APPLICAND_KIND              27064
#define IDC_cmbAPPLICANT                27065
#define IDC_cmbBSFORM_PRICE_CHARACTER   27066
#define IDC_edtBSFORM_REQUEST_HOUR      27066

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        27011
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         27067
#define _APS_NEXT_SYMED_VALUE           27000
#endif
#endif
