//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BO_ACQ_DONATE_STATISTICS.rc
//
#define IDC_edtPURCHASE_STATISTICS      10001
#define IDC_edtDONATE_STATISTICS        10001
#define IDC_stcPURCHASE_STATISTICS      10002
#define IDC_stcDONATE_STATISTICS        10002
#define IDC_stcPURCHASE_STATISTICS_DATA 11010
#define IDC_stcDONATE_STATISTICS_DATA   11010
#define IDC_edtSTATISTICS_CONDITION     12000
#define IDC_edtDONATE_STATISTICS_CONDITION 12000
#define IDC_stcPURCHASE_STATISTICS_CONDITION 12001
#define IDC_stcDONATE_STATISTICS_CONDITION 12001
#define IDC_stcDONATE_STATISTICS_UNIT   12002
#define IDC_edtPURCHASE_STATISTICS_YEAR 18016
#define IDC_edtDONATE_STATISTICS_YEAR   18016
#define IDC_stcPURCHASE_STATISTICS_YEAR 18017
#define IDC_stcDONATE_STATISTICS_YEAR   18017
#define IDC_gridSTATISTICS_DATA         19000
#define IDC_gridPURCHASE_STATISTICS_DATA 19000
#define IDC_gridDONATE_STATISTICS_DATA  19000
#define IDD_BO_ACQ_DONATE_STATISTICS_MGR 8443
#define IDD_BO_ACQ_DONATE_STATISTICS    8444

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        13000
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         13000
#define _APS_NEXT_SYMED_VALUE           13000
#endif
#endif
