//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ECOMath.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MATHTYPE                    129
#define IDD_DIALOGBAR                   5881
#define IDR_BIREL_MENU                  131
#define IDB_VERTBMP                     132
#define IDR_GREEK_MENU                  134
#define IDR_UPGREEK_MENU                135
#define IDR_HEBREW_MENU                 136
#define IDR_BIOP_MENU                   137
#define IDR_ARROW_MENU                  138
#define IDR_LOGICAL_MENU                139
#define IDR_SET_MENU                    140
#define IDR_MISC_MENU                   141
#define IDR_FENCE_TEMPLATE_MENU         142
#define IDR_FRACTION_MENU               147
#define IDR_RADICAL_MENU                148
#define IDR_SCRIPT_MENU                 149
#define IDR_SUMMATION_MENU              150
#define IDR_INTEGRAL_MENU               151
#define IDR_BAR_MENU                    152
#define IDR_LABELEDARROW_MENU           153
#define IDR_PRODUCT_MENU                154
#define IDR_SETTHEORY_MENU              156
#define IDB_CARET                       157
#define UPGREEKD                        158
#define ARROWSD                         159
#define BARU                            160
#define BARD                            161
#define FENCEU                          162
#define FENCED                          163
#define FRACTIONU                       164
#define FRACTIOND                       165
#define GREEKU                          166
#define GREEKD                          167
#define INTEGRALU                       168
#define INTEGRALD                       169
#define LABELEDU                        170
#define LABELEDD                        171
#define LOGICALU                        172
#define LOGICALD                        173
#define MISCU                           174
#define ARROWSU                         175
#define MISCD                           176
#define UPGREEKU                        178
#define RELATIOND                       179
#define RELATIONU                       180
#define OPERATORU                       181
#define OPERATORD                       182
#define SETD                            183
#define SETU                            184
#define RADICALD                        185
#define RADICALU                        186
#define SCRIPTD                         187
#define SCRIPTU                         188
#define SUMD                            189
#define SUMU                            190
#define IDB_RELATION                    191
#define IDB_BITMAP1                     192
#define IDC_BIREL_BTN                   1000
#define IDC_GREEK_BTN                   1001
#define IDC_UPGREEK_BTN                 1002
#define IDC_HEBREW_BTN                  1003
#define IDC_ARROW_BTN                   1004
#define IDC_OP_BTN                      1005
#define IDC_LOGICAL_BTN                 1006
#define IDC_SET_BTN                     1007
#define IDC_MISC_BTN                    1008
#define IDC_FENCE_TEMP_BTN              1009
#define IDC_FRACTION_BTN                1010
#define IDC_RADICAL_BTN                 1011
#define IDC_SCRIPT_BTN                  1012
#define IDC_SUMMATION_BTN               1013
#define IDC_PRODUCT_BTN                 1017
#define IDC_MATRIX_BTN                  1019
#define IDC_INTEGRAL_BTN                1020
#define IDC_BAR_BTN                     1021
#define IDC_SETTHEORY_BTN               1023
#define IDC_SEND2TOC                    1025
#define ID_GT                           32774
#define ID_LT                           32775
#define ID_EQ                           32776
#define ID_LE                           32778
#define ID_PREC                         32780
#define ID_GE                           32785
#define ID_SUCC                         32787
#define ID_EQUIV                        32792
#define ID_ALPHA                        32812
#define ID_BETA                         32813
#define ID_GAMMA                        32814
#define ID_DELTA                        32815
#define ID_EPSILON                      32816
#define ID_ZETA                         32817
#define ID_ETA                          32818
#define ID_THETA                        32819
#define ID_IOTA                         32820
#define ID_KAPPA                        32821
#define ID_LAMBDA                       32822
#define ID_MU                           32823
#define ID_NU                           32824
#define ID_XI                           32825
#define ID_PI                           32826
#define ID_RHO                          32827
#define ID_SIGMA                        32828
#define ID_TAU                          32829
#define ID_UPSILON                      32830
#define ID_PHI                          32831
#define ID_CHI                          32832
#define ID_PSI                          32833
#define ID_OMEGA                        32834
#define ID_VAREPSILON                   32835
#define ID_VARPI                        32836
#define ID_VARSIGMA                     32837
#define ID_VARTHETA                     32838
#define ID_VARRHO                       32839
#define ID_VARPHI                       32840
#define ID_DIGAMMA                      32841
#define ID_VARKAPPA                     32842
#define ID_VARGAMMA                     32843
#define ID_VARDELTA                     32844
#define ID_VARLAMBDA                    32845
#define ID_VARXI                        32846
#define ID_VARUPSILON                   32847
#define ID_VARPSI                       32848
#define ID_VAROMEGA                     32849
#define ID_DALETH                       32853
#define ID_GIMEL                        32854
#define ID_PLUS                         32855
#define ID_PM                           32856
#define ID_TIMES                        32857
#define ID_CIRC                         32858
#define ID_OPLUS                        32864
#define ID_OTIMES                       32865
#define ID_AST                          32870
#define ID_MINUS                        32872
#define ID_MP                           32873
#define ID_CDOTS                        32874
#define ID_DIV                          32877
#define ID_TRIANGLERIGHT                32881
#define ID_BULLET                       32885
#define ID_LEFTARROW                    32890
#define ID_RIGHTARROW                   32891
#define ID_LLEFTARROW                   32894
#define ID_LEFTRIGHTARROW               32896
#define ID_LLEFTRIGHTARROW              32897
#define ID_UPARROW                      32898
#define ID_UUPARROW                     32899
#define ID_UPDOWNARROW                  32900
#define ID_MAPSTO                       32904
#define ID_RRIGHTARROW                  32908
#define ID_DOWNARROW                    32912
#define ID_DDOWNARROW                   32913
#define ID_UUPDOWNARROW                 32914
#define ID_TRIANGLELEFT                 32923
#define ID_NE                           32925
#define ID_APPROX                       32927
#define ID_CONG                         32928
#define ID_PROPTO                       32929
#define ID_LANGLE                       32930
#define ID_RANGLE                       32931
#define ID_THEREFORE                    32932
#define ID_BECAUSE                      32933
#define ID_EXISTS                       32934
#define ID_FORALL                       32935
#define ID_NEG                          32936
#define ID_EDGE                         32937
#define ID_VEE                          32938
#define ID_IN                           32939
#define ID_OWNS                         32940
#define ID_CUP                          32941
#define ID_CAP                          32942
#define ID_SUBSET                       32943
#define ID_SUPSET                       32944
#define ID_SUBSETEQ                     32945
#define ID_SUPSETEQ                     32946
#define ID_NOTSUBSET                    32947
#define ID_EMPTYSET                     32948
#define ID_PARTIAL                      32949
#define ID_NABLA                        32950
#define ID_IM                           32951
#define ID_RE                           32952
#define ID_ALEPH                        32953
#define ID_ANGLE                        32954
#define ID_BOT                          32955
#define ID_DIAMONDSUIT                  32956
#define ID_ELL                          32957
#define ID_WP                           32958
#define ID_UPCIRC                       32959
#define ID_HBAR                         32960
#define ID_SMALLINT                     32961
#define ID_SUM                          32962
#define ID_PROD                         32963
#define ID_COPROD                       32964
#define ID_ROUND_BRACKET                32967
#define ID_SQUARE_BRACKET               32968
#define ID_CURLY_BRACKET                32969
#define ID_ANGLE_BRACKET                32970
#define ID_SINGLE_VERTICAL_BAR          32971
#define ID_DOUBLE_VERTICAL_BAR          32972
#define ID_FLOOR_BRACKET                32973
#define ID_CEILING_BRACKET              32974
#define ID_UPPER_HORIZENTAL_BRACE       32975
#define ID_LOWER_HORIZENTAL_BRACE       32976
#define ID_LEFT_PARENTHESIS             32977
#define ID_RIGHT_PARENTHESIS            32978
#define ID_LEFT_BRACKET                 32979
#define ID_RIGHT_BRACKET                32980
#define ID_LEFT_BRACE                   32981
#define ID_RIGHT_BRACE                  32982
#define ID_LEFT_ANGLE_BRACKET           32983
#define ID_RIGHT_ANGLE_BRACKET          32984
#define ID_LEFT_VERTICAL_BAR            32985
#define ID_RIGHT_VERTICAL_BAR           32986
#define ID_LEFT_DOUBLE_BAR              32987
#define ID_RIGHT_DOUBLE_BAR             32988
#define ID_FRACTION                     32989
#define ID_DIAGONAL_FRACTION            32990
#define ID_SLASH_FRACTION               32991
#define ID_SQUARD_ROOT                  32992
#define ID_NTH_ROOT                     32993
#define ID_LONG_DIVISION                32994
#define ID_SUPERSCRIPT                  32995
#define ID_SUBSCRIPT                    32996
#define ID_SUPER_SUBSCRIPT              32997
#define ID_LEFT_SUPERSCRIPT             32998
#define ID_LEFT_SUBSCRIPT               32999
#define ID_LEFT_SUPER_SUBSCRIPT         33000
#define ID_OVER_SCRIPT                  33001
#define ID_UNDER_SCRIPT                 33002
#define ID_OVER_UNDER_SCRIPT            33003
#define ID_SUM_NOLIMIT                  33004
#define ID_SUM_UNDERSCRIPTLIMIT         33005
#define ID_SUM_UNDER                    33006
#define ID_SUM_UNDEROVER                33007
#define ID_SUM_SUB                      33008
#define ID_SUM_SUBSUPER                 33009
#define ID_INDEFINITE_INTEGRAL          33011
#define ID_INTEGRAL_OVERUNDER           33012
#define ID_INTEGRAL_SUBSUPER            33013
#define ID_OVER_BAR                     33021
#define ID_UNDER_BAR                    33023
#define ID_RIGHTOVER_BAR                33025
#define ID_LEFTOVER_BAR                 33026
#define ID_RIGHTUNVER_BAR               33028
#define ID_LEFTUNDER_BAR                33029
#define ID_RIGHT_UPPER                  33031
#define ID_LEFT_UPPER                   33032
#define ID_DOUBLEHEAD_UPPER             33033
#define ID_RIGHT_LOWER                  33034
#define ID_LEFT_LOWER                   33035
#define ID_DOUBLEHEAD_LOWER             33036
#define ID_PRODUCT_NOLIMIT              33037
#define ID_PRODUCT_UNDER                33038
#define ID_PRODUCT_UNDEROVER            33039
#define ID_PRODUCT_SUB                  33040
#define ID_PRODUCT_SUBSUPER             33041
#define ID_COPRODUCT_NOLIMIT            33042
#define ID_COPRODUCT_UNDER              33043
#define ID_COPRODUCT_UNDEROVER          33044
#define ID_COPRODUCT_SUB                33045
#define ID_COPRODUCT_SUBSUPER           33046
#define ID_SETTHEORY_NOLIMIT            33047
#define ID_SETTHEORY_UNDER              33048
#define ID_SETTHEORY_UNDEROVER          33049
#define ID_SETTHEORY_SUB                33050
#define ID_SETTHEORY_SUBSUPER           33051
#define ID_UNION_NOLIMIT                33052
#define ID_UNION_UNDER                  33053
#define ID_UNION_UNDEROVER              33054
#define ID_UNION_SUB                    33055
#define ID_UNION_SUBSUPER               33056
#define ID_HE_ALPHA                     33057
#define ID_HE_BETA                      33058
#define ID_OMICRON                      33059
#define ID_UPGAMMA                      33060
#define ID_UPDELTA                      33061
#define ID_UPTHETA                      33062
#define ID_UPLAMBDA                     33063
#define ID_UPXI                         33064
#define ID_UPPI                         33065
#define ID_UPSIGMA                      33066
#define ID_UPUPSILON                    33067
#define ID_UPPHI                        33068
#define ID_UPPSI                        33069
#define ID_UPOMEGA                      33070
#define ID_SEND_SOOSIK                  33072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         33073
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
