//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CAT_FIXED_FIELD.rc
//
#define IDC_sSTATIC2                    1063
#define IDC_sSTATIC1                    1064
#define IDC_cLITERATURE2                1065
#define IDC_STATIC_BCPF                 1066
#define IDC_cDATA_TYPE1                 1087
#define IDC_cDATA_TYPE2                 1088
#define IDC_cTHESIS                     1091
#define IDC_cTHESIS2                    1092
#define IDC_cTHESIS3                    1093
#define IDC_cUNIVERCITY_CODE            1111
#define IDC_cLIST_JUNGEO                1146
#define IDC_cLITERATURE                 1150
#define IDC_eILLUST                     1151
#define IDC_cPUBLICATE_COUNTRY          1192
#define IDC_ePUBLICATE_YEAR             1194
#define IDC_ePUBLICATE_YEAR_SEL         1195
#define IDC_eDate                       1204
#define IDC_cSTATUS                     1261
#define IDC_cINDEX                      1265
#define IDC_cSEOJI                      1273
#define IDC_cUPDATE                     1285
#define IDC_cLANG                       1312
#define IDC_cSTYLE                      1332
#define IDC_cUSE                        1336
#define IDC_cBINDO                      1337
#define IDC_cINPUT_LEVEL                1358
#define IDC_cINPUT_LEVEL2               1359
#define IDC_cDISCERN                    1368
#define IDC_cDISCERN2                   1369
#define IDC_cDISCERN3                   1370
#define IDC_cDISCERN4                   1371
#define IDC_cDISCERN5                   1372
#define IDC_cJUNGEO                     1405
#define IDC_cGOVERNMENT                 1430
#define IDC_cFORM                       1526
#define IDC_cCONFERENCE                 1534
#define IDC_eINPUT_DATE                 1680
#define IDC_cUSER_LEVEL1                2008
#define IDC_cSTANDARD                   2092
#define IDC_cXXCONSUMR_RANGE            2093
#define IDC_cUSER_LEVEL                 2095
#define IDC_cFILE_FORM                  2096
#define IDC_cDRAWING                    2098
#define IDC_cPRIME_MERIAIAN             2099
#define IDC_cMP_FROM                    2100
#define IDC_cMP_INDEX                   2101
#define IDC_cMUSIC_FORM                 2103
#define IDC_cMUSIC_SHEET_FORM           2104
#define IDC_cMAT_FORM                   2105
#define IDC_cMUSIC_CONTENTS             2107
#define IDC_cUSE_OBJ_LEVEL              2109
#define IDC_cMETERIAL_TYPE              2110
#define IDC_cTECH_LEVEL                 2111
#define IDC_eMAT_CATEGORY               2112
#define IDC_cMAT_DISCRIM                2113
#define IDC_cORIGINAL_LEVEL             2114
#define IDC_cCOLOR                      2115
#define IDC_cPHYSICAL_MAT               2116
#define IDC_cMAT_CATEGORY               2117
#define IDC_cCOPY_FORM                  2118
#define IDC_cEXPOSURE_MAT               2119
#define IDC_cMUSIC_MAT                  2120
#define IDC_cFIRM_LENGTH                2121
#define IDC_cCREAT_PROCESS              2122
#define IDC_cFIRM_MAT                   2123
#define IDC_cSCREEN_FORM                2124
#define IDC_cBASIC_MAT                  2125
#define IDC_cCOPY_CONTENTS              2126
#define IDC_cEXPOSURE_LEVEL             2127
#define IDC_cFORMULA_MAT                2128
#define IDC_cSTATUS2                    2129
#define IDC_cMAKE_ELEMENT               2130
#define IDC_cMAKE_LEVEL                 2131
#define IDC_cCOLOR_CATEGORY             2132
#define IDC_cCOLOR_TYPE                 2133
#define IDC_cCHANGE_LEVEL               2134
#define IDC_cCOMPLETENESS               2135
#define IDC_cPLAY_LEVEL                 2137
#define IDC_cSPEED                      2138
#define IDC_cSOUND_LENGTH               2139
#define IDC_cSIZE                       2140
#define IDC_cTAPE_WIDTH                 2141
#define IDC_cTAPE_FORMULA               2142
#define IDC_cTAPE_KIND                  2143
#define IDC_cMATERIAL                   2144
#define IDC_cEDIT_TYPE                  2145
#define IDC_cRECORD_MATHOD              2146
#define IDC_cTRECORD_MATHOD             2147
#define IDC_cVIDEO_FORM                 2178
#define IDC_cFORM2                      2179
#define IDC_cFORM_MARK1                 2359
#define IDC_cFORM_MARK2                 2360
#define IDC_cACCOMP_MAT1                2361
#define IDC_cACCOMP_MAT2                2362
#define IDC_cACCOMP_MAT3                2363
#define IDC_cMUSIC_CONTENTS1            2364
#define IDC_cMUSIC_CONTENTS2            2365
#define IDC_eRUNNING_TIME               2366
#define IDC_eFIRM_DATE                  2367
#define IDC_eXXCONSUME                  2368
#define IDC_eILLUST1                    2386
#define IDC_eILLUST2                    2387
#define IDC_eILLUST3                    2388
#define IDC_eILLUST4                    2389
#define IDC_eMODEL_MAP1                 2394
#define IDC_eMODEL_MAP2                 2395
#define IDC_eMODEL_MAP3                 2396
#define IDC_eMODEL_MAP4                 2397
#define IDC_cNOMAL                      3000
#define IDC_cISSN                       3001
#define IDC_cSE_STYLE                   3002
#define IDC_cTITLE_LAN                  3003
#define IDC_cTITLT_GISUL                3004
#define IDC_cFORMAT                     3005
#define IDC_cMON_FORMAT                 3006
#define IDD_FIXED_008_AC                5648
#define IDC_b007EDIT                    3216
#define IDD_FIXED_007_Z                 5649
#define IDD_FIXED_007_C                 5650
#define IDD_FIXED_007_O                 5651
#define IDD_FIXED_007_CONTAINER         5652
#define IDD_FIXED_007_D                 5653
#define IDD_FIXED_007_G                 5654
#define IDD_FIXED_007_H                 5655
#define IDD_FIXED_007_K                 5656
#define IDD_FIXED_007_M                 5657
#define IDD_FIXED_007_S                 5658
#define IDD_FIXED_007_T                 5659
#define IDD_FIXED_007_V                 5660
#define IDD_FIXED_008_MP                5661
#define IDD_FIXED_008_MU                5662
#define IDD_FIXED_008_VM                5663
#define IDD_FIXED_008_O                 5664
#define IDD_FIXED_008_CF                5665
#define IDD_FIXED_008_TX                5666
#define IDD_FIXED_007_A                 5667
#define IDD_FIXED_008_SE                5668

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3001
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3008
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
