//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ContentsMgr_BO.rc
//
#define IDC_bCLASS_SEARCH               3
#define IDD_CODE_SEARCH                 8285
#define IDD_CLASS_SEARCH                8286
#define IDC_sISBNISSN                   1003
#define IDC_SEARCH_CODE_TAB             1003
#define IDC_sSTATIC                     1005
#define IDC_sDEG_CODE                   1006
#define IDC_dSTATIC                     1010
#define IDC_dSTATIC1                    1011
#define IDC_dSTATIC2                    1012
#define IDC_sETC_CODE2                  1013
#define IDC_cPRINT_COUNT                1014
#define IDC_sCLASS_CODE                 1015
#define IDC_sUNIVERCITY_CODE            1016
#define IDC_sGOVERNMENT                 1017
#define IDC_sPAN                        1018
#define IDC_sMED_CLASS                  1019
#define IDC_sTHESIS                     1020
#define IDC_sPUBLICATE_YEAR             1021
#define IDC_sTEXT_LANGUAGE              1022
#define IDC_sSUMMARY_LANGUAGE           1023
#define IDC_sPRINT_COUNT                1024
#define IDC_sJANGJUNG                   1025
#define IDC_sUSE_LIMIT_CLASS            1026
#define IDC_sUSE_OBJECT_CLASS           1027
#define IDC_sPANJONG_GUBUN              1028
#define IDC_sMED_CLASS_NONBOOK          1029
#define IDC_bGOVERNMENT                 1030
#define IDC_sINFO                       1031
#define IDC_sINFO_TYPE                  1032
#define IDC_sAUTHOR                     1033
#define IDC_sPUBLISHER                  1034
#define IDC_bTEXT_LANGUAGE              1035
#define IDC_sTITLE                      1037
#define IDC_sKEYWORD                    1038
#define IDC_ePUBLICATE_YEAR_END         1061
#define IDC_cTHESIS                     1091
#define IDC_eWORD                       1096
#define IDC_cUNIVERCITY_CODE            1111
#define IDC_cMED_CLASS                  1137
#define IDC_cMED_CLASS_NONBOOK          1138
#define IDC_ePUBLISHER                  1203
#define IDC_eTITLE                      1266
#define IDC_ePUBLICATE_YEAR_START       1292
#define IDC_cMATERIAL_CLASS             1373
#define IDC_eAUTHOR                     1394
#define IDC_cGOVERNMENT                 1430
#define IDC_eKEYWORD                    1546
#define IDC_eKEYWORD2                   1547
#define IDC_eKEYWORD3                   1548
#define IDC_f1VCF                       1560
#define IDC_f1VCF_01                    1561
#define IDC_f1VCF_02                    1562
#define IDC_eCONTROL_NO                 1704
#define IDC_eCONTROL_NO_START           1740
#define IDC_eCONTROL_NO_END             1741
#define IDC_eCLASS_CODE                 1829
#define IDC_eETC_CODE                   1830
#define IDC_eINDEX                      1851
#define IDC_eSTANDARD_CODE              1958
#define IDC_eETC_CODE1                  1960
#define IDC_eETC_CODE2                  1961
#define IDC_eETC_CODE3                  1962
#define IDC_eETC_CODE4                  1963
#define IDC_cDATA                       1964
#define IDC_cOP1                        1965
#define IDC_OP2                         1966
#define IDC_eTITLE_ARTICLE              1973
#define IDC_cSTANDARD_CODE              1978
#define IDC_cCLASS_CODE                 1980
#define IDC_cETC_CODE                   1981
#define IDC_bUNIVERCITY_CODE            2004
#define IDC_bSUMMARY_LANGUAGE           2005
#define IDC_cPANJONG                    2501
#define IDC_cJANGJUNG                   2503
#define IDC_LIST                        2612
#define IDC_cUSE_OBJECT_CLASS           2774
#define IDC_cUSE_LIMIT_CLASS            2777
#define IDC_TAB                         2789
#define IDC_bCLEAR                      3035
#define IDC_bDETAIL                     3055
#define IDC_bDETAIL_SEARCH              3058
#define IDC_bFIND                       3071
#define IDC_bNEXT                       3106
#define IDC_bCDELETE                    3111
#define IDC_bSAVEA                      3112
#define IDC_bADELETE                    3113
#define IDC_bPREV                       3123
#define IDC_bSEARCH                     3147
#define IDD_CONTENTMGR_01               8287
#define IDC_bEDIT                       5003
#define IDD_CONTENTMGR_02               8288
#define IDD_CONTENTMGR_03               8289
#define IDD_CONTENTMGR_SPECIES          8290
#define IDC_bBRINGINC                   5010
#define IDC_bBRINGINA                   5011
#define IDC_bSAVEC                      5012
#define IDC_STATIC_01                   5014
#define IDC_STATIC_02                   5015
#define IDC_bCONTENTS                   5016
#define IDC_bABSTRACTS                  5017
#define IDC_bSPECIES                    5018
#define IDC_cPANJONG_GUBUN              6000
#define IDD_CONTENTMGR_SEARCH           8291
#define IDC_BUTTON1                     7000
#define IDC_bTest                       7000
#define IDC_bMOK_KEYWORD                7000
#define IDC_bSearchToc                  7001
#define IDC_bCHO_KEYWORD                7001
#define IDD_CONTENTMGR_INDEX_SEARCH     8292
#define IDC_COMBO_LIMIT_MOK             7003
#define IDC_COMBO_LIMIT_CHO             7005
#define IDC_ePubyear                    7006
#define IDC_COMBO_USE_LIMIT_mok         7007
#define DC_COMBO_USE_LIMIT_mok          7008
#define IDC_eMOK_KEYWORD                7009
#define IDC_eCHO_KEYWORD                7010
#define IDC_bDCMInput                   7011
#define IDC_TocRect                     7012
#define IDC_ChoRect                     7013
#define IDC_eCON_CREATE_DATE_F          7301
#define IDC_eCON_CREATE_DATE_T          7302
#define IDC_eCON_UPDATE_DATE_F          7304
#define IDC_eCON_UPDATE_DATE_T          7305
#define IDC_eABS_CREATE_DATE_F          7307
#define IDC_eABS_CREATE_DATE_T          7308
#define IDC_eABS_UPDATE_DATE_F          7310
#define IDC_eABS_UPDATE_DATE_T          7311
#define IDC_eCON_INDEX                  7312
#define IDC_eABS_INDEX                  7313
#define IDC_GRID_VOLUME                 12029
#define IDC_Grid_CONTENT                19001
#define IDD_DATA_SEARCH                 8293

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7004
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         7014
#define _APS_NEXT_SYMED_VALUE           7000
#endif
#endif
