//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MNG_LOC_MGR.rc
//
#define IDC_tabMENU                     5000
#define IDC_radSETTING_LOAN_STOP_USE_N  5002
#define IDC_radSETTING_DELAY_MONEY_USE_Y 5003
#define IDC_radSETTING_DELAY_MONEY_USE_N 5004
#define IDC_radSETTING_FAMILY_USE_Y     5005
#define IDC_radSETTING_LOAN_STOP_USE_N2 5005
#define IDC_radSETTING_FAMILY_USE_N     5006
#define IDC_radSETTING_USER_NO_AUTO_USE_Y 5007
#define IDC_radSETTING_USER_NO_AUTO_USE_N 5008
#define IDC_radSETTING_LOAN_STOP_DATE_AUTO_USE_Y 5009
#define IDC_radSETTING_LOAN_STOP_DATE_AUTO_USE_N 5010
#define IDC_radSETTING_RETURN_TYPE_2_Y  5011
#define IDC_radSETTING_RETURN_TYPE_2_N  5012
#define IDC_cmbSETTING_DELAY_DAY_HOW    5013
#define IDC_radSETTING_APPENDIX_LOAN_Y  5013
#define IDC_cmbSETTING_DELAY_COUNT_HOW  5014
#define IDC_radSETTING_APPENDIX_LOAN_N  5014
#define IDC_edtSETTING_DELAY_MONEY_ADD_NUMBER 5015
#define IDC_radSETTING_CIVILNO_AUTO_CHECK_USE_Y 5015
#define IDC_radSETTING_RELOAN_FAMILY_Y  5016
#define IDC_edtSETTING_DELAY_MONEY      5016
#define IDC_radSETTING_RELOAN_FAMILY_N  5017
#define IDC_edtSETTING_DELAY_MONEY_ADD_NUMBER2 5017
#define IDC_radSETTING_RELOAN_ONE_Y     5018
#define IDC_radSETTING_RELOAN_ONE_N     5019
#define IDC_radSETTING_RELOAN_VIEW_Y    5020
#define IDC_radSETTING_RESERVE_ATUO_CANCEL_Y 5021
#define IDC_radSETTING_APPENDIX_INLUDE_LOAN_BOOK_Y 5021
#define IDC_radSETTING_RESERVE_ATUO_CANCEL_N 5022
#define IDC_radSETTING_APPENDIX_INLUDE_LOAN_BOOK_N 5022
#define IDC_radSETTING_RESERVE_USE_Y2   5023
#define IDC_radSETTING_USER_CARD_Y      5023
#define IDC_radSETTING_LOAN_MANAGE_Y    5024
#define IDC_radSETTING_RESERVE_USE_N2   5024
#define IDC_radSETTING_LOAN_MANAGE_N    5025
#define IDC_radSETTING_RESERVE_ATUO_CANCEL_Y2 5025
#define IDC_radSETTING_LOAN_TYPE_0_Y    5026
#define IDC_radSETTING_RESERVE_EXPIRE_ATUO_Y 5026
#define IDC_radSETTING_LOAN_TYPE_0_N    5027
#define IDC_radSETTING_RESERVE_EXPIRE_ATUO_N 5027
#define IDC_radSETTING_LOAN_TYPE_1_Y    5028
#define IDC_radSETTING_RESERVE_ATUO_CANCEL_Y3 5028
#define IDC_radSETTING_LOAN_TYPE_2_Y    5029
#define IDC_radSETTING_RESERVE_ATUO_CANCEL_N3 5029
#define IDC_radSETTING_LOAN_TYPE_1_N    5030
#define IDC_radSETTING_RESERVE_ATUO_CANCEL_Y4 5030
#define IDC_radSETTING_LOAN_TYPE_2_N    5031
#define IDC_radSETTING_RESERVE_ATUO_CANCEL_N4 5031
#define IDC_radSETTING_RETURN_TYPE_0_Y  5032
#define IDC_radSETTING_SYSDATE_RESERVE_USE_Y 5032
#define IDC_radSETTING_RETURN_TYPE_0_N  5033
#define IDC_radSETTING_SYSDATE_RESERVE_USE_N 5033
#define IDC_radSETTING_RETURN_TYPE_1_Y  5034
#define IDC_radSETTING_RETURN_TYPE_1_N  5035
#define IDC_cmbSETTING_DELAY_OR_RESERVE_RETURN 5036
#define IDC_radSETTING_USER_CARD_N      5036
#define IDC_radSETTING_RESERVE_ATUO_CANCEL_N2 5037
#define IDC_radSETTING_RELOAN_VIEW_N    5037
#define IDC_edtDELAYRETURNCNT           5038
#define IDC_radSETTING_RETURN_MANAGE_Y  5038
#define IDC_edtDELAYRETURNCNT2          5039
#define IDC_cmbCODE                     5039
#define IDC_radSETTING_RETURN_MANAGE_N  5039
#define IDC_cmbSETTING_DELAY_OR_RESERVE_RETURN2 5040
#define IDC_gridCode                    5040
#define IDC_radSETTING_CIVILNO_AUTO_CHECK_USE_N 5040
#define IDC_cmbUSE_OBJ_CODE             5041
#define IDC_cmbRETURN_PLAN_DAY_DELAY_OPTION 5041
#define IDC_radSETTING_LOAN_TYPE_3_Y    5041
#define IDC_gridMAIL                    5042
#define IDC_radSETTING_LOAN_TYPE_3_N    5042
#define IDC_radSETTING_APPENDIX_INLUDE_RETURN_BOOK_Y 5043
#define IDC_radSETTING_APPENDIX_INLUDE_RETURN_BOOK_N 5044
#define IDC_cmbYN1                      5046
#define IDC_cmbYN2                      5047
#define IDC_edtVALUE                    5047
#define IDC_btnAPPLY                    5048
#define IDC_cmbYN3                      5048
#define IDC_radSETTING_LOAN_STOP_USE_Y  5049
#define IDC_staTITLE1                   5050
#define IDC_edtRELOAN_LIMIT_DAY         5050
#define IDC_radSETTING_LOAN_STOP_USE_Y2 5050
#define IDC_staTITLE2                   5051
#define IDC_COMBO2                      5052
#define IDC_staTITLE3                   5052
#define IDC_EDIT1                       5053
#define IDC_EDIT2                       5054
#define IDC_COMBO1                      5055
#define IDC_COMBO3                      5056
#define IDC_STATIC_BORDER               5056
#define IDC_imgDIVISION_WIDTH           5057
#define IDC_imgDIVISION_LONG1           5058
#define IDC_imgDIVISION_LONG2           5059
#define IDC_imgDIVISION_LONG3           5060
#define IDC_radSETTING_LOAN_RECEIPT_USE_Y 5061
#define IDC_radSETTING_LOAN_RECEIPT_USE_N 5062
#define IDC_radSETTING_RETURN_RECEIPT_USE_Y 5063
#define IDC_radSETTING_RETURN_RECEIPT_USE_N 5064
#define IDC_lblTITLE8                   5065
#define IDC_lblFUNCTION19               5067
#define IDC_lblDESC9                    5068
#define IDC_lblFUNCTION18               5069
#define IDC_RE_BORDER                   5070
#define IDC_lblRESERVE_FUNC6            5071
#define IDC_lblRESERVE_DESC3            5072
#define IDC_lblY6                       5073
#define IDC_lblN6                       5074
#define IDC_imgDIVISION_LONG5           5076
#define IDC_imgDIVISION_LONG6           5077
#define IDC_imgDIVISION_LONG4           5078
#define IDC_radSETTING_MESSAGE_TYPE_Y   5079
#define IDC_radSETTING_MESSAGE_TYPE_N   5080
#define IDC_radSETTING_DISPLAY_TYPE_Y   5081
#define IDC_radSETTING_ID_IMPORT_Y      5081
#define IDC_radSETTING_DISPLAY_TYPE_N   5082
#define IDC_radSETTING_ID_IMPORT_N      5082
#define IDC_COMMON_LOAN_TYPE_1          5083
#define IDC_radSETTING_DISPLAY_USER_TYPE_Y 5083
#define IDC_COMMON_LOAN_TYPE_2          5084
#define IDC_radSETTING_DISPLAY_USER_TYPE_N 5084
#define IDC_COMMON_LOAN_TYPE_3          5085
#define IDC_COMMON_LOAN_TYPE_4          5086
#define IDC_LOAN_TYPE_EXP_1             5087
#define IDC_LOAN_TYPE_EXP_2             5088
#define IDC_cmbSetting_MESSAGE_TYPE     5089
#define IDC_radSETTING_ADD_HOLYDAY_LOANSTOP1 5089
#define IDC_LOAN_TYPE_EXP_3             5089
#define IDC_radSETTING_ADD_HOLYDAY_LOANSTOP2 5090
#define IDC_LOAN_TYPE_EXP_4             5090
#define IDC_cmbSetting_MESSAGE_TYPE2    5090
#define IDC_LOAN_TYPE_EXP_5             5091
#define IDC_radSETTING_ADD_HOLYDAY_RESERVATION1 5092
#define IDC_LOAN_TYPE_EXP_6             5092
#define IDC_radSUPPLEMENT_Y             5092
#define IDC_radSETTING_ADD_HOLYDAY_RESERVATION2 5093
#define IDC_radSUPPLEMENT_N             5093
#define IDC_LOAN_TYPE_EXP_8             5094
#define IDC_radHOLYDAY_Y                5094
#define IDC_LOAN_TYPE_EXP_9             5095
#define IDC_radHOLYDAY_N                5095
#define IDC_LOAN_TYPE_EXP_10            5096
#define IDC_edtBASIC_ARREAR             5096
#define IDC_LOAN_TYPE_EXP_7             5097
#define IDC_LOAN_TYPE_EXP_11            5098
#define IDC_edtRELOAN_LIMITDAY          5098
#define IDC_LOAN_TYPE_EXP_12            5099
#define IDC_LOAN_TYPE_EXP_13            5100
#define IDC_eMNG01_DELAYDAY_WEIGHT      5100
#define IDC_eMNG01_BASIC_ARREAR         5101
#define IDC_LOAN_TYPE_EXP_15            5102
#define IDC_eMNG01_MAX_LOAN_STOP_DAY    5102
#define IDC_LOAN_TYPE_EXP_16            5103
#define IDC_LOAN_TYPE_EXP_17            5104
#define IDC_eMNG10_BASIC_ARREAR         5104
#define IDC_LOAN_TYPE_EXP_14            5105
#define IDC_eMNG10_MAX_LOAN_STOP_DAY    5105
#define IDC_LILL_DESC                   5105
#define IDC_LOAN_TYPE_EXP_18            5106
#define IDD_EDIT_BOX_DIALOG             8337
#define IDD_MNG_LOC_MGR_DLG             8338
#define IDD_MNG_LOC_MGR_01_DLG          8339
#define IDD_MNG_LOC_MGR_02_DLG          8340
#define IDD_MNG_LOC_MGR_03_DLG          8341
#define IDD_MNG_LOC_MGR_05_DLG          8342
#define IDD_MNG_LOC_MGR_04_DLG          8343
#define IDD_MNG_LOC_MGR_06_DLG          8344
#define IDD_MNG_LOC_MGR_07_DLG          8345
#define IDD_MNG_LOC_MGR_08_DLG          8346
#define IDD_MNG_LOC_MGR_09_DLG          8347
#define IDD_MNG_LOC_MGR_10_DLG          8348
#define IDC_eMNG09_LOANSTOPDAY          16000
#define IDC_edtDELAYRETURN_CNT          16000
#define IDC_edtLIMIT                    16001
#define IDC_gridMNG_LOC_MGR_08          19003
#define IDC_gridMNG_LOC_MGR_09          19004
#define IDC_gridMNG_LOC_MGR_02          19005
#define IDC_gridMNG_LOC_MGR_01          19006
#define IDC_gridMNG_LOC_MGR_03          19007
#define IDC_gridMNG_LOC_MGR_07          19008
#define IDC_gridMNG_LOC_MGR_10          19009
#define IDC_gridPOSITION                30009
#define IDC_gridPOSITION2               30010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        5014
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         5106
#define _APS_NEXT_SYMED_VALUE           5000
#endif
#endif
