//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BL_LOC_LOAN.rc
//
#define IDC_BTN2                        2
#define IDC_BTN3                        3
#define IDC_BTN4                        4
#define IDR_MAINFRAME                   128
#define IDC_MAINGRID3                   1000
#define IDC_APPENDIX_LIST               1002
#define IDC_btnSELECT                   1003
#define IDC_radAPPENDIX_RETURN1         1004
#define IDC_btnBOOK_RESERVATION         1004
#define IDC_radAPPENDIX_RETURN2         1005
#define IDC_btnBOOK_DETAIL              1005
#define IDC_radAPPENDIX_RETURN3         1006
#define IDC_btnSRFID_SYNC               1006
#define IDC_edtAPPENDIX_RETURN4         1007
#define IDC_edtRESERVATION1             1008
#define IDC_edtAPPENDIX_RETURN5         1008
#define IDB_BITMAP_BOOK                 1008
#define IDC_edtRESERVATION3             1009
#define IDB_BITMAP2                     1009
#define IDC_edtRESERVATION5             1010
#define IDC_edtRESERVATION6             1011
#define IDC_edtRESERVATION2             1012
#define IDI_ICON1                       1012
#define IDC_edtRESERVATION4             1013
#define IDC_LOAN_MANAGE_VALUE_PROGRESS  1014
#define IDC_staMSG                      1015
#define IDR_BL_LOC_VOL_RESERVE_MNG_MAINFRAME 1015
#define IDC_edtKUS_LibCode              1015
#define IDC_edtINPUT_RESERVATOIN_EXPIRE_DAY 1016
#define IDC_edtKUIS_UserNo              1016
#define IDC_btnOK                       1017
#define IDC_staBOTTOMLINE               1018
#define IDC_tabMENU                     1019
#define IDC_edtAPPENDIX_BARCODE         1020
#define IDC_sMED_CLASS                  1020
#define IDC_LOAN_HISTORY_GRID           1021
#define IDC_sPUBLICATE_YEAR             1021
#define IDC_btnLOAN_CLOSE               1022
#define IDC_edtFileUSER18               1022
#define IDC_sREG_NO                     1022
#define IDC_LOAN_HISTORY_GRID2          1023
#define IDC_sCLASS_NO                   1023
#define IDC_staTITLE2                   1024
#define IDC_btnLOAN_COTINUE             1026
#define IDC_chkALL_APPLY                1027
#define IDC_sLOANSTOPDATE               1029
#define IDI_ICON2                       1029
#define IDC_DATETIMEPICKER1             1031
#define IDC_LIST1                       1032
#define IDC_sINFO_TYPE                  1032
#define IDC_LOAN_MONTHCALENDAR1         1033
#define IDD_LR2_DELAY_USER_MANAGER      1033
#define IDD_DELAY_USER_DLG              1033
#define IDC_sAUTHOR                     1033
#define IDC_edtINPUT_LOAN_DAY           1034
#define IDC_sPUBLISHER                  1034
#define IDC_rSINGLE                     1035
#define IDD_INSERT_PASSWORD_DLG         1035
#define IDC_sINFO_TYPE2                 1035
#define IDC_STATIC2                     1036
#define IDC_edtBARCODE                  1036
#define IDC_edtSERIALNO                 1037
#define IDC_STATIC3                     1037
#define IDC_rDUAL                       1037
#define IDC_sTITLE                      1037
#define IDC_rDETAIL_Y                   1038
#define IDR_MAINFRAME2                  1038
#define IDC_sKEYWORD                    1038
#define IDC_rDETAIL_N                   1039
#define IDC_sAUTHOR2                    1039
#define IDC_rMODE1                      1040
#define IDC_btnIgnore                   1040
#define IDC_btnUSERFIND1                1040
#define IDC_datRETURN1                  1041
#define IDC_rMODE2                      1041
#define IDC_btnPrintTest                1041
#define IDC_datRETURN2                  1042
#define IDC_rMODE3                      1042
#define IDC_EDT_LOAN_BSC                1042
#define IDC_btnRESERVATIONCLOSE         1043
#define IDC_rMODE4                      1043
#define IDC_edtBARCODE2                 1044
#define IDC_edtARREARDAY                1044
#define IDC_btnUSERCLOSE                1044
#define IDC_btnRETURNCLOSE              1045
#define IDC_edtARREARDAY1               1046
#define IDC_chkLOAN_RECEIPT             1047
#define IDC_edtARREARDAY2               1047
#define IDD_SEARCH_BOOK_INFO            1047
#define IDD_SEARCH_BOOK_RESULT          1047
#define IDC_chkRETURN_RECEIPT           1048
#define IDC_edtMONEYPAID                1048
#define IDC_staSEARCH_VIEWSIMPLE        1048
#define IDC_chkPREVIEW                  1049
#define IDC_datLOANSTOPDATE             1049
#define IDC_edtLOANSTOPDATE             1049
#define IDD_VIEW_TAG_INFO               1049
#define IDC_staSEARCH_VIEWDETAIL        1049
#define IDC_btnCUT_RECEIPT              1050
#define IDC_gridARREAR                  1050
#define IDC_staSEARCH_VIEWSIMPLE2       1050
#define IDC_edtMONEYPAID2               1051
#define IDC_edtARREARDAY3               1052
#define IDC_edtSTOP_DAY                 1052
#define IDD_SMS                         1052
#define IDD_SMS_EDIT                    1053
#define IDC_edtBASICARREAR              1053
#define IDD_VIEW_TAG_INFO_DLG           1054
#define IDC_edtBOOK                     1056
#define IDC_gridARREARUSERLIST          1057
#define IDC_gridARREARBOOKLIST          1058
#define IDC_gridARREARUSERLISTMAX       1059
#define IDC_edtUSERFIND8                1061
#define IDB_TAG_INFO_BG                 1061
#define IDC_edtUSERFIND10               1062
#define IDC_btnFEE_RECEIPT_PRINT        1064
#define IDC_SMS_STATIC                  1064
#define IDC_btnFEE_PREVIEW              1067
#define IDC_EDT_NOTIFY                  1069
#define IDC_btn3115_LoanUserView        1069
#define IDD_KL_SELECT_LIB               1069
#define IDC_chkLOAN_HISTORY2_ALLCHECK   1070
#define IDC_gridLOAN_HISTORY2_BOOK      1071
#define IDC_gridLOAN_HISTORY2_HISTORY   1072
#define IDB_LOAN_KL_MSG                 1072
#define IDC_btnLOAN_HISTORY2_COTINUE    1073
#define IDC_btnLOAN_HISTORY2_CLOSE      1074
#define IDC_edtLOAN_HISTORY2_LIMITDAY   1075
#define IDC_edtLOAN_HISTORY2_DATE1      1076
#define IDC_gridLOAN_APPENDIX_LIST2     1076
#define IDC_edtLOAN_HISTORY2_DATE2      1077
#define IDC_edtLOAN_APPENDIX_LIST2_BARCODE 1077
#define IDC_btnLOAN_APPENDIX_LIST2_SELECT 1078
#define IDC_btnLOAN_APPENDIX_LIST2_CANCEL 1079
#define IDC_edtSREG_NO                  1079
#define IDC_gridRETURN_APPENDIX_LIST2   1080
#define IDC_gridRAL_BOOK                1080
#define IDD_KL_OTHER_RETURN_EDIT_MEMO   1080
#define IDC_btnRETURN_APPENDIX_LIST2_SELECT 1081
#define IDD_KL_OTHER_RETURN_DETAILVIEW  1081
#define IDC_btnRETURN_APPENDIX_LIST2_CANCEL 1082
#define IDD_RESERVATION_DLG             1082
#define IDC_gridLOAN_FAIL_LIST          1083
#define IDC_gridRAL_APPENDIX            1083
#define IDC_btnLOAN_FAIL_LIST_CLOSE     1084
#define IDD_GROUP_LIB_LIST              1084
#define IDC_staLOAN_FAIL_LIST_MSG       1085
#define IDC_staRETURN_MISSING_LIST_MSG  1086
#define IDC_btnRETURN_MISSING_LIST_CLOSE 1087
#define IDC_btnKOLL_Close               1087
#define IDC_gridRETURN_MISSING_LIST     1088
#define IDC_gridKOLL_Main               1088
#define IDC_btnKOLL_Return              1089
#define IDC_gridRS_COURSE               1094
#define IDC_btnRS_COURSE_SEARCH         1096
#define IDC_chkUSE_LIMIT                1098
#define IDC_chkUSE_UserSearch           1099
#define IDC_chkUSE_ILL_LIMIT            1101
#define IDC_btnRS_CANCEL_SEARCH         1102
#define IDC_datRESERVATION1             1104
#define IDC_gridRECEIPT                 1106
#define IDC_gridRS_CANCEL               1106
#define IDC_edtUSER_NO                  1107
#define IDC_edtUSER_NAME                1108
#define IDC_btnRS_CANCEL_INIT           1108
#define IDC_edtRESERVATION8             1109
#define IDC_radLOAN                     1109
#define IDC_btnDUM_CLOSE                1109
#define IDC_edt_ILL_APL_USER_NAME       1109
#define IDC_radRETURN                   1110
#define IDC_edtRS_CANCEL_BEFORE         1110
#define IDC_btnPRINT_RECEIPT            1111
#define IDC_btnPRINT_RECEIPT2           1111
#define IDC_edtRS_CANCEL_AFTER          1111
#define IDC_btnLocloanCLOSE             1112
#define IDC_btnLOANSTOPCLOSE2           1112
#define IDC_progRS_COURSE               1112
#define IDC_btnPREVIEW                  1113
#define IDC_progRS_CANCEL               1113
#define IDC_STATIC1                     1114
#define IDC_btnSETUP                    1115
#define IDC_edtPREVIEW                  1115
#define IDC_btnLOANPRINT                1115
#define IDC_TAB_LOAN1                   1116
#define IDC_tabRS                       1116
#define IDC_edtRETURN1                  1117
#define IDC_TAB_LOAN2                   1117
#define IDC_edtTOTAL                    1117
#define IDC_btnSEARCH                   1118
#define IDC_btnRS_USER                  1118
#define IDC_btnRS_COURSE_USER           1118
#define IDC_btnPRINT_CANCEL             1119
#define IDC_btnRS_CANCEL_USER           1119
#define IDC_btnDATE_SEARCH              1120
#define IDC_btnRS_CLOSE                 1120
#define IDC_TAB_MENU                    1120
#define IDC_cmbRS_SLC                   1121
#define IDC_cmbRS_SLC_MULTI             1121
#define IDC_cmbRS_SLC2                  1122
#define IDC_cmbRS_SLC_MULTI2            1122
#define IDC_btnRS_CANCEL_RECEIPT        1123
#define IDC_stcRS_CANCEL_TITLE          1124
#define IDC_stcRS_CANCEL_WAVE           1125
#define IDC_progRS_MARQUEE1             1126
#define IDC_progRS_MARQUEE2             1127
#define IDC_btnKUS_LibCode              1127
#define IDC_stcRS_DIALOG_MIN_SIZE       1128
#define IDC_btnRS_CANCEL_RESERVE        1128
#define IDC_edtDelayDays                1129
#define IDC_cmbRO_SLC                   1129
#define IDC_edtDUM_DELAY_DAY_MORE       1129
#define IDC_cmbShelfLocCode             1130
#define IDC_btnRO_SEARCH                1130
#define IDC_cmbDUM_SLC                  1130
#define IDC_edtPM_DELAYCNT1             1130
#define IDC_btnSearchDelayUser          1131
#define IDC_gridRO_MAIN                 1131
#define IDC_btnDUM_SEARCH               1131
#define IDC_GROUP_BOX_1                 1131
#define IDC_btnSearchUser               1132
#define IDC_progRO_MARQUEE              1132
#define IDC_btnDUM_USER                 1132
#define IDC_gridDelayUserList           1133
#define IDC_progRO_PERCENT              1133
#define IDC_gridDUM_USER                1133
#define IDC_gridDelayUserLoanList       1134
#define IDC_btnRO_CLOSE                 1134
#define IDC_gridDUM_LOAN                1134
#define IDC_progRO_MARQUEE2             1134
#define IDC_btnDelayDayPlus             1135
#define IDC_stcRO_MIN_SIZE              1135
#define IDC_btnDUM_PLUS                 1135
#define IDC_btnDelayDayMinus            1136
#define IDC_stcRS_MIN_SIZE              1136
#define IDC_btnRO_USER                  1136
#define IDC_btnDUM_MINUS                1136
#define IDC_btnDUM_INIT                 1137
#define IDC_cmbUSERFIND9                1137
#define IDC_cmbRO_SLC_MULTI             1137
#define IDC_progDUM_MARQUEE             1138
#define IDC_btnRO_RECEIPT               1138
#define IDC_cmbPM_CLASS                 1138
#define IDC_progDUM_PERCENT             1139
#define IDC_btnRO_RESERVE               1139
#define IDC_cmbPM_EDIT_CLASS            1139
#define IDC_cmbUSERFIND10               1139
#define IDC_stcDUM_USER                 1140
#define IDC_progPM_PERCENT              1140
#define IDC_stcDUM_LOAN                 1141
#define IDC_progPM_MARQUEE              1141
#define IDC_stcDUM_MIN_SIZE             1142
#define IDC_edtPassword                 1143
#define IDC_stcDUM_REMARK               1143
#define IDC_radNewIssue                 1144
#define IDC_radReIssue                  1145
#define IDC_btnNewIssue                 1146
#define IDC_btnReIssue                  1147
#define IDC_edtDUM_DELAY_DAY_LESS       1149
#define IDC_btnDelaydayModify           1150
#define IDC_btnDUM_SAVE                 1150
#define IDC_edtPM_DELAYCNT2             1150
#define IDC_edtDelayMore                1151
#define IDC_edtDelayLess                1152
#define IDC_btnDelaydaySave             1153
#define IDC_btnSLU_SEARCH               1155
#define IDC_progSLU_MARQUEE             1156
#define IDC_edt_ILL_LOAN_REG_NO         1157
#define IDC_grid_ILL_RETURN_OTHER       1157
#define IDC_progSLU_PERCENT             1157
#define IDC_btn_ILL_LOAN                1158
#define IDC_grid_ILL_LOAN               1159
#define IDC_btn_ILL_RETURN              1159
#define IDC_edt_KL_RETURN_REG_NO        1160
#define IDC_staILL_LOAN_USER            1160
#define IDC_edt_ILL_RETURN_REG_NO       1160
#define IDC_tab_ILL_RETURN              1161
#define IDC_staILL_RETURN_USER          1162
#define IDC_grid_ILL_RETURN_WE          1162
#define IDC_btnRP_RECEIPT               1163
#define IDC_datRESERVATION2             1164
#define IDC_chkRP_RECEIPT               1164
#define IDC_btnSELECT2                  1165
#define IDC_chkRP_SMS                   1165
#define IDC_stcRP_BOOK                  1166
#define IDC_stcRP_USER                  1167
#define IDC_gridRP_BOOK                 1168
#define IDC_gridRP_USER                 1169
#define IDC_btnRP_GRANT                 1170
#define IDC_btnRP_CLOSE                 1171
#define IDC_gridRU_BOOK                 1172
#define IDC_gridRP_VOL_BOOK             1172
#define IDC_btnRU_CLOSE                 1173
#define IDC_gridRU_VOL_BOOK             1174
#define IDC_grid1                       1174
#define IDC_RADIO_LOAN4                 1176
#define IDC_RADIO_LOAN5                 1177
#define IDC_RADIO_LOAN6                 1178
#define IDC_RADIO_LOAN7                 1179
#define IDC_EDIT_LOAN1                  1180
#define IDC_BUTTON2                     1181
#define IDC_edtKLUserSettingPhone       1181
#define IDC_BUTTON_LOAN_3               1182
#define IDC_edtKLUserSettingLastLoan    1182
#define IDC_btnKL_ReturnCancel          1182
#define IDC_edtKLUserSettingLastEdit    1183
#define IDC_btnKL_print_waybill         1183
#define IDC_EDIT_LOAN2                  1184
#define IDC_edtKLUserSettingAdd         1184
#define IDC_btnKL_edit_memo             1184
#define IDC_BUTTON5                     1185
#define IDC_edtKUI_HomePhone            1185
#define IDC_BUTTON_SAVE                 1185
#define IDC_btnKL_loan_user_view        1186
#define IDC_edtKLUserSettingPhone2      1186
#define IDC_EDIT_LOAN3                  1187
#define IDC_edtKLUserSettingPhone3      1187
#define IDC_EDIT_LOAN4                  1188
#define IDC_btnSecuritySynchronization  1188
#define IDC_gridTagInfo                 1189
#define IDC_staProgress                 1190
#define IDC_progRO_VOL_MARQUEE          1191
#define IDC_btnRO_VOL_RESERVE           1192
#define IDC_gridRO_VOL_MAIN             1193
#define IDC_btnRO_VOL_CLOSE             1194
#define IDC_btnRO_VOL_USER              1195
#define IDC_btnRO_VOL_SEARCH            1196
#define IDC_cmbRO_VOL_SLC_MULTI         1197
#define IDC_stcRP_VOL_BOOK              1198
#define IDC_btnRO_VOL_RECEIPT           1198
#define IDC_stcRP_VOL_USER              1199
#define IDC_chkRP_VOL_SMS               1200
#define IDC_progRO_VOL_PERCENT          1200
#define IDC_cmb_ILL_RETURN_MANAGE_CODE  1201
#define IDC_btnRP_VOL_GRANT             1201
#define IDC_btnRO_SLC                   1201
#define IDC_grid_ILL_RETURN_SEARCH_BOOK 1202
#define IDC_btnRP_VOL_CLOSE             1202
#define IDC_btnSecurityCheckStart       1202
#define IDC_gridRP_VOL_USER             1203
#define IDC_btnSecurityCheckStop        1203
#define IDC_edtUSERFIND6                1203
#define IDC_chkRP_VOL_RECEIPT           1204
#define IDC_gridSLC_MAIN                1204
#define IDC_edtUSERFIND_6               1205
#define IDC_btnRP_VOL_RECEIPT           1205
#define IDC_btnSLC_SELECT               1205
#define IDC_btnSLC_CANCEL               1206
#define IDC_btnRO_VOL_SLC               1207
#define IDC_btnRS_COURSE_SLC            1208
#define IDC_btnRS_CANCEL_SLC            1209
#define IDC_btnDUM_SLC                  1209
#define IDC_cmbUSERFIND12               1210
#define IDC_stcDUM_OPTION               1210
#define IDC_progVTI_PERCENT             1211
#define IDC_chkLibName                  1212
#define IDC_BUTTON1                     1212
#define IDC_chkUserName                 1213
#define IDC_BUTTON4                     1213
#define IDC_BUTTON_NEXT                 1213
#define IDC_edtFileUSER2                1214
#define IDC_staMSG2                     1214
#define IDC_chkDelayBookCnt             1215
#define IDC_sta1                        1215
#define IDC_edtLOANFileUSER15           1215
#define IDC_BUTTON_CLOSE                1215
#define IDC_chkTotalDelayDay            1216
#define IDC_edtFileUSER23               1216
#define IDC_chkDivideYN                 1217
#define IDC_edtMessage                  1218
#define IDC_edtSMSPreview               1219
#define IDC_edtLibListSearch            1219
#define IDC_staSMSLength                1220
#define IDC_radLibListArea              1220
#define IDC_radLibListUnity             1221
#define IDC_stcSP_DEFAULT               1222
#define IDC_btnLibListSearch            1222
#define IDC_stcRAL_BOOK                 1223
#define IDC_gridSECURITY_AGAIN          1223
#define IDC_stcSP_HEAD                  1223
#define IDC_gridLibListGrid             1223
#define IDC_stcRAL_APPENDIX             1224
#define IDC_btnSECURITY_AGAIN_CLOSE     1224
#define IDC_stcSP_FLOOR                 1224
#define IDC_btnLibListSelect            1224
#define IDC_staSECURITY_AGAIN_MSG       1225
#define IDC_btnLibListClose             1225
#define IDC_btnSECURITY_AGAIN           1226
#define IDC_stcLibListString            1226
#define IDC_gridRC_MAIN                 1227
#define IDC_btnRC_RETURN                1228
#define IDC_btnRC_CLOSE                 1229
#define IDC_btnRC_RELOAD                1230
#define IDC_btnPM_EDIT_CLASS            1230
#define IDC_gridPM_MAIN                 1231
#define IDC_btnPM_SEARCH                1232
#define IDC_btnPM_SAVE                  1233
#define IDC_edtKOLL_RegNo               1233
#define IDC_btnPM_INIT                  1234
#define IDC_chkPM_DELAY                 1236
#define IDC_chkPM_LOANCNT               1237
#define IDC_chkPM_POSITION              1238
#define IDC_chkPM_CLASS                 1239
#define IDC_stcPM_REMARK                1240
#define IDC_edtPM_REMARK                1241
#define IDC_btnPM_REMARK                1242
#define IDC_edtPM_LOANDATE1             1243
#define IDC_edtPM_LOANDATE2             1244
#define IDC_edtPM_LOANCNT1              1245
#define IDC_edtPM_LOANCNT2              1246
#define IDC_cmbPM_POSITION              1247
#define IDC_btnPM_CLOSE                 1248
#define IDC_stcPM_EDIT_CLASS            1249
#define IDC_stcPM_OPTION                1250
#define IDC_radPM_THIS_YEAR             1251
#define IDC_radPM_THIS                  1252
#define IDC_radPM_LAST                  1253
#define IDC_btnSMSEdit                  1254
#define IDC_staPicture                  1255
#define IDC_staSaveResult               1256
#define IDC_BTN1                        1257
#define IDC_stcKLUserSearchMsg          1258
#define IDC_btnKLUserSearchAgain        1259
#define IDC_btnKLUserSearchClose        1260
#define IDC_radKLUserSettingSMSY        1261
#define IDC_radKLUserSettingSMSN        1262
#define IDC_radKLUserSettingMAILY       1263
#define IDC_btnKLUserSettingOK          1264
#define IDC_btnKLUserSettingClose       1265
#define IDC_edtRETURN3                  1266
#define IDC_edtKLUserSettingMail        1266
#define IDC_btnKLUserLoanInfoAgain      1267
#define IDC_btnKLUserLoanInfoClose      1268
#define IDC_stcKLUserLoanInfoMsg        1269
#define IDC_eArrear                     1270
#define IDC_eLoanStopDate               1271
#define IDC_btnArrearCheck              1272
#define IDC_BTN_REFRESH                 1274
#define IDC_BUTTON3                     1275
#define IDC_btnSecurityOn               1279
#define IDC_btnSecurityOff              1280
#define IDC_stcKUS_UserInfo             1281
#define IDC_stcKUS_Status               1282
#define IDC_Date1                       1282
#define IDC_stcKUS_LibList              1283
#define IDC_Date2                       1283
#define IDC_stcDate1                    1286
#define IDC_stcDate2                    1287
#define IDC_stcKUSY_LibList             1288
#define IDC_btnKUSY_LibSearch           1289
#define IDC_EDIT_LOAN_USERNO            1289
#define IDC_gridKUSY_Lib                1290
#define IDC_EDIT_LOAN_USERNAME          1290
#define IDC_edtKUSY_LibCode             1291
#define IDC_EDIT_LOAN_DATE              1291
#define IDC_edtUSERFIND7                1292
#define IDC_EDIT_LOAN_RETURN_PLAN_DATE  1292
#define IDC_edtUSERFIND9                1293
#define IDC_btnKUSY_UserSearch          1293
#define IDC_EDIT_BOOK_TITLE             1293
#define IDC_stcKUSY_Status              1294
#define IDC_EDIT_BOOK_PUBLISHER         1294
#define IDC_btnKUSY_Switch              1295
#define IDC_EDIT_BOOK_AUTHOR            1295
#define IDC_btnKUSY_Close               1296
#define IDC_BTN_RESERVATION_EXPIRE_GIVE 1296
#define IDC_stcKUI_MSG                  1297
#define IDC_BTN_SEND_EMAIL              1297
#define IDC_cmbKUI_UserNoClass          1298
#define IDC_BTN_SEND_SMS                1298
#define IDC_cmbKUI_MemberClass          1299
#define IDC_BTN_PRINT                   1299
#define IDC_cmbKUI_UserClass            1300
#define IDC_BTN_RESERVATION_CANCEL      1300
#define IDC_edtKUI_Phone1               1301
#define IDC_BTN_CANCEL                  1301
#define IDC_edtKUI_Phone2               1302
#define IDC_BTN_RESERV_ASSIGN           1302
#define IDC_edtKUI_Phone3               1303
#define IDC_BTN_RESERV_ASSIGN_CANCEL    1303
#define IDC_edtKUI_Mail                 1304
#define IDC_STATIC_RESERV_DLG_RESULT    1304
#define IDC_edtKUI_Address              1305
#define IDC_edtKUI_Remark               1306
#define IDC_edtKUI_LastLoan             1307
#define IDC_edtKUI_LastEdit             1308
#define IDC_btnKUI_Save                 1309
#define IDC_btnKUI_Cancel               1310
#define IDC_edtKUIS_LibCode             1311
#define IDC_btnKUIS_LibCode             1312
#define IDC_btnKUIS_Import              1314
#define IDC_btnKUIS_Close               1315
#define IDC_stcKUIS_Status              1316
#define IDC_chkKLUserSettingOK          1317
#define IDC_chkKUIS_Confirm             1318
#define IDC_chkKUS_Confirm              1319
#define IDC_edtKL_SWITCH_STATEMENT      1320
#define IDC_stcKL_USER_SWITCH           1321
#define IDC_btnKL_GipyoPrint            1322
#define IDC_btnKL_PostInfo              1323
#define IDC_gridKORD_Main               1324
#define IDC_edt_SendLibname             1325
#define IDC_edt_ReceiveLibname          1326
#define IDC_btn_Prev                    1327
#define IDC_edt_RequestDate             1328
#define IDC_BUTTON_PRE                  1328
#define IDC_btnBookSELECT               1328
#define IDC_edt_PostNo                  1329
#define IDC_grid_Main                   1329
#define IDC_btn_Next                    1330
#define IDC_Static_CivilNo              1330
#define IDC_Static_Hyphen               1331
#define IDC_EDIT_HOLYDAY                1332
#define IDC_STATIC_EXPLAIN              1333
#define IDC_edtUSER7                    1334
#define IDC_edtSLU_NAME                 1334
#define IDC_edtFileUSER7                1334
#define IDC_edtKUI_UserName             1334
#define IDC_EDIT_ALL_HOLYDAY            1334
#define IDC_STATIC_HOLYDAY1             1335
#define IDC_STATIC_HOLYDAY2             1336
#define IDC_STATIC_HOLYDAY3             1337
#define IDC_STATIC_HOLYDAY4             1338
#define IDC_STATIC_DELAY1               1339
#define IDC_STATIC_HOLY1                1340
#define IDC_EDIT_DELAY1                 1341
#define IDC_EDIT_HOLYDAY1               1342
#define IDC_btn_PRESERVATION_LOAN       1346
#define IDC_edt_PRESERVATION_LOAN_REG_NO 1347
#define IDC_staPRESERVATION_LOAN_USER   1348
#define IDC_grid_PRESERVATION_LOAN      1349
#define IDC_staPRESERVATION_RETURN_USER 1350
#define IDC_edt_PRESERVATION_RETURN_REG_NO 1351
#define IDC_btn_PRESERVATION_RETURN     1352
#define IDC_cmb_PRESERVATION_RETURN_MANAGE_CODE 1353
#define IDC_tab_PRESERVATION_RETURN     1354
#define IDC_grid_PRESERVATION_RETURN_OTHER 1355
#define IDC_grid_PRESERVATION_RETURN_WE 1356
#define IDC_grid_PRESERVATION_RETURN_SEARCH_BOOK 1357
#define IDC_cmbUSERFIND2                1373
#define IDC_cmbUSERFIND13               1374
#define IDC_edtUSERFIND5                1395
#define IDC_edt_ILL_APL_BOOK_REG_NO     1414
#define IDC_edt_ILL_BOOK_CALL_NO        1415
#define IDC_edt_ILL_APL_PUBLISHER       1416
#define IDC_edt_ILL_APL_DIV             1417
#define IDC_edt_ILL_APL_BOOK_TITLE      1418
#define IDC_edt_ILL_APL_AUTHOR          1419
#define IDC_edt_ILL_APL_CONTENT         1420
#define IDC_edt_ILL_APL_USER_CONTENT    1421
#define IDC_edt_ILL_APL_LIBNAME         1422
#define IDC_edt_ILL_APL_GIVE_LIBNAME    1423
#define IDC_edt_ILL_APL_BOOK_PUB_YEAR   1424
#define IDC_edt_ILL_APL_VOL             1425
#define IDC_edt_ILL_APL_PUBLISH_FORM    1426
#define IDC_edt_ILL_APL_GIVE_LIBCODE    1427
#define IDC_edt_ILL_APL_APL_LIBCODE     1428
#define IDC_edt_ILL_APL_APL_BOOKKEY     1429
#define IDC_edt_ILL_APL_USER_CLASSCODE  1430
#define IDC_edt_ILL_APL_BOOK_MANAGECODE 1431
#define IDC_edt_ILL_APL_APL_USERKEY     1432
#define IDC_edt_ILL_APL_BOOK_APPENDIX_FLAG 1433
#define IDC_edt_ILL_APL_BOOK_MOTHER_KEY 1434
#define IDC_edtFileUSER3                1436
#define IDC_edtFileUSER8                1444
#define IDC_edtUSER33                   1445
#define IDC_edtRETURN2                  1470
#define IDC_redtMESSAGE                 1530
#define IDC_edtFileUSER22               1531
#define IDC_redtMESSAGE3                1532
#define IDC_edtRESERVATION7             1533
#define IDC_edtUSER1                    1533
#define IDC_edtSLU_USERNO               1533
#define IDC_edtFileUSER1                1533
#define IDC_edtKUI_UserNo               1533
#define IDC_edt_ILL_APL_USER_NO         1533
#define IDC_edt_ILL_APL_USER_NO2        1534
#define IDC_edtUSERFIND2                1546
#define IDC_edtUSERFIND3                1547
#define IDC_edtUSERFIND4                1548
#define IDC_edtFileUSER21               1694
#define IDC_edtHOLY_DAY                 1853
#define IDC_edtDISSOLVE_DAY             1854
#define IDC_cmbUSERFIND4                1965
#define IDC_cmbUSERFIND5                1966
#define IDC_edtUSERFIND1                1973
#define IDC_edtUSERFIND_1               1974
#define IDC_STATIC_5                    2186
#define IDC_STATIC_6                    2187
#define IDC_STATIC_9                    2190
#define IDC_BTN_PRINT_CANCEL2           2207
#define IDC_edt_ILL_APL_DATE            2379
#define IDC_edtFileUSER4                2601
#define IDC_cmbFileUSER3                2728
#define IDC_cmbUSER8                    2729
#define IDC_edtUSER10                   2739
#define IDC_edtSLU_ADDRESS              2739
#define IDC_edtFileUSER10               2739
#define IDC_edtFileUSER9                2740
#define IDC_edtFileUSER11               2741
#define IDC_edtFileUSER13               2742
#define IDC_edtFileUSER12               2743
#define IDC_edtFileUSER14               2744
#define IDC_cmbFileUSER5                2750
#define IDC_radRETURN1                  2856
#define IDC_radRETURN2                  2857
#define IDC_radRETURN3                  2858
#define IDC_radSTEP1                    2859
#define IDC_radSTEP2                    2860
#define IDC_radSTEP3                    2861
#define IDB_BITMAT_SMS                  3001
#define IDC_cmbFileUSER1                3008
#define IDC_cmbKLUserSettingUserClass   3008
#define IDC_cmbFileUSER2                3009
#define IDC_cmbKLUserSettingMemberClass 3009
#define IDC_btnFileSAVE                 3010
#define IDC_btnSAVE                     3010
#define IDC_cmbFileUSER7                3011
#define IDC_cmbUSER9                    3014
#define IDC_STATIC_UNVISIBLE_2          3017
#define IDC_btnLOAN_CANCEL              3028
#define IDC_btnLOAN_CLEAR               3035
#define IDC_btnSLU_CLEAR                3035
#define IDC_btnCLEAR                    3035
#define IDC_btnFileCLOSE                3047
#define IDC_STATIC_PASS_CONFIRM         3049
#define IDC_btnKUS_Close                3050
#define IDC_gridRESERVATION             3054
#define IDC_btnSEARCH_DETAIL            3055
#define IDC_btnFileFIND2                3071
#define IDC_btnDDFINDUSER               3071
#define IDC_btnRETURNNEXT               3106
#define IDC_btnFileNEXT                 3106
#define IDC_btnRETURNPREV               3123
#define IDC_btnFilePREV                 3123
#define IDC_BTN_SMS_SEND                3147
#define IDC_btnFileFIND1                3147
#define IDC_btnDDFINDBOOK               3147
#define IDC_BTN_SMS_CLOSE               3148
#define IDC_btnDUEDATE                  3162
#define IDC_btnRETURNSAVE               3237
#define IDC_btnFileDUPLICATE1           3247
#define IDC_btnKUI_SetUserNo            3248
#define IDC_btnFileDUPLICATE2           3290
#define IDC_btnDUPLICATE4               3292
#define IDC_btnSENDMAIL                 3334
#define IDC_btnSENDSMS                  3335
#define IDC_btnAPL                      4006
#define IDC_btnDDCLOSE                  4014
#define IDC_edt_ILL_APL_USER_EMAIL      4015
#define IDC_edtFileUSER16               5000
#define IDC_edtFileUSER17               5001
#define IDC_btnREG_CARDPASSWD           5035
#define IDC_EDT_CARDPASSWD              5036
#define IDC_SttMSG_CARDPASSWD           5037
#define IDOK_CARDPASSWD                 5038
#define IDCANCEL_CARDPASSWD             5039
#define IDD_SEARCH_LOAN_INFO            5884
#define IDD_USER_INFO                   5885
#define IDC_stext_state_description     6004
#define IDC_edt_KL_RETURN_MEMO_TITLE    6005
#define IDC_edt_KL_RETURN_MEMO_USERNO   6006
#define IDC_edt_KL_RETURN_MEMO_REGNO    6007
#define IDC_edtRETURN5                  6008
#define IDC_edt_KL_RETURN_MEMO_CONTENT  6008
#define IDC_edtRETURN6                  6009
#define IDC_edtRETURN4                  6011
#define IDC_grid_userview               6011
#define IDC_edtRETURN7                  6012
#define IDC_gridRECEIPT2                6013
#define IDC_edtRETURN9                  6013
#define IDC_gridRECEIPT3                6014
#define IDC_edtPLANARREAR               6014
#define IDC_cmbFileUSER4                7000
#define IDC_STATIC_10                   7008
#define IDC_STATIC_11                   7009
#define IDC_STATIC_12                   7010
#define IDC_STATIC_13                   7011
#define IDC_edtFileUSER5                7112
#define IDC_edtFileUSER6                7113
#define IDC_edtFileUSER19               7218
#define IDC_edtUSER20                   7219
#define IDC_edtSLU_PHONE                7219
#define IDC_edtFileUSER20               7219
#define IDC_STATIC_PASS                 7230
#define IDD_SYS01_SVC_009               8170
#define IDD_SYS01_SVC_004               8171
#define IDD_SYS01_SVC_014               8172
#define IDD_SYS01_SVC_015               8173
#define IDD_KL_SEARCH_LOAN_INFO         8173
#define IDD_KL_SET_USERNO               8188
#define IDD_BO_LOC_3133                 8510
#define IDD_CARDPASSWD_DLG              8511
#define IDD_MESSAGE_DIALOG              8512
#define IDD_LOAN_MANAGE_VALUE           8513
#define IDD_INPUT_RESERVATION_EXPIRE_DAY 8514
#define IDD_BO_LOC_3115                 8515
#define IDD_LOAN_BOOK_LIST_DLG          8516
#define IDD_BO_LOC_3170                 8517
#define IDD_BO_LOC_3130                 8518
#define IDD_RESERVATION_INFO            8519
#define IDD_BO_LOC_3131                 8520
#define IDD_BO_LOC_3132                 8521
#define IDD_LOAN_APPENDIX_LIST_DLG      8522
#define IDD_RETURN_APPENDIX_LIST_DLG    8523
#define IDD_LOAN_HISTORY                8524
#define IDD_BO_LOC_3170_RESERVEINFO_DLG 8525
#define IDD_RESERVELINKBOOKINFODLG_DIALOG 8526
#define IDD_FEE_ARREAR_RECEIPT          8527
#define IDD_LOAN_FEE_LOANSTOP           8528
#define IDD_BO_LOC_RECEIPT_PRINT_DLG    8529
#define IDD_BO_LOC_RECEIPT_PREVIEW_DLG  8530
#define IDD_BO_LOC_RECEIPT_SET_DLG      8531
#define IDD_BO_LOC_RECEIPT_SEARCH_DLG   8532
#define IDD_BO_LOC_LOAN_DATE            8533
#define IDD_BO_LOC_3130_2               8534
#define IDD_KL_FEE_LIST                 8736
#define IDD_KL_PAYMENT_LIST             8736
#define IDC_edtDUM_REMARK               9247
#define IDC_edtKLUserSettingRemark      9247
#define IDC_btnDUM_REMARK               9249
#define IDD_LIB_LIST                    9258
#define IDC_EDIT_CIVILNUM1              9262
#define IDC_edtSLU_CIVILNO              9262
#define IDC_edtKUI_CivilNo1             9262
#define IDC_edtKUI_CivilNo2             9263
#define IDC_EDT_BSC_RESERVE_VOL         9268
#define IDC_BTN_BSC_OFF_RESERVE_VOL     9269
#define IDC_BTN_BSC_ACTIVE_RESERVE_VOL  9270
#define IDC_BTN_SEND_SMS_RESERVE_VOL    9271
#define IDC_BTN_PRINT_RESERVE_VOL       9272
#define IDD_SMS_PREVIEW                 9277
#define IDC_STATIC_FAILED_PRINT_3170    9278
#define IDC_EDIT_SMS_MSG                9278
#define IDC_STATIC_FAILED_PRINT_3170_VR 9279
#define IDC_EDIT_SMS_RECEIVEPHONE       9279
#define IDC_EDIT_SMS_SENDPHONE          9280
#define IDC_EDIT_SMS_LENGTH             9281
#define IDD_KL_OTHER_RETURN_SELECT_BOOK 9734
#define IDC_gridLOANMAIN                10000
#define IDD_KL_OTHER_RETURN_MAIN        10265
#define IDD_KL_OTHER_RETURN_REQUEST     10266
#define IDD_KL_OTEHR_RETURN_OFFER       10267
#define IDD_ILL_SEARCH_BOOK             10276
#define IDD_ILL_SEARCH_BOOK_LIST        10279
#define IDD_ILL_RETURN_SEARCH_BOOK      10281
#define IDD_ILL_LOAN                    10282
#define IDD_ILL_RETURN                  10283
#define IDD_ILL_RETURN_WE               10284
#define IDD_ILL_RETURN_OTHER            10285
#define IDC_TAB_MAIN                    11000
#define IDC_grid                        11002
#define IDC_cmb                         11005
#define IDC_Tab_SEARCH_BOOK_LIST        11030
#define IDC_edtDATE1                    11059
#define IDC_edtDATE2                    11060
#define IDC_edtDATE3                    11061
#define IDC_edtDATE4                    11062
#define IDC_edtDATE5                    11063
#define IDC_edtDATE6                    11064
#define IDC_edtDATE7                    11065
#define IDC_edtDATE8                    11066
#define IDC_edtDATE9                    11067
#define IDC_edtDATE10                   11068
#define IDC_edt11                       11069
#define IDC_edt12                       11070
#define IDC_edt13                       11071
#define IDC_edt14                       11072
#define IDC_edt15                       11073
#define IDC_edt16                       11074
#define IDC_STATIC_EMAIL                11098
#define IDC_grid_APPENDIX_LIST          11116
#define IDD_ILL_RETURN_BOOK_SEARCH      12467
#define IDD_LOAN_HISTORY2               12468
#define IDD_LOAN_APPENDIX_LIST2_DLG     12469
#define IDD_RETURN_APPENDIX_LIST2_DLG   12470
#define IDD_LOAN_FAIL_LIST              12471
#define IDD_RETURN_MISSING_LIST         12472
#define IDD_RESERVATION_SHELF           12476
#define IDD_RESERVATION_OBJECT          12477
#define IDD_KL_USER_IMPORT              14043
#define IDD_KL_OTHER_LOAN_LIST          15060
#define IDD_KL_USER_SYNC                15535
#define IDD_ILL_APL_APPENDIX            19165
#define IDD_KL_USER_SWITCH              19162
#define IDD_ILL_RESERVE_CONVERT_LIB_DLG 19163
#define IDD_KL_OTHER_RETURN_DELIVERY    19169
#define IDD_KL_CERTIFY                  19176
#define IDC_datDATE1                    21014
#define IDC_datDATE2                    21015
#define IDC_chkReq_RESERVATION			21016
#define IDC_btnCLOSE_LOAN_BOOK_LIST     22003
#define IDC_btnCLOSE_USER_SELECT        22003
#define IDC_btnSLU_CLOSE                22003
#define IDC_btnCOTINUE                  22004
#define IDC_btnUSER_SELECT              22004
#define IDC_btnSLU_SELECT               22004
#define IDB_BSC_OFF                     22005
#define IDB_BSC_ON                      22006
#define IDB_BSC_ACTIVE                  22007
#define IDD_SEARCH_LOAN_USER            22013
#define IDD_RESERVATION_PROC            22014
#define IDD_RESERVATION_UNMANNED        22015
#define IDD_RESERVATION_PROC_VOL        22016
#define IDD_RESERVATION_OBJECT_VOL      22017
#define IDD_SLC_SELECT                  22018
#define IDD_SECURITY_AGAIN              22019
#define IDD_RETURN_CHECK                22020
#define IDD_PREMIUM_MEMBER              22021
#define IDD_KL_USER_SEARCH              22022
#define IDD_KL_USER_SETTING             22023
#define IDD_KL_USER_LOAN_INFO           22024
#define IDD_BO_LOC_ARREAR               22025
#define IDD_BO_LOC_3130_3               22026
#define IDD_KL_USER_IMPORT_SET          22027
#define IDD_ILL_APL_3100                22028
#define IDD_BO_LOC_ANALYSIS_CHOOSE      22029
#define IDD_PRESERVATION_LOAN           22030
#define IDD_PRESERVATION_RETURN         22031
#define IDD_PRESERVATION_RETURN_OTHER   22032
#define IDD_PRESERVATION_RETURN_WE      22033
#define IDD_PRESERVATION_RETURN_SEARCH_BOOK 22034
#define IDC_chkKUI_SMS                  22037
#define IDC_chkKUI_MAIL                 22040
#define IDC_sNUM_TYPE                   22064
#define IDC_edtFEE_PAYMENT              22080
#define IDC_btnPREVIEW2                 22086
#define IDC_BTN_BSC_OFF                 22091
#define IDC_BTN_BSC_ACTIVE              22092
#define IDC_RADIO_LOAN1                 22121
#define IDC_radSLU_ALL                  22121
#define IDC_RADIO_LOAN2                 22122
#define IDC_radSLU_MAN                  22122
#define IDC_RADIO_LOAN3                 22123
#define IDC_radSLU_WOMAN                22123
#define IDC_radKLUserSettingMAILN       22124
#define IDC_btnKUI_Certification        22127
#define IDC_btnKUS_LibSearch            22149
#define IDC_gridKUS_Lib                 22151
#define IDC_btnKUS_Switch               22153
#define IDC_btnKUS_UserSearch           22154
#define IDC_btnRenumber                 22192
#define IDC_btnKSUClose                 22193
#define IDC_edtKUS_STATEMENT            22225
#define IDC_stcKL_USER_SETTING          22226
#define IDC_edtKLCertifyName            22227
#define IDC_edtKLCertifyCvilNo1         22228
#define IDC_edtKLCertifyCvilNo2         22229
#define IDC_btnKLCertify                22230
#define IDC_btnKLCertifyClose           22234
#define IDC_stcKLCertifyMassage2        22236
#define IDC_stcKLCertifyFailMassage     22238
#define IDC_edtRI_TITLE_INFO            25501
#define IDC_edtRI_AUTHOR_INFO           25502
#define IDC_edtRI_PUB_INFO              25503
#define IDC_btnR_CLOSE                  25504
#define IDC_btnR_CANCEL                 25505
#define IDC_gridRI_BOOK                 25506
#define IDC_gridRI_OTHERS               25507
#define IDC_gridRI_USER                 25508
#define IDC_btnMAKE_REXPIRE             25509
#define IDC_btnRESERVE_LINK             25510
#define IDC_btnS_EMAIL                  25511
#define IDC_VR_BOOK_LIST                25512
#define IDC_btnLINK_CANCEL              25512
#define IDC_btnVR_SELECT                25514
#define IDC_btnVR_CLOSE                 25515
#define IDC_MAINGRID2                   27001
#define IDC_MAINGRID_USER               27001
#define IDC_gridSLU_MAIN                27001
#define IDC_BOOKLISTGRID                28000
#define IDC_grid_SEARCH_BOOK_LIST_MO    28000
#define IDC_BOOKLISTGRID2               28001
#define IDC_grid_SEARCH_BOOK_LIST_SE    28001
#define IDC_GRID_RESERV_BOOK_LIST       28555
#define IDC_GRID_RESERV_BOOK_INFO       28556
#define IDC_GRID_RESERV_USERLIST        28558
#define IDC_cmbFileUSER6                29002
#define IDC_gridARREARList              29003
#define IDC_btnRFID_RECORD_BOOK			29004
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1085
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1358
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
