// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vcdatagrid.h"


/////////////////////////////////////////////////////////////////////////////
// CVcDataGrid properties

/////////////////////////////////////////////////////////////////////////////
// CVcDataGrid operations

short CVcDataGrid::GetColumnCount()
{
	short result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I2, (VOID*)&result, NULL);
	return result;
}

VOID CVcDataGrid::SetColumnCount(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x1, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CVcDataGrid::GetColumnLabelCount()
{
	short result;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_I2, (VOID*)&result, NULL);
	return result;
}

VOID CVcDataGrid::SetColumnLabelCount(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x2, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CVcDataGrid::GetRowLabelCount()
{
	short result;
	InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_I2, (VOID*)&result, NULL);
	return result;
}

VOID CVcDataGrid::SetRowLabelCount(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x3, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CVcDataGrid::GetRowCount()
{
	short result;
	InvokeHelper(0x4, DISPATCH_PROPERTYGET, VT_I2, (VOID*)&result, NULL);
	return result;
}

VOID CVcDataGrid::SetRowCount(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x4, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

VOID CVcDataGrid::DeleteColumns(short Column, short Count)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Column, Count);
}

VOID CVcDataGrid::InsertColumns(short Column, short Count)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Column, Count);
}

VOID CVcDataGrid::DeleteColumnLabels(short LabelIndex, short Count)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 LabelIndex, Count);
}

VOID CVcDataGrid::InsertColumnLabels(short LabelIndex, short Count)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 LabelIndex, Count);
}

VOID CVcDataGrid::DeleteRows(short Row, short Count)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Row, Count);
}

VOID CVcDataGrid::InsertRows(short Row, short Count)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Row, Count);
}

VOID CVcDataGrid::DeleteRowLabels(short LabelIndex, short Count)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 LabelIndex, Count);
}

VOID CVcDataGrid::InsertRowLabels(short LabelIndex, short Count)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 LabelIndex, Count);
}

VOID CVcDataGrid::RandomDataFill()
{
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

VOID CVcDataGrid::SetSize(short RowLabelCount, short ColumnLabelCount, short DataRowCount, short DataColumnCount)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 RowLabelCount, ColumnLabelCount, DataRowCount, DataColumnCount);
}

VOID CVcDataGrid::InitializeLabels()
{
	InvokeHelper(0xf, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

VOID CVcDataGrid::RandomFillColumns(short Column, short Count)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Column, Count);
}

VOID CVcDataGrid::RandomFillRows(short Row, short Count)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Row, Count);
}

VOID CVcDataGrid::MoveData(short Top, short Left, short Bottom, short Right, short OverOffset, short DownOffset)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Top, Left, Bottom, Right, OverOffset, DownOffset);
}

VOID CVcDataGrid::GetData(short Row, short Column, double* DataPoint, short* nullFlag)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_PR8 VTS_PI2;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Row, Column, DataPoint, nullFlag);
}

VOID CVcDataGrid::SetData(short Row, short Column, double DataPoint, short nullFlag)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_R8 VTS_I2;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Row, Column, DataPoint, nullFlag);
}

CString CVcDataGrid::GetColumnLabel(short Column, short LabelIndex)
{
	CString result;
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x15, DISPATCH_PROPERTYGET, VT_BSTR, (VOID*)&result, parms,
		Column, LabelIndex);
	return result;
}

VOID CVcDataGrid::SetColumnLabel(short Column, short LabelIndex, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR;
	InvokeHelper(0x15, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 Column, LabelIndex, lpszNewValue);
}

CString CVcDataGrid::GetCompositeColumnLabel(short Column)
{
	CString result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x16, DISPATCH_PROPERTYGET, VT_BSTR, (VOID*)&result, parms,
		Column);
	return result;
}

CString CVcDataGrid::GetCompositeRowLabel(short Row)
{
	CString result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x17, DISPATCH_PROPERTYGET, VT_BSTR, (VOID*)&result, parms,
		Row);
	return result;
}

CString CVcDataGrid::GetRowLabel(short Row, short LabelIndex)
{
	CString result;
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x18, DISPATCH_PROPERTYGET, VT_BSTR, (VOID*)&result, parms,
		Row, LabelIndex);
	return result;
}

VOID CVcDataGrid::SetRowLabel(short Row, short LabelIndex, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR;
	InvokeHelper(0x18, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 Row, LabelIndex, lpszNewValue);
}
