// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "barcod.h"

/////////////////////////////////////////////////////////////////////////////
// CBarcod

IMPLEMENT_DYNCREATE(CBarcod, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CBarcod properties

short CBarcod::GetBarWidth()
{
	short result;
	GetProperty(0x2, VT_I2, (VOID*)&result);
	return result;
}

VOID CBarcod::SetBarWidth(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

long CBarcod::GetDirection()
{
	long result;
	GetProperty(0x3, VT_I4, (VOID*)&result);
	return result;
}

VOID CBarcod::SetDirection(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

CString CBarcod::GetDisplayed()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (VOID*)&result);
	return result;
}

VOID CBarcod::SetDisplayed(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

long CBarcod::GetPrinterHDC()
{
	long result;
	GetProperty(0x5, VT_I4, (VOID*)&result);
	return result;
}

VOID CBarcod::SetPrinterHDC(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

long CBarcod::GetPrinterHeight()
{
	long result;
	GetProperty(0x6, VT_I4, (VOID*)&result);
	return result;
}

VOID CBarcod::SetPrinterHeight(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

long CBarcod::GetPrinterLeft()
{
	long result;
	GetProperty(0x7, VT_I4, (VOID*)&result);
	return result;
}

VOID CBarcod::SetPrinterLeft(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

short CBarcod::GetPrinterScaleMode()
{
	short result;
	GetProperty(0x8, VT_I2, (VOID*)&result);
	return result;
}

VOID CBarcod::SetPrinterScaleMode(short propVal)
{
	SetProperty(0x8, VT_I2, propVal);
}

long CBarcod::GetPrinterTop()
{
	long result;
	GetProperty(0x9, VT_I4, (VOID*)&result);
	return result;
}

VOID CBarcod::SetPrinterTop(long propVal)
{
	SetProperty(0x9, VT_I4, propVal);
}

long CBarcod::GetPrinterWidth()
{
	long result;
	GetProperty(0xa, VT_I4, (VOID*)&result);
	return result;
}

VOID CBarcod::SetPrinterWidth(long propVal)
{
	SetProperty(0xa, VT_I4, propVal);
}

long CBarcod::GetStyle()
{
	long result;
	GetProperty(0xb, VT_I4, (VOID*)&result);
	return result;
}

VOID CBarcod::SetStyle(long propVal)
{
	SetProperty(0xb, VT_I4, propVal);
}

long CBarcod::GetUPCNotches()
{
	long result;
	GetProperty(0xc, VT_I4, (VOID*)&result);
	return result;
}

VOID CBarcod::SetUPCNotches(long propVal)
{
	SetProperty(0xc, VT_I4, propVal);
}

CString CBarcod::GetVersion()
{
	CString result;
	GetProperty(0xd, VT_BSTR, (VOID*)&result);
	return result;
}

VOID CBarcod::SetVersion(LPCTSTR propVal)
{
	SetProperty(0xd, VT_BSTR, propVal);
}

OLE_COLOR CBarcod::GetBackColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_BACKCOLOR, VT_I4, (VOID*)&result);
	return result;
}

VOID CBarcod::SetBackColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_BACKCOLOR, VT_I4, propVal);
}

CString CBarcod::GetCaption()
{
	CString result;
	GetProperty(DISPID_CAPTION, VT_BSTR, (VOID*)&result);
	return result;
}

VOID CBarcod::SetCaption(LPCTSTR propVal)
{
	SetProperty(DISPID_CAPTION, VT_BSTR, propVal);
}

BOOL CBarcod::GetEnabled()
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (VOID*)&result);
	return result;
}

VOID CBarcod::SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

OLE_COLOR CBarcod::GetForeColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_FORECOLOR, VT_I4, (VOID*)&result);
	return result;
}

VOID CBarcod::SetForeColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_FORECOLOR, VT_I4, propVal);
}

OLE_HANDLE CBarcod::GetHWnd()
{
	OLE_HANDLE result;
	GetProperty(DISPID_HWND, VT_I2, (VOID*)&result);
	return result;
}

VOID CBarcod::SetHWnd(OLE_HANDLE propVal)
{
	SetProperty(DISPID_HWND, VT_I2, propVal);
}

long CBarcod::GetAlignment()
{
	long result;
	GetProperty(0x1, VT_I4, (VOID*)&result);
	return result;
}

VOID CBarcod::SetAlignment(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

CString CBarcod::GetExtension()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (VOID*)&result);
	return result;
}

VOID CBarcod::SetExtension(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CBarcod operations

VOID CBarcod::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
