//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TocSyntaxCheck.rc
//
#define IDD_ERROR_LOG                   5875
#define IDD_TIFF_FILE_DLG               5876
#define IDC_ERROR_LIST                  1002
#define IDC_tTIFF_FILE_TREE             1003

#define	IDS_STRING_5001		5001
#define	IDS_STRING_5002		5002
#define	IDS_STRING_5003		5003
#define	IDS_STRING_5004		5004
#define	IDS_STRING_5005		5005
#define	IDS_STRING_5006		5006
#define	IDS_STRING_5007		5007
#define	IDS_STRING_5008		5008
#define	IDS_STRING_5009		5009
#define	IDS_STRING_5010		5010
#define	IDS_STRING_5011		5011
#define	IDS_STRING_5012		5012
#define	IDS_STRING_5013		5013
#define	IDS_STRING_5014		5014
#define	IDS_STRING_5015		5015
#define	IDS_STRING_5016		5016
#define	IDS_STRING_5017		5017
#define	IDS_STRING_5018		5018
#define	IDS_STRING_5019		5019
#define	IDS_STRING_5020		5020
#define	IDS_STRING_5021		5021
#define	IDS_STRING_5022		5022
#define	IDS_STRING_5023		5023
#define	IDS_STRING_5024		5024
#define	IDS_STRING_5025		5025
#define	IDS_STRING_5026		5026
#define	IDS_STRING_5027		5027
#define	IDS_STRING_5028		5028
#define	IDS_STRING_5029		5029
#define	IDS_STRING_5030		5030
#define	IDS_STRING_5031		5031
#define	IDS_STRING_5032		5032

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1004
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
